### ISSUE TITLE
The provider Yqcloud can't work after update the newest version

### ISSUE THREAD

**Issue by zjhgx163** [xtekky/gpt4free#1007]
Traceback (most recent call last):
  File "/Users/gaoxianghu/opt/anaconda3/envs/aliyunpanCrawler/lib/python3.10/site-packages/g4f/Provider/base_provider.py", line 109, in create_completion
    yield loop.run_until_complete(gen.__anext__())
  File "/Users/gaoxianghu/opt/anaconda3/envs/aliyunpanCrawler/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/Users/gaoxianghu/opt/anaconda3/envs/aliyunpanCrawler/lib/python3.10/site-packages/g4f/Provider/Yqcloud.py", line 26, in create_async_generator
    async with session.post("https://api.aichatos.cloud/api/generateStream", proxy=proxy, json=payload) as response:
  File "/Users/gaoxianghu/opt/anaconda3/envs/aliyunpanCrawler/lib/python3.10/site-packages/aiohttp/client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "/Users/gaoxianghu/opt/anaconda3/envs/aliyunpanCrawler/lib/python3.10/site-packages/aiohttp/client.py", line 447, in _request
    tm = TimeoutHandle(self._loop, real_timeout.total)
AttributeError: 'int' object has no attribute 'total'

**Comment by hlohaus** [comment]
aiorequests doesn't have a timeout by default. There is no reason for a timeout config. I already removed them again in my PR.
