### ISSUE TITLE
bing not process

### ISSUE THREAD

**Issue by xmyano** [xtekky/gpt4free#1036]
create: Traceback (most recent call last):
  File "/www/wwwroot/gpt4free/etc/testing/test_chat_completion.py", line 9, in <module>
    for response in g4f.ChatCompletion.create(
  File "/www/wwwroot/gpt4free/g4f/Provider/base_provider.py", line 111, in create_completion
    yield loop.run_until_complete(gen.__anext__())
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/Python-3.11.0/Lib/asyncio/base_events.py", line 650, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/www/wwwroot/gpt4free/g4f/Provider/Bing.py", line 251, in stream_generate
    conversation = await create_conversation(session, proxy)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/www/wwwroot/gpt4free/g4f/Provider/Bing.py", line 66, in create_conversation
    data = await response.json()
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client_reqrep.py", line 1104, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: ', url=URL('https://www.bing.com/turing/conversation/create?bundleVersion=1.1150.3')          这个是怎么回事

**Comment by D-Octopus** [comment]
我也遇到了同样的问题，但是等了一晚就好了。感觉好像是请求次数过多了，bing chat每天每人好像只有300次请求次数。

**Comment by xmyano** [comment]
> 我也遇到了同样的问题，但是等了一晚就好了。感觉好像是请求次数过多了，bing chat每天每人好像只有300次请求次数。 I also encountered the same issue, but it was resolved after waiting for one night. It seems like the problem might have been caused by making too many requests. It appears that Bing Chat allows only 300 requests per person per day.

SUID not found

**Comment by clin366** [comment]
这个问题好像一直没有解决
