### ISSUE TITLE
Vercel Provider Error / Function Calling

### ISSUE THREAD

**Issue by Kobeeeef** [xtekky/gpt4free#1083]
**Bug description**
I am getting error while using the vercel provider and trying to use gpt-3.5-turbo-16k-0613 for function calling
error:
Traceback (most recent call last):
  File "C:\Users\kobel\PycharmProjects\testing\GPT_CHAT.py", line 241, in <module>
    get_response("hello")
  File "C:\Users\kobel\PycharmProjects\testing\GPT_CHAT.py", line 230, in get_response
    response = g4f.ChatCompletion.create(
  File "C:\Users\kobel\PycharmProjects\testing\venv\lib\site-packages\g4f\__init__.py", line 75, in create
    return result if stream else ''.join(result)
  File "C:\Users\kobel\PycharmProjects\testing\venv\lib\site-packages\g4f\Provider\Vercel.py", line 36, in create_completion
    'custom-encoding'   : get_anti_bot_token(),
  File "C:\Users\kobel\PycharmProjects\testing\venv\lib\site-packages\g4f\Provider\Vercel.py", line 103, in get_anti_bot_token
    raw_token = json.dumps({'r': execjs.compile(js_script).call(''), 't': raw_data['t']}, 
  File "C:\Users\kobel\PycharmProjects\testing\venv\lib\site-packages\execjs\_abstract_runtime_context.py", line 37, in call
    return self._call(name, *args)
  File "C:\Users\kobel\PycharmProjects\testing\venv\lib\site-packages\execjs\_external_runtime.py", line 92, in _call
    return self._eval("{identifier}.apply(this, {args})".format(identifier=identifier, args=args))
  File "C:\Users\kobel\PycharmProjects\testing\venv\lib\site-packages\execjs\_external_runtime.py", line 78, in _eval
    return self.exec_(code)
  File "C:\Users\kobel\PycharmProjects\testing\venv\lib\site-packages\execjs\_abstract_runtime_context.py", line 18, in exec_
    return self._exec_(source)
  File "C:\Users\kobel\PycharmProjects\testing\venv\lib\site-packages\execjs\_external_runtime.py", line 88, in _exec_
    return self._extract_result(output)
  File "C:\Users\kobel\PycharmProjects\testing\venv\lib\site-packages\execjs\_external_runtime.py", line 167, in _extract_result
    raise ProgramError(value)
execjs._exceptions.ProgramError: SyntaxError: Syntax error

code:
g4f.ChatCompletion.create(
        model=g4f.models.gpt_35_turbo_16k_0613,
        messages=[{"role": "user", "content": "hello"}],
        functions=get_functions(),
        provider=g4f.Provider.Vercel
    )

**Additional context**
how would i use function calling within this?

**Comment by xtekky** [comment]
I dont really see any issue with Vercel, are you using g4f from pip ? 

```py
import g4f

messages = [
    {"role": "user", "content": "if there is 10 birds on a tree and I shoot one, how many are left"}
]

response = g4f.ChatCompletion.create(model='gpt-3.5-turbo', provider=g4f.Provider.Vercel,
                                     messages=messages, stream=True)

for message in response:
    print(message)
```

<img width="528" alt="image" src="https://github.com/xtekky/gpt4free/assets/98614666/949f6d28-ca36-48bf-beee-bde1c9a6123f">

**Comment by Kobeeeef** [comment]
Yes i am using the g4f package from pip.

g4f version: g4f-0.1.6.6

code:
import g4f

messages = [
    {"role": "user", "content": "if there is 10 birds on a tree and I shoot one, how many are left"}
]

response = g4f.ChatCompletion.create(model='gpt-3.5-turbo', provider=g4f.Provider.Vercel,
                                     messages=messages, stream=True)

for message in response:
    print(message)
   
and same error:
Traceback (most recent call last):
  File "C:\Users\kobel\PycharmProjects\testing\test.py", line 10, in <module>
    for message in response:
  File "C:\Users\kobel\PycharmProjects\testing\venv\lib\site-packages\g4f\Provider\Vercel.py", line 36, in create_completion
    'custom-encoding'   : get_anti_bot_token(),
  File "C:\Users\kobel\PycharmProjects\testing\venv\lib\site-packages\g4f\Provider\Vercel.py", line 103, in get_anti_bot_token
    raw_token = json.dumps({'r': execjs.compile(js_script).call(''), 't': raw_data['t']}, 
  File "C:\Users\kobel\PycharmProjects\testing\venv\lib\site-packages\execjs\_abstract_runtime_context.py", line 37, in call
    return self._call(name, *args)
  File "C:\Users\kobel\PycharmProjects\testing\venv\lib\site-packages\execjs\_external_runtime.py", line 92, in _call
    return self._eval("{identifier}.apply(this, {args})".format(identifier=identifier, args=args))
  File "C:\Users\kobel\PycharmProjects\testing\venv\lib\site-packages\execjs\_external_runtime.py", line 78, in _eval
    return self.exec_(code)
  File "C:\Users\kobel\PycharmProjects\testing\venv\lib\site-packages\execjs\_abstract_runtime_context.py", line 18, in exec_
    return self._exec_(source)
  File "C:\Users\kobel\PycharmProjects\testing\venv\lib\site-packages\execjs\_external_runtime.py", line 88, in _exec_
    return self._extract_result(output)
  File "C:\Users\kobel\PycharmProjects\testing\venv\lib\site-packages\execjs\_external_runtime.py", line 167, in _extract_result
    raise ProgramError(value)
execjs._exceptions.ProgramError: SyntaxError: Syntax error

**Comment by yasir-io** [comment]
> I dont really see any issue with Vercel, are you using g4f from pip ?
> 
> ```python
> import g4f
> 
> messages = [
>     {"role": "user", "content": "if there is 10 birds on a tree and I shoot one, how many are left"}
> ]
> 
> response = g4f.ChatCompletion.create(model='gpt-3.5-turbo', provider=g4f.Provider.Vercel,
>                                      messages=messages, stream=True)
> 
> for message in response:
>     print(message)
> ```
> 
> <img alt="image" width="528" src="https://user-images.githubusercontent.com/98614666/275470067-949f6d28-ca36-48bf-beee-bde1c9a6123f.png">

Please help me Vercel is saying no javascript runtime found how to fix it

**Comment by yasir-io** [comment]
Please anyone help me i am using verc but it's saying no javascript runtime found 😭
