### ISSUE TITLE
GptGod fail

### ISSUE THREAD

**Issue by zjhgx163** [xtekky/gpt4free#1105]
Traceback (most recent call last):
  File "/home/opc/git/yunpan_crawler/g4f_provider_test.py", line 261, in <module>
    response = g4f.ChatCompletion.create(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/opc/miniconda3/lib/python3.11/site-packages/g4f/__init__.py", line 74, in create
    return result if stream else ''.join(result)
                                 ^^^^^^^^^^^^^^^

**Comment by xtekky** [comment]
hello, please try other providers or use the retryprovider by not setting the provider when creating a completion
