### ISSUE TITLE
A new bug in the current version 

### ISSUE THREAD

**Issue by egcash** [xtekky/gpt4free#1111]
Interference API isn't running, it's displayijg the value error, Which  is 

""""
raise ValueError("Invalid host/port specified.")
ValueError: Invalid host/port specified.
""""

I'm using Docker btw

**Comment by St-ZFeng** [comment]
The same
```
Traceback (most recent call last):
  File "/usr/local/bin/g4f", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/site-packages/g4f/cli.py", line 20, in main
    Api(g4f).run('localhost:1337', 8)
  File "/usr/local/lib/python3.10/site-packages/g4f/api/__init__.py", line 68, in run
    serve(self.app, host=host, port=port, ident=None, threads=threads)
  File "/usr/local/lib/python3.10/site-packages/waitress/__init__.py", line 13, in serve
    server = _server(app, **kw)
  File "/usr/local/lib/python3.10/site-packages/waitress/server.py", line 78, in create_server
    last_serv = TcpWSGIServer(
  File "/usr/local/lib/python3.10/site-packages/waitress/server.py", line 244, in __init__
    self.bind_server_socket()
  File "/usr/local/lib/python3.10/site-packages/waitress/server.py", line 361, in bind_server_socket
    self.bind(sockaddr)
  File "/usr/local/lib/python3.10/site-packages/waitress/wasyncore.py", line 396, in bind
    return self.socket.bind(addr)
OSError: [Errno 99] Cannot assign requested address
```

**Comment by xtekky** [comment]
fixed

**Comment by St-ZFeng** [comment]
Should use 0.0.0.0 not 127.0.0.1 for docker. Otherwise, the port cannot be mapped successfully. In addition, I received the following reminder: `"Install Flask with the 'async' extra in order to use async views."` The problem was solved when I downloaded the correct Flask package. I don't know if this is a problem with the wrong dependencies.

**Comment by egcash** [comment]
> Should use 0.0.0.0 not 127.0.0.1 for docker. Otherwise, the port cannot be mapped successfully. In addition, I received the following reminder: `"Install Flask with the 'async' extra in order to use async views."` The problem was solved when I downloaded the correct Flask package. I don't know if this is a problem with the wrong dependencies.

Flask-async what?
Can you please explain, I'm having the exact issue.

**Comment by xiaoranchenwai** [comment]
> Should use 0.0.0.0 not 127.0.0.1 for docker. Otherwise, the port cannot be mapped successfully. In addition, I received the following reminder: `"Install Flask with the 'async' extra in order to use async views."` The problem was solved when I downloaded the correct Flask package. I don't know if this is a problem with the wrong dependencies.

What version of flask are you using?
