### ISSUE TITLE
Is this a bug?

### ISSUE THREAD

**Issue by www963257827** [xtekky/gpt4free#112]
2023-04-25 09:23:11.393 Uncaught app exception
Traceback (most recent call last):
  File "C:\Users\JX624\AppData\Local\Programs\Python\Python310\lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 565, in _run_script
    exec(code, module.__dict__)
  File "C:\AI\gpt4free-main\streamlit_app.py", line 33, in <module>
    answer = phind_get_answer(question_text_area)
  File "C:\AI\gpt4free-main\streamlit_app.py", line 11, in phind_get_answer
    results     = phind.Search.create(question, actualSearch = True),
  File "C:\AI\gpt4free-main\phind\__init__.py", line 96, in create
    'browserLanguage': language}).json()['rawBingResults']
  File "C:\Users\JX624\AppData\Local\Programs\Python\Python310\lib\site-packages\curl_cffi\requests\cookies.py", line 54, in json
    return loads(self.content, **kw)
  File "C:\Users\JX624\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\JX624\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\JX624\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by rupeshs** [comment]
Phind is broken.

**Comment by repollo** [comment]
specific to phind,

you need to create your own, `phind.cf_clearance`, `phind.user_agent` objects for it to work as suggested here, https://github.com/xtekky/gpt4free/issues/97

**Comment by xtekky** [comment]
thanks @repollo
