### ISSUE TITLE
OpenAI provider giving a NoneType error

### ISSUE THREAD

**Issue by Meshwa428** [xtekky/gpt4free#1155]
**Known Issues**
- The open AI provider is giving this sort of NoneType error
- even after providing the message and the access token

**Environment**
- Python 3.11.4
- location India

**Additional context**
Error
```bash
Traceback (most recent call last):
  File "P:\Python\Audio classification\test.py", line 80, in <module>
    response = g4f.ChatCompletion.create(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vandu\AppData\Local\Programs\Python\Python311\Lib\site-packages\g4f\__init__.py", line 75, in create
    return result if stream else ''.join(result)
                                 ^^^^^^^^^^^^^^^
  File "C:\Users\vandu\AppData\Local\Programs\Python\Python311\Lib\site-packages\g4f\Provider\base_provider.py", line 111, in create_completion
    yield loop.run_until_complete(gen.__anext__())
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vandu\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\vandu\AppData\Local\Programs\Python\Python311\Lib\site-packages\g4f\Provider\needs_auth\OpenaiChat.py", line 68, in create_async_generator
    if "message" not in line or "message_type" not in line["message"]["metadata"]:
                                                      ~~~~~~~~~~~~~~~^^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
```

Code used:
```py
import g4f

response = g4f.ChatCompletion.create(
    messages=[{"role": "user", "content": "hello"}],
    provider=g4f.Provider.OpenaiChat,
    model=g4f.models.default,  # type: ignore
    auth="token",
    access_token="my access token ...",
)
print(response)
```

**Comment by Meshwa428** [comment]
I sort of figured it out what is happening here:

see, in the openai provider file i just tries to print the line variable of this part

line 56 to some what like 78 or so


```py
            async with session.post(f"{cls.url}/backend-api/conversation", json=data) as response:
                response.raise_for_status()
                last_message = ""
                async for line in response.iter_lines():
                    if line.startswith(b"data: "):
                        line = line[6:]
                        if line == b"[DONE]":
                            break
                        try:
                            line = json.loads(line)
                        except:
                            continue

                        print(line)    #<----    see here
                        if "message" not in line or "message_type" not in line["message"]["metadata"]:
                            continue
                        if line["message"]["metadata"]["message_type"] == "next":
                            new_message = line["message"]["content"]["parts"][0]
                            yield new_message[len(last_message):]
                            last_message = new_message

```


and i got this as a response, there are 3 of them so i am just providing the last 2:
```json
{'message': {'id': 'b1b1f239-e4fc-44d9-87a3-8b9f9d093184', 'author': {'role': 'user', 'name': None, 'metadata': {}}, 'create_time': 1698243907.03428, 'update_time': None, 'content': {'content_type': 'text', 'parts': ['Assistant: I am GPT 4\nUser: can you tell me that again\nAssistant:']}, 'status': 'finished_successfully', 'end_turn': None, 'weight': 1.0, 'metadata': {'timestamp_': 'absolute', 'message_type': None}, 'recipient': 'all'}, 'conversation_id': '0ad8c111-4d08-4649-8d24-8ae93a41d344', 'error': None}
{'message': None, 'conversation_id': '0ad8c111-4d08-4649-8d24-8ae93a41d344', 'error': 'Our systems have detected unusual activity from your system. Please try again later.'}
```

so as you can see there is no metadata variable here. I think OpenAI is blocking the response, so i think we have to  find some other way to use it

**Comment by thanhtoan1196** [comment]
any updates?

**Comment by Meshwa428** [comment]
Not really, but I'm trying to figure it out, if I got it then I'll post it here

**Comment by hlohaus** [comment]
the akrosa_token is maybe missing. In the master branch i added it.

**Comment by Meshwa428** [comment]
Thanks bro👍. I was very confused while doing the stuff but anyways, thanks

**Comment by Meshwa428** [comment]
Any updates??

**Comment by Meshwa428** [comment]
Any updates, is there any one to fix this bruhh?? Cause I don't know how to😭

**Comment by thanhtoan1196** [comment]
Any updates?

**Comment by thanhtoan1196** [comment]
is there any one to fix this?

**Comment by Meshwa428** [comment]
It's fixed in latest updates 🙂

**Comment by Frehyyy** [comment]
> It's fixed in latest updates 🙂

Where can I see your latest update?

**Comment by Meshwa428** [comment]
Dude, just install the latest version of the package

Use this command

```bash
pip install -U g4f
```
