### ISSUE TITLE
How to fix a bug?

### ISSUE THREAD

**Issue by SergeyStratus** [xtekky/gpt4free#118]
2023-04-25 10:07:22.024 Uncaught app exception
Traceback (most recent call last):
  File "C:\pyhton\lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 565, in _run_script
    exec(code, module.__dict__)
  File "C:\Users\STRATUSON\gpt4free-main\streamlit_app.py", line 33, in <module>
    answer = phind_get_answer(question_text_area)
  File "C:\Users\STRATUSON\gpt4free-main\streamlit_app.py", line 11, in phind_get_answer
    results     = phind.Search.create(question, actualSearch = True),
  File "C:\Users\STRATUSON\gpt4free-main\phind\__init__.py", line 96, in create
    'browserLanguage': language}).json()['rawBingResults']
  File "C:\pyhton\lib\site-packages\curl_cffi\requests\cookies.py", line 54, in json
    return loads(self.content, **kw)
  File "C:\pyhton\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\pyhton\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\pyhton\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by xtekky** [comment]
Hi, please refer to the readme and set the cf_clearance / user_agent variables

**Comment by SergeyStratus** [comment]
> 

Thanks for the answer !
And how to do it ?

**Comment by SergeyStratus** [comment]
> Привет, пожалуйста, обратитесь к файлу readme и установите переменные cf_clearance / user_agent

Thanks for the answer !
And how to do it ?

**Comment by SergeyStratus** [comment]
> Привет, пожалуйста, обратитесь к файлу readme и установите переменные cf_clearance / user_agent

![image](https://user-images.githubusercontent.com/130560684/234216549-d088dbbb-516d-4730-9649-a696e52c8f66.png)
This file?

**Comment by onetenthdev** [comment]
hav u try unplugging & restarting

**Comment by SergeyStratus** [comment]
> hav u try unplugging & restarting

I completely restarted my computer, didn't help.
Or do you mean completely reinstall the repository?

**Comment by xtekky** [comment]
fixed it just now, redownload the repo

**Comment by SergeyStratus** [comment]
> fixed it just now, redownload the repo
That bug has been fixed, a new one has appeared
Answer :

An error occured, please make sure you are using a cf_clearance token and correct useragent | Expecting value: line 1 column 1 (char 0)

**Comment by kodiyak** [comment]
> > fixed it just now, redownload the repo
> > That bug has been fixed, a new one has appeared
> > Answer :
> 
> An error occured, please make sure you are using a cf_clearance token and correct useragent | Expecting value: line 1 column 1 (char 0)

Same Here...
