### ISSUE TITLE
Exception: CaptchaChallenge: User needs to solve CAPTCHA to continue.

### ISSUE THREAD

**Issue by xiangdeyue** [xtekky/gpt4free#1253]
After I deployed using docker, I reported the following error when using bing on the web gui:

```
2023-11-15 07:03:25.13 UTCgpt4free-gui-7599dddfdc-tv8fkgpt4free-gui[{'role': 'user', 'content': ' \n hello\n '}, {'role': 'assistant', 'content': '<!doctype html>\n<html lang=en>\n<title>500 Internal Server Error</title>\n<h1>Internal Server Error</h1>\n<p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>\n '}, {'role': 'user', 'content': 'hello'}]
2023-11-15 07:03:25.13 UTCgpt4free-gui-7599dddfdc-tv8fkgpt4free-guiBing
2023-11-15 07:03:25.97 UTCgpt4free-gui-7599dddfdc-tv8fkgpt4free-gui10.8.10.16 - - [15/Nov/2023 07:03:25] "POST /backend-api/v2/conversation HTTP/1.1" 500 -
2023-11-15 07:03:25.97 UTCgpt4free-gui-7599dddfdc-tv8fkgpt4free-guiError on request:
2023-11-15 07:03:25.97 UTCgpt4free-gui-7599dddfdc-tv8fkgpt4free-guiTraceback (most recent call last):
2023-11-15 07:03:25.97 UTCgpt4free-gui-7599dddfdc-tv8fkgpt4free-gui  File "/usr/local/lib/python3.9/site-packages/werkzeug/serving.py", line 362, in run_wsgi
2023-11-15 07:03:25.97 UTCgpt4free-gui-7599dddfdc-tv8fkgpt4free-gui    execute(self.server.app)
2023-11-15 07:03:25.97 UTCgpt4free-gui-7599dddfdc-tv8fkgpt4free-gui  File "/usr/local/lib/python3.9/site-packages/werkzeug/serving.py", line 325, in execute
2023-11-15 07:03:25.97 UTCgpt4free-gui-7599dddfdc-tv8fkgpt4free-gui    for data in application_iter:
2023-11-15 07:03:25.97 UTCgpt4free-gui-7599dddfdc-tv8fkgpt4free-gui  File "/usr/local/lib/python3.9/site-packages/werkzeug/wsgi.py", line 256, in __next__
2023-11-15 07:03:25.97 UTCgpt4free-gui-7599dddfdc-tv8fkgpt4free-gui    return self._next()
2023-11-15 07:03:25.97 UTCgpt4free-gui-7599dddfdc-tv8fkgpt4free-gui  File "/usr/local/lib/python3.9/site-packages/werkzeug/wrappers/response.py", line 32, in _iter_encoded
2023-11-15 07:03:25.97 UTCgpt4free-gui-7599dddfdc-tv8fkgpt4free-gui    for item in iterable:
2023-11-15 07:03:25.97 UTCgpt4free-gui-7599dddfdc-tv8fkgpt4free-gui  File "/app/g4f/gui/server/backend.py", line 58, in stream
2023-11-15 07:03:25.97 UTCgpt4free-gui-7599dddfdc-tv8fkgpt4free-gui    yield from g4f.ChatCompletion.create(
2023-11-15 07:03:25.97 UTCgpt4free-gui-7599dddfdc-tv8fkgpt4free-gui  File "/app/g4f/Provider/base_provider.py", line 112, in create_completion
2023-11-15 07:03:25.97 UTCgpt4free-gui-7599dddfdc-tv8fkgpt4free-gui    yield loop.run_until_complete(gen.__anext__())
2023-11-15 07:03:25.97 UTCgpt4free-gui-7599dddfdc-tv8fkgpt4free-gui  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
2023-11-15 07:03:25.97 UTCgpt4free-gui-7599dddfdc-tv8fkgpt4free-gui    return future.result()
2023-11-15 07:03:25.97 UTCgpt4free-gui-7599dddfdc-tv8fkgpt4free-gui  File "/app/g4f/Provider/Bing.py", line 484, in stream_generate
2023-11-15 07:03:25.97 UTCgpt4free-gui-7599dddfdc-tv8fkgpt4free-gui    raise Exception(f"{result['value']}: {result['message']}")
2023-11-15 07:03:25.97 UTCgpt4free-gui-7599dddfdc-tv8fkgpt4free-guiException: CaptchaChallenge: User needs to solve CAPTCHA to continue.
```

**Comment by NotFenixio** [comment]
Presumably if you're not authenticated, Bing will show a CAPTCHA.
