### ISSUE TITLE
Delete FakeGPT Provider

### ISSUE THREAD

**Issue by amit-pathak11** [xtekky/gpt4free#1265]
FakeGPT suddenly stopped working by giving `IndexError: list index out of range` error. Full error below:

```
Traceback (most recent call last):
  File "D:\x\x\t.py", line 4, in <module>
    response = g4f.ChatCompletion.create(
  File "C:\Users\x\AppData\Local\Programs\Python\Python310\lib\site-packages\g4f\__init__.py", line 77, in create
    return result if stream else ''.join(result)
  File "C:\Users\x\AppData\Local\Programs\Python\Python310\lib\site-packages\g4f\Provider\base_provider.py", line 112, in create_completion
    yield loop.run_until_complete(gen.__anext__())
  File "C:\Users\x\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "C:\Users\x\AppData\Local\Programs\Python\Python310\lib\site-packages\g4f\Provider\FakeGpt.py", line 41, in create_async_generator
    "token_key": random.choice(token_ids),
  File "C:\Users\x\AppData\Local\Programs\Python\Python310\lib\random.py", line 378, in choice
    return seq[self._randbelow(len(seq))]
IndexError: list index out of range
```

**Comment by amit-pathak11** [comment]
It seems like it is too unstable. Sometimes it works, sometimes it doesn't...

**Comment by amit-pathak11** [comment]
Update: they have implemented Cloudflare on their website, delete this provider.

**Comment by thanhtoan1196** [comment]
any updates?
