### ISSUE TITLE
Captcha error for GPT-4

### ISSUE THREAD

**Issue by OmiiiDev** [xtekky/gpt4free#1284]
**Issue for url:** https://liaobots.work/api/chat

**Bug description**
When choosing the GPT-4 model and sending it a message, it prompts yo to do a captcha test to use the api....

**Steps to reproduce**
1. Select GPT-4 Model
2. Enter user prompt and send it
3. See Captcha error

**Error in text version:**
ERROR:root:RetryProvider failed:
Phind: TypeError: Binary Location Must be a String
Liaobots: ClientResponseError: 500, message='Internal Server Error', url=URL('https://liaobots.work/api/chat')
Bing: Exception: CaptchaChallenge: User needs to solve CAPTCHA to continue.
Traceback (most recent call last):
  File "/home/runner/gpt4free/.pythonlibs/lib/python3.10/site-packages/g4f/api/__init__.py", line 85, in chat_completions
    response = g4f.ChatCompletion.create(
  File "/home/runner/gpt4free/.pythonlibs/lib/python3.10/site-packages/g4f/__init__.py", line 76, in create
    return result if stream else ''.join(result)
  File "/home/runner/gpt4free/.pythonlibs/lib/python3.10/site-packages/g4f/Provider/retry_provider.py", line 59, in create_completion
    self.raise_exceptions()
  File "/home/runner/gpt4free/.pythonlibs/lib/python3.10/site-packages/g4f/Provider/retry_provider.py", line 87, in raise_exceptions
    raise RuntimeError("\n".join(["RetryProvider failed:"] + [
RuntimeError: RetryProvider failed:
Phind: TypeError: Binary Location Must be a String
Liaobots: ClientResponseError: 500, message='Internal Server Error', url=URL('https://liaobots.work/api/chat')
Bing: Exception: CaptchaChallenge: User needs to solve CAPTCHA to continue.

**Comment by xtekky** [comment]
Hi, I will be reviewing the gpt4free infrastructure and providers this weekend, expect a major update.

**Comment by Luneye** [comment]
will try to update the bing code when i'll have more free time
