### ISSUE TITLE
RecursionError: maximum recursion depth exceeded while calling a Python object

### ISSUE THREAD

**Issue by Petyay** [xtekky/gpt4free#1292]
Ubuntu 22, g4f-0.1.9.0, pip installation method, python3.10

**Bug description**
G4F API has these errors after 5-10 requests. I have to restart constantly. It is very uncomfortable. This problem did not exist in the previous version.

**Errors**
```
RecursionError: maximum recursion depth exceeded in comparison
RecursionError: maximum recursion depth exceeded while calling a Python object
RuntimeError: RetryProvider failed:
You: RecursionError: maximum recursion depth exceeded
Chatgpt4Online: RecursionError: maximum recursion depth exceeded in comparison
ChatAnywhere: RecursionError: maximum recursion depth exceeded while encoding a JSON object
ChatgptX: RecursionError: maximum recursion depth exceeded in comparison
GptForLove: RuntimeUnavailableError: Could not find an available JavaScript runtime.
ChatBase: RecursionError: maximum recursion depth exceeded while encoding a JSON object
GptGo: RecursionError: maximum recursion depth exceeded while calling a Python object
```

**Traceback**
```
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/g4f/api/__init__.py", line 85, in chat_completions
    response = g4f.ChatCompletion.create(
  File "/usr/local/lib/python3.10/dist-packages/g4f/__init__.py", line 76, in create
    return result if stream else ''.join(result)
  File "/usr/local/lib/python3.10/dist-packages/g4f/Provider/retry_provider.py", line 59, in create_completion
    self.raise_exceptions()
  File "/usr/local/lib/python3.10/dist-packages/g4f/Provider/retry_provider.py", line 87, in raise_exceptions
    raise RuntimeError("\n".join(["RetryProvider failed:"] + [
RuntimeError: RetryProvider failed:
ChatAnywhere: RecursionError: maximum recursion depth exceeded
ChatBase: RecursionError: maximum recursion depth exceeded
ChatgptX: RecursionError: maximum recursion depth exceeded
You: RecursionError: maximum recursion depth exceeded while calling a Python object
GptGo: RecursionError: maximum recursion depth exceeded
Chatgpt4Online: RecursionError: maximum recursion depth exceeded
GptForLove: RecursionError: maximum recursion depth exceeded

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/uvicorn/protocols/http/h11_impl.py", line 408, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/usr/local/lib/python3.10/dist-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/fastapi/applications.py", line 1106, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.10/dist-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
    raise e
  File "/usr/local/lib/python3.10/dist-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/usr/local/lib/python3.10/dist-packages/fastapi/routing.py", line 274, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.10/dist-packages/fastapi/routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
  File "/usr/local/lib/python3.10/dist-packages/g4f/api/__init__.py", line 91, in chat_completions
    logging.exception(e)
  File "/usr/lib/python3.10/logging/__init__.py", line 2113, in exception
    error(msg, *args, exc_info=exc_info, **kwargs)
  File "/usr/lib/python3.10/logging/__init__.py", line 2105, in error
    root.error(msg, *args, **kwargs)
  File "/usr/lib/python3.10/logging/__init__.py", line 1506, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/usr/lib/python3.10/logging/__init__.py", line 1624, in _log
    self.handle(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 1634, in handle
    self.callHandlers(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 1696, in callHandlers
    hdlr.handle(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 968, in handle
    self.emit(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 686, in format
    record.exc_text = self.formatException(record.exc_info)
  File "/usr/lib/python3.10/logging/__init__.py", line 636, in formatException
    traceback.print_exception(ei[0], ei[1], tb, None, sio)
  File "/usr/lib/python3.10/traceback.py", line 120, in print_exception
    for line in te.format(chain=chain):
  File "/usr/local/lib/python3.10/dist-packages/exceptiongroup/_formatting.py", line 248, in format
    yield from _ctx.emit(exc.format_exception_only())
  File "/usr/local/lib/python3.10/dist-packages/exceptiongroup/_formatting.py", line 64, in emit
    for text in text_gen:
  File "/usr/local/lib/python3.10/dist-packages/exceptiongroup/_formatting.py", line 335, in format_exception_only
    if isinstance(self.__notes__, collections.abc.Sequence):
  File "/usr/lib/python3.10/abc.py", line 119, in __instancecheck__
    return _abc_instancecheck(cls, instance)
RecursionError: maximum recursion depth exceeded in comparison
```

**Comment by Petyay** [comment]
I tried other versions.
In version 1.8.8 there are the same errors.
Version 1.8.0 - returns the error "An error occurred while generating the response".

**Comment by Petyay** [comment]
**Temporary solution**
add the following code to the g4f/api/run.ry file:

```
import sys
sys.setrecursionlimit(10000)
```
