### ISSUE TITLE
Bing error ERROR:root:RetryProvider failed: 

### ISSUE THREAD

**Issue by Turbo1337GS** [xtekky/gpt4free#1305]
```
ERROR:root:RetryProvider failed:
Bing: ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url=URL('https://www.bing.com/turing/conversation/create?bundleVersion=1.1199.4')
Traceback (most recent call last):
  File "/var/www/html/Tools/Stasiu/g4f/api/__init__.py", line 220, in chat_completions
    response = g4f.ChatCompletion.create(
  File "/var/www/html/Tools/Stasiu/g4f/__init__.py", line 76, in create
    return result if stream else ''.join(result)
  File "/var/www/html/Tools/Stasiu/g4f/Provider/retry_provider.py", line 59, in create_completion
    self.raise_exceptions()
  File "/var/www/html/Tools/Stasiu/g4f/Provider/retry_provider.py", line 87, in raise_exceptions
    raise RuntimeError("\n".join(["RetryProvider failed:"] + [
RuntimeError: RetryProvider failed:
Bing: ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url=URL('https://www.bing.com/turing/conversation/create?bundleVersion=1.1199.4')
INFO:     31.60.147.242:0 - "POST /v1/chat/completions HTTP/1.0" 200 OK


```

How i can fix this? I use python -m g4f.api.run, when i wanna use gpt3.5 its great
but when i wanna using the bing, i see the error

**Comment by Aarushb** [comment]
I am also having this issue. This happened to me in two separate locations with two separate IP's. I hope it's not a block. I can use bing just fine on the website though.

**Comment by Turbo1337GS** [comment]
> I am also having this issue. This happened to me in two separate locations with two separate IP's. I hope it's not a block. I can use bing just fine on the website though.

My IP got blocked, and I found out two things.I started using a proxy, and Bing started working.I contacted technical support, and they told me that my IP has been blocked.
