### ISSUE TITLE
I'm getting error to solve Bing Captcha!

### ISSUE THREAD

**Issue by Seruios** [xtekky/gpt4free#1326]
I'm getting error - 

> g4f.Provider.Bing supports: (
    model,
    messages: Messages,
    proxy: str = None,
    cookies: dict = None,
    tone: str = Creative,
    image: str = None
)
Using RetryProvider provider
Using Phind provider
Using Liaobots provider
Liaobots: ClientResponseError: 500, message='Internal Server Error', url=URL('https://liaobots.work/api/chat')
Using Bing provider
Bing: Exception: CaptchaChallenge: User needs to solve CAPTCHA to continue.
Traceback (most recent call last):
  File "/root/Seruios/Gpt_test.py", line 18, in <module>
    response = g4f.ChatCompletion.create(
  File "/usr/local/lib/python3.10/dist-packages/g4f/__init__.py", line 79, in create
    return result if stream else ''.join(result)
  File "/usr/local/lib/python3.10/dist-packages/g4f/Provider/retry_provider.py", line 59, in create_completion
    self.raise_exceptions()
  File "/usr/local/lib/python3.10/dist-packages/g4f/Provider/retry_provider.py", line 87, in raise_exceptions
    raise RuntimeError("\n".join(["RetryProvider failed:"] + [
RuntimeError: RetryProvider failed:
Liaobots: ClientResponseError: 500, message='Internal Server Error', url=URL('https://liaobots.work/api/chat')
Bing: Exception: CaptchaChallenge: User needs to solve CAPTCHA to continue.

**Comment by hlohaus** [comment]
You can try add cookies to the Bing provider

**Comment by hussainwali74** [comment]
make it active, this is an active issue
