### ISSUE TITLE
bard and some others dont work

### ISSUE THREAD

**Issue by tinker1234** [xtekky/gpt4free#1330]
when updating through pip or github i cant use bard or some of the others because i get
Traceback (most recent call last):
  File "c:\shared\python\jarvis4\main.py", line 25, in <module>
    app.run()
  File "c:\shared\python\jarvis4\main.py", line 15, in run  
    label = self.command_processor.handle_command(command)  
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^  
  File "c:\shared\python\jarvis4\command_processing.py", line 7, in handle_command
    return self.agent.get_command_label(command)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\shared\python\jarvis4\openai_agent.py", line 31, in get_command_label
    response = self.create_messages(messages)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\shared\python\jarvis4\openai_agent.py", line 13, in create_messages
    response = g4f.ChatCompletion.create(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\shared\python\jarvis4\venv\Lib\site-packages\g4f\__init__.py", line 91, in create
    model, provider = get_model_and_provider(model, provider, stream, ignored, ignore_working, ignore_stream_and_auth)  
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^  
  File "C:\shared\python\jarvis4\venv\Lib\site-packages\g4f\__init__.py", line 60, in get_model_and_provider
    provider = model.best_provider
               ^^^^^^^^^^^^^^^^^^^
AttributeError: type object 'Bard' has no attribute 'best_provider'

**Comment by hlohaus** [comment]
try:
  model=g4f.models.default,
  provider=g4f.Provider.Bard,

**Comment by tinker1234** [comment]
how do i send cookie

**Comment by hlohaus** [comment]
The new Bard use a browser. It needs JavaScript. If you run the provider, a new browser window should be open. There you can log in.
