### ISSUE TITLE
Docker compose error: FileNotFoundError: [Errno 2] No such file or directory: 'git'

### ISSUE THREAD

**Issue by seth100** [xtekky/gpt4free#1332]
**Bug description**

Running docker-compose.yml file and it fails:

```sh
[2023-12-10 21:35:13,404] ERROR in app: Exception on /backend-api/v2/version [GET]
gpt4free  | Traceback (most recent call last):
gpt4free  |   File "/home/seluser/.local/lib/python3.10/site-packages/flask/app.py", line 1455, in wsgi_app
gpt4free  |     response = self.full_dispatch_request()
gpt4free  |   File "/home/seluser/.local/lib/python3.10/site-packages/flask/app.py", line 869, in full_dispatch_request
gpt4free  |     rv = self.handle_user_exception(e)
gpt4free  |   File "/home/seluser/.local/lib/python3.10/site-packages/flask/app.py", line 867, in full_dispatch_request
gpt4free  |     rv = self.dispatch_request()
gpt4free  |   File "/home/seluser/.local/lib/python3.10/site-packages/flask/app.py", line 852, in dispatch_request
gpt4free  |     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
gpt4free  |   File "/app/g4f/gui/server/backend.py", line 54, in version
gpt4free  |     "version": g4f.get_version(),
gpt4free  |   File "/app/g4f/__init__.py", line 26, in get_version
gpt4free  |     return check_output(command, text=True, stderr=PIPE).strip()
gpt4free  |   File "/usr/lib/python3.10/subprocess.py", line 421, in check_output
gpt4free  |     return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
gpt4free  |   File "/usr/lib/python3.10/subprocess.py", line 503, in run
gpt4free  |     with Popen(*popenargs, **kwargs) as process:
gpt4free  |   File "/usr/lib/python3.10/subprocess.py", line 971, in __init__
gpt4free  |     self._execute_child(args, executable, preexec_fn, close_fds,
gpt4free  |   File "/usr/lib/python3.10/subprocess.py", line 1863, in _execute_child
gpt4free  |     raise child_exception_type(errno_num, err_msg, err_filename)
gpt4free  | FileNotFoundError: [Errno 2] No such file or directory: 'git'
gpt4free  | 172.26.0.1 - - [10/Dec/2023 21:35:13] "GET /backend-api/v2/version HTTP/1.1" 500 -
gpt4free  | 172.26.0.1 - - [10/Dec/2023 21:35:13] "GET /assets/img/apple-touch-icon.png HTTP/1.1" 200 -
gpt4free  | 172.26.0.1 - - [10/Dec/2023 21:35:13] "GET /assets/img/favicon-16x16.png HTTP/1.1" 200 -
gpt4free  | 172.26.0.1 - - [10/Dec/2023 21:35:14] "GET /assets/img/gpt.png HTTP/1.1" 200 -
gpt4free  | 172.26.0.1 - - [10/Dec/2023 21:35:31] "GET /assets/img/user.png HTTP/1.1" 200 -
gpt4free  | Failed to check g4f pypi version: [Errno 2] No such file or directory: 'git'
```

**Environment**

- Docker v24.0.7
- Docker Compose v2.21.0
- Ubuntu 22.04

**Comment by hlohaus** [comment]
Disable the version check or
set the version in your docker-compose.yml:
```
    environment:
      - G4F_VERSION=0.1.9.2
``

**Comment by seth100** [comment]
Thanks it works, how to disable the version check?

**Comment by seth100** [comment]
and how can I always set the latest version using that variable?
