### ISSUE TITLE
ModuleNotFoundError No module named 'distutils' with Python312

### ISSUE THREAD

**Issue by iG8R** [xtekky/gpt4free#1339]
**Bug description**
After installing g4f, when trying to run it, for example via `g4f gui`, the following error occurs:
```
C:\Users\iG8R>g4f gui
Traceback (most recent call last):
  File "<frozen runpy>", line 189, in _run_module_as_main
  File "<frozen runpy>", line 112, in _get_module_details
  File "C:\Python312\Lib\site-packages\g4f\__init__.py", line 8, in <module>
    from .models   import Model, ModelUtils, _all_models
  File "C:\Python312\Lib\site-packages\g4f\models.py", line 4, in <module>
    from .Provider   import BaseProvider, RetryProvider
  File "C:\Python312\Lib\site-packages\g4f\Provider\__init__.py", line 5, in <module>
    from .deprecated     import *
  File "C:\Python312\Lib\site-packages\g4f\Provider\deprecated\__init__.py", line 18, in <module>
    from .Aibn          import Aibn
  File "C:\Python312\Lib\site-packages\g4f\Provider\deprecated\Aibn.py", line 7, in <module>
    from ...requests import StreamSession
  File "C:\Python312\Lib\site-packages\g4f\requests.py", line 9, in <module>
    from .webdriver import WebDriver, WebDriverSession, bypass_cloudflare
  File "C:\Python312\Lib\site-packages\g4f\webdriver.py", line 5, in <module>
    from undetected_chromedriver import Chrome, ChromeOptions
  File "C:\Python312\Lib\site-packages\undetected_chromedriver\__init__.py", line 44, in <module>
    from .patcher import IS_POSIX
  File "C:\Python312\Lib\site-packages\undetected_chromedriver\patcher.py", line 4, in <module>
    from distutils.version import LooseVersion
ModuleNotFoundError: No module named 'distutils'
```

**Environment**
- python version: 3.12
- location ( are you in a cloudfare flagged country ): I don't quit understand how to determine it, I'm from Ukraine.

**Additional context**
Since newly released Python 3.12 removed `distutils`, this error could be solved, for example, by installing `setuptools` which provides `distutils` (`pip install -U setuptools`), but it would be more convenient to solve this issue in g4f itself.

**Comment by hlohaus** [comment]
The issue must be fixed in undetected_chromedriver package.

**Comment by Frehyyy** [comment]
Have you solved it?
