### ISSUE TITLE
FakeGpt is not working (IndexError: Cannot choose from an empty sequence)

### ISSUE THREAD

**Issue by thanhtoan1196** [xtekky/gpt4free#1363]
**Bug description**
FakeGpt is not working (IndexError: Cannot choose from an empty sequence)

Logs:
```
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.11/site-packages/flask/app.py", line 1478, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/flask/app.py", line 1458, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/flask/app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/flask/app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/flask/app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/flask/app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/teq-toantran/Desktop/python/main-python/app.py", line 14, in request_code
    result = g4f.ChatCompletion.create(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/g4f/__init__.py", line 101, in create
    return result if stream else ''.join(result)
                                 ^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/g4f/Provider/base_provider.py", line 142, in create_completion
    yield loop.run_until_complete(gen.__anext__())
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/g4f/Provider/FakeGpt.py", line 41, in create_async_generator
    "token_key": random.choice(token_ids),
                 ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/random.py", line 373, in choice
    raise IndexError('Cannot choose from an empty sequence')
IndexError: Cannot choose from an empty sequence
````

**Environment**
- python version: 3.11.6
- g4f version: 0.1.9.3

**Comment by devAdityaa** [comment]
This is an issue with youe system. The main issue is that the API endpoint isn't sending token_ids as a response. This could be happening because the server is blocked in your region.

Go to this URL, https://chat-shared2.zhile.io/api/loads. This URL is responsible for sending the token_ids. If you see an error or don't see a list of token_ids (as shown in the picture), then unfortunately, you can't do much except use a VPN.

However, if you see a list of token_ids, I recommend uninstalling and reinstalling the g4f package and trying again. If the issue still persists, you can try copying and pasting the token_id manually. Just be aware that this token might expire after a week or so, and you'll have to repeat the copy-and-paste process.
![Screenshot from 2023-12-18 18-57-43](https://github.com/xtekky/gpt4free/assets/77636021/6f21d093-e0f3-46c2-99e6-e1354247222c)

**Comment by Vanfreddy** [comment]
i get the same error since yesterday 
Using FakeGpt provider
FakeGpt: IndexError: Cannot choose from an empty sequence

[0.1.9.4](https://github.com/xtekky/gpt4free/commit/b615a95a417d8a857b1f822bd2d2f993737d532a)

**Comment by devAdityaa** [comment]
Okay so this issue is happening to me now. So its not an issue with the server being blocked, which means it's a bug in the code. I'll look at the code and fix it and let you know.
