### ISSUE TITLE
New possible models to add (Gemini pro and gpt 3.5

### ISSUE THREAD

**Issue by OmiiiDev** [xtekky/gpt4free#1375]
Gemini pro site: https://geminiprochat.com

Gpt3.5 chat: https://chat.3211000.xyz/

I tested both on dec 21 and they both worked but I'm not certain about the models...

**Comment by devAdityaa** [comment]
> Gemini pro site: https://geminiprochat.com
> 
> Gpt3.5 chat: https://chat.3211000.xyz/
> 
> 
> I tested both on dec 21 and they both worked but I'm not certain about the models...

Ok I'll check them and let you know.

**Comment by sharoz-27** [comment]
I need it too! Gemini pro site: https://geminiprochat.com has a long answer, which is very good!

**Comment by hlohaus** [comment]
I added GeminiPro provider in #1412.

**Comment by iG8R** [comment]
@hlohaus 
There is an issue with the GeminiPro provider:
```
127.0.0.1 - - [04/Jan/2024 14:50:48] "POST /backend-api/v2/conversation HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [04/Jan/2024 14:50:48] "POST /backend-api/v2/conversation HTTP/1.1" 200 -
ERROR:root:'utf-8' codec can't decode byte 0xc3 in position 184: unexpected end of data
Traceback (most recent call last):
  File "c:\gpt4free\venv\Lib\site-packages\g4f-0.1.9.8-py3.12.egg\g4f\gui\server\backend.py", line 79, in try_response
    for chunk in g4f.ChatCompletion.create(
  File "c:\gpt4free\venv\Lib\site-packages\g4f-0.1.9.8-py3.12.egg\g4f\Provider\base_provider.py", line 142, in create_completion
    yield loop.run_until_complete(gen.__anext__())
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\asyncio\base_events.py", line 664, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "c:\gpt4free\venv\Lib\site-packages\g4f-0.1.9.8-py3.12.egg\g4f\Provider\GeminiProChat.py", line 52, in create_async_generator
    yield chunk.decode()
          ^^^^^^^^^^^^^^
```
