### ISSUE TITLE
Issue for chat completion for g4f api

### ISSUE THREAD

**Issue by OmiiiDev** [xtekky/gpt4free#1378]
**Bug description**
After sending a post request (message) to the completions url i get this error message:
INFO:     172.31.196.1:52004 - "POST /v1/chat/completions HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/runner/gpt4free/.pythonlibs/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 408, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/home/runner/gpt4free/.pythonlibs/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "/home/runner/gpt4free/.pythonlibs/lib/python3.10/site-packages/fastapi/applications.py", line 1106, in __call__
    await super().__call__(scope, receive, send)
  File "/home/runner/gpt4free/.pythonlibs/lib/python3.10/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/runner/gpt4free/.pythonlibs/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/home/runner/gpt4free/.pythonlibs/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/home/runner/gpt4free/.pythonlibs/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/home/runner/gpt4free/.pythonlibs/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/home/runner/gpt4free/.pythonlibs/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
    raise e
  File "/home/runner/gpt4free/.pythonlibs/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/home/runner/gpt4free/.pythonlibs/lib/python3.10/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/home/runner/gpt4free/.pythonlibs/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/home/runner/gpt4free/.pythonlibs/lib/python3.10/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/home/runner/gpt4free/.pythonlibs/lib/python3.10/site-packages/fastapi/routing.py", line 274, in app
    raw_response = await run_endpoint_function(
  File "/home/runner/gpt4free/.pythonlibs/lib/python3.10/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
  File "/home/runner/gpt4free/.pythonlibs/lib/python3.10/site-packages/g4f/api/__init__.py", line 87, in chat_completions
    provider = item_data.get('provider').replace('g4f.Provider.', '')
AttributeError: 'NoneType' object has no attribute 'replace'
INFO:     172.31.196.1:32986 - "POST /v1/chat/completions HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/runner/gpt4free/.pythonlibs/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 408, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/home/runner/gpt4free/.pythonlibs/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "/home/runner/gpt4free/.pythonlibs/lib/python3.10/site-packages/fastapi/applications.py", line 1106, in __call__
    await super().__call__(scope, receive, send)
  File "/home/runner/gpt4free/.pythonlibs/lib/python3.10/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/runner/gpt4free/.pythonlibs/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/home/runner/gpt4free/.pythonlibs/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/home/runner/gpt4free/.pythonlibs/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/home/runner/gpt4free/.pythonlibs/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/home/runner/gpt4free/.pythonlibs/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
    raise e
  File "/home/runner/gpt4free/.pythonlibs/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/home/runner/gpt4free/.pythonlibs/lib/python3.10/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/home/runner/gpt4free/.pythonlibs/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/home/runner/gpt4free/.pythonlibs/lib/python3.10/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/home/runner/gpt4free/.pythonlibs/lib/python3.10/site-packages/fastapi/routing.py", line 274, in app
    raw_response = await run_endpoint_function(
  File "/home/runner/gpt4free/.pythonlibs/lib/python3.10/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
  File "/home/runner/gpt4free/.pythonlibs/lib/python3.10/site-packages/g4f/api/__init__.py", line 87, in chat_completions
    provider = item_data.get('provider').replace('g4f.Provider.', '')
AttributeError: 'NoneType' object has no attribute 'replace'

ex.
1. run the g4f api script on replit
2. send a post request to the completions link
3. See error

**Environment**
- g4f version 0.1.9.5

**Comment by hlohaus** [comment]
AttributeError: 'NoneType' object has no attribute 'replace'
has been fixed
