### ISSUE TITLE
AttributeError: module 'g4f' has no attribute 'version'

### ISSUE THREAD

**Issue by the-thirteenth-fox** [xtekky/gpt4free#1380]
**Bug description**

after installing version from GitHub and try to start by this command: python3 gpt4free/g4f/api/run.py
I got this error Traceback (most recent call last):
  File "/root/gpt4free/g4f/api/run.py", line 5, in <module>
    print(f'Starting server... [g4f v-{g4f.version}]')
AttributeError: module 'g4f' has no attribute 'versio

**Environment**
- Python 3.10.12

**Additional context**
After deleting this 
<img width="209" alt="Снимок экрана 2023-12-23 в 17 25 23" src="https://github.com/xtekky/gpt4free/assets/44783405/a74cec29-54b9-402f-ae8b-f17a22b90ac7">
the error goes away. 

But when I send a request I got another error:
INFO:     127.0.0.1:33232 - "POST /v1/chat/completions HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/uvicorn/protocols/http/h11_impl.py", line 408, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/usr/local/lib/python3.10/dist-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/fastapi/applications.py", line 1106, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.10/dist-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
    raise e
  File "/usr/local/lib/python3.10/dist-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/usr/local/lib/python3.10/dist-packages/fastapi/routing.py", line 274, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.10/dist-packages/fastapi/routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
  File "/usr/local/lib/python3.10/dist-packages/g4f/api/__init__.py", line 87, in chat_completions
    provider = item_data.get('provider').replace('g4f.Provider.', '')
AttributeError: 'NoneType' object has no attribute 'replace'

**Comment by hlohaus** [comment]
I fixed the Error:
 AttributeError: 'NoneType' object has no attribute 'replace'
and g4f.version is g4g.debug.get_version() now.

Thank you for your feedback.
