### ISSUE TITLE
NotImplementedError

### ISSUE THREAD

**Issue by astrales69** [xtekky/gpt4free#1392]
Hi all, I have created my discord bot with neural network function using g4f library, when I write a command it is processed correctly but along with that it is accompanied by popups and errors in the console, how can I fix this?

Environment: Windows 11, Python 3.11.4

Function code:
```
async def gptanswer(prompt: str) -> str:
    response = await g4f.ChatCompletion.create_async(
        model=g4f.models.gpt_35_turbo_16k_0613,
        messages=[{"role": "user", "content": prompt}],
    )
    return response
```

```
Exception ignored from cffi callback <function socket_function at 0x000001D9B4E97130>:
Traceback (most recent call last):
  File "C:\Users\MACHINE\Desktop\discord bot\hefner py\.venv\lib\site-packages\curl_cffi\aio.py", line 63, in socket_function
    loop.add_reader(sockfd, async_curl.process_data, sockfd, CURL_CSELECT_IN)
  File "C:\Users\MACHINE\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 518, in add_reader
    raise NotImplementedError
NotImplementedError:
Exception ignored from cffi callback <function socket_function at 0x000001D9B4E97130>:
Traceback (most recent call last):
  File "C:\Users\MACHINE\Desktop\discord bot\hefner py\.venv\lib\site-packages\curl_cffi\aio.py", line 69, in socket_function
    async_curl._sockfds.remove(sockfd)
KeyError: 1192
Exception ignored from cffi callback <function socket_function at 0x000001D9B4E97130>:
Traceback (most recent call last):
  File "C:\Users\MACHINE\Desktop\discord bot\hefner py\.venv\lib\site-packages\curl_cffi\aio.py", line 66, in socket_function
    loop.add_writer(sockfd, async_curl.process_data, sockfd, CURL_CSELECT_OUT)
  File "C:\Users\MACHINE\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 524, in add_writer
    raise NotImplementedError
NotImplementedError:
Exception ignored from cffi callback <function socket_function at 0x000001D9B4E97130>:
Traceback (most recent call last):
  File "C:\Users\MACHINE\Desktop\discord bot\hefner py\.venv\lib\site-packages\curl_cffi\aio.py", line 63, in socket_function
    loop.add_reader(sockfd, async_curl.process_data, sockfd, CURL_CSELECT_IN)
  File "C:\Users\MACHINE\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 518, in add_reader
    raise NotImplementedError
NotImplementedError:
Exception ignored from cffi callback <function socket_function at 0x000001D9B4E97130>:
Traceback (most recent call last):
  File "C:\Users\MACHINE\Desktop\discord bot\hefner py\.venv\lib\site-packages\curl_cffi\aio.py", line 69, in socket_function
    async_curl._sockfds.remove(sockfd)
KeyError: 1192
Exception ignored from cffi callback <function socket_function at 0x000001D9B4E97130>:
Traceback (most recent call last):
  File "C:\Users\MACHINE\Desktop\discord bot\hefner py\.venv\lib\site-packages\curl_cffi\aio.py", line 63, in socket_function
    loop.add_reader(sockfd, async_curl.process_data, sockfd, CURL_CSELECT_IN)
  File "C:\Users\MACHINE\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 518, in add_reader
    raise NotImplementedError
NotImplementedError:
Exception ignored from cffi callback <function socket_function at 0x000001D9B4E97130>:
Traceback (most recent call last):
  File "C:\Users\MACHINE\Desktop\discord bot\hefner py\.venv\lib\site-packages\curl_cffi\aio.py", line 69, in socket_function
    async_curl._sockfds.remove(sockfd)
KeyError: 2600
Exception ignored from cffi callback <function socket_function at 0x000001D9B4E97130>:
Traceback (most recent call last):
  File "C:\Users\MACHINE\Desktop\discord bot\hefner py\.venv\lib\site-packages\curl_cffi\aio.py", line 66, in socket_function
    loop.add_writer(sockfd, async_curl.process_data, sockfd, CURL_CSELECT_OUT)
  File "C:\Users\MACHINE\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 524, in add_writer
    raise NotImplementedError
NotImplementedError:
Exception ignored from cffi callback <function socket_function at 0x000001D9B4E97130>:
Traceback (most recent call last):
  File "C:\Users\MACHINE\Desktop\discord bot\hefner py\.venv\lib\site-packages\curl_cffi\aio.py", line 63, in socket_function
    loop.add_reader(sockfd, async_curl.process_data, sockfd, CURL_CSELECT_IN)
  File "C:\Users\MACHINE\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 518, in add_reader
    raise NotImplementedError
NotImplementedError:
Exception ignored from cffi callback <function socket_function at 0x000001D9B4E97130>:
Traceback (most recent call last):
  File "C:\Users\MACHINE\Desktop\discord bot\hefner py\.venv\lib\site-packages\curl_cffi\aio.py", line 69, in socket_function
    async_curl._sockfds.remove(sockfd)
KeyError: 2600
```
![image](https://github.com/xtekky/gpt4free/assets/152309073/64b08b02-13cf-41d0-ac0a-01ffc6bb9b1d)

**Comment by astrales69** [comment]
i found solution #898

**Comment by yifeikong** [comment]
Here: yifeikong/curl_cffi#70

**Comment by astrales69** [comment]
> Here: [yifeikong/curl_cffi#70](https://github.com/yifeikong/curl_cffi/issues/70)

it doesn't works
![image](https://github.com/xtekky/gpt4free/assets/152309073/bfb0500c-61b6-40f3-bbbc-a6258d852b62)

**Comment by hlohaus** [comment]
Try add this to your code:
```
if sys.platform == 'win32':
    if isinstance(
        asyncio.get_event_loop_policy(), asyncio.WindowsProactorEventLoopPolicy
    ):
        asyncio.set_event_loop_policy(asyncio.WindowsSelectorEventLoopPolicy())
```

**Comment by T-256** [comment]
> it doesn't works

Update curl-cffi to 0.6.0b7, I believe it'd be solved.

**Comment by sukacute** [comment]
i think python version
