### ISSUE TITLE
UnboundLocalError: cannot access local variable 'latest_version' where it is not associated with a value

### ISSUE THREAD

**Issue by agn-7** [xtekky/gpt4free#1394]
Error:

```
Failed to check g4f pypi version: SOCKSHTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /pypi/g4f/json (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7fa980acd210>: Failed to establish a new connection: [Errno 111] Connection refused'))
Traceback (most recent call last):
  File "/home/benyamin/PycharmProjects/ifsguid-backend/ifsguid/modules.py", line 15, in generate_ai_response
    response = await g4f.ChatCompletion.create_async(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/benyamin/.cache/pypoetry/virtualenvs/ifsguid-VUbnfeiD-py3.11/lib/python3.11/site-packages/g4f/__init__.py", line 110, in create_async
    model, provider = get_model_and_provider(model, provider, False, ignored)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/benyamin/.cache/pypoetry/virtualenvs/ifsguid-VUbnfeiD-py3.11/lib/python3.11/site-packages/g4f/__init__.py", line 50, in get_model_and_provider
    check_pypi_version()
  File "/home/benyamin/.cache/pypoetry/virtualenvs/ifsguid-VUbnfeiD-py3.11/lib/python3.11/site-packages/g4f/__init__.py", line 40, in check_pypi_version
    if version != latest_version:
                  ^^^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'latest_version' where it is not associated with a value
```

I am using the version `g4f = "0.1.9.3"`

**Comment by agn-7** [comment]
The origin of the previous error was related to my internet connection due to the proxy setting, so that I fix that by the following command:

```bash
export all_proxy=""
```

But, now I encountered a new issue:

```
Traceback (most recent call last):
  File "/home/benyamin/PycharmProjects/ifsguid-backend/ifsguid/modules.py", line 15, in generate_ai_response
    response = await g4f.ChatCompletion.create_async(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/benyamin/.cache/pypoetry/virtualenvs/ifsguid-VUbnfeiD-py3.11/lib/python3.11/site-packages/g4f/__init__.py", line 110, in create_async
    model, provider = get_model_and_provider(model, provider, False, ignored)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/benyamin/.cache/pypoetry/virtualenvs/ifsguid-VUbnfeiD-py3.11/lib/python3.11/site-packages/g4f/__init__.py", line 60, in get_model_and_provider
    provider = model.best_provider
               ^^^^^^^^^^^^^^^^^^^
AttributeError: 'tuple' object has no attribute 'best_provider'
```

**Comment by hlohaus** [comment]
How do you call the create function. Maybe the wrong model?

**Comment by agn-7** [comment]
Here's the calling create function part:

```python
async def generate_ai_response(content: str, interaction: Interaction) -> str:
    try:
        response = await g4f.ChatCompletion.create_async(
            model=g4f.ModelUtils.convert["gpt-3.5-turbo"],
            messages=[
                {"role": "system", "content": "This GPT is an agent that answers and assists with the questions only in the field of software programming and software engineering. So you are not allowed to answer the questions in other topics than software engineering."},
                {"role": "user", "content": "Can you explain to me the functionality of integral in mathematics?"},
            ],
        )
        return response
    except Exception:
        traceback.print_exc()
        return "error!"
```

**Comment by hlohaus** [comment]
I can't reproduce that. Maybe update the g4f package.
