### ISSUE TITLE
captha? bing?

### ISSUE THREAD

**Issue by Turbo1337GS** [xtekky/gpt4free#1395]
```bash
5|Stasiu API (proxy)  | ERROR:root:CaptchaChallenge: User needs to solve CAPTCHA to continue.
5|Stasiu API (proxy)  | Traceback (most recent call last):
5|Stasiu API (proxy)  |   File "/var/www/html/api/Stasiu/g4f/api/__init__.py", line 134, in streaming
5|Stasiu API (proxy)  |     for chunk in response:
5|Stasiu API (proxy)  |   File "/var/www/html/api/Stasiu/g4f/Provider/base_provider.py", line 142, in create_completion
5|Stasiu API (proxy)  |     yield loop.run_until_complete(gen.__anext__())
5|Stasiu API (proxy)  |   File "/venv/lib/python3.10/site-packages/nest_asyncio.py", line 99, in run_until_complete
5|Stasiu API (proxy)  |     return f.result()
5|Stasiu API (proxy)  |   File "/usr/lib/python3.10/asyncio/futures.py", line 201, in result
5|Stasiu API (proxy)  |     raise self._exception.with_traceback(self._exception_tb)
5|Stasiu API (proxy)  |   File "/usr/lib/python3.10/asyncio/tasks.py", line 232, in __step
5|Stasiu API (proxy)  |     result = coro.send(None)
5|Stasiu API (proxy)  |   File "/var/www/html/api/Stasiu/g4f/Provider/Bing.py", line 503, in stream_generate
5|Stasiu API (proxy)  |     raise Exception(f"{result['value']}: {result['message']}")
5|Stasiu API (proxy)  | Exception: CaptchaChallenge: User needs to solve CAPTCHA to continue.

```

**Comment by zeke789** [comment]
try using good proxy and changing user agent

**Comment by Turbo1337GS** [comment]
> try using good proxy and changing user agent

Ye! I must using proxychains ;( 
But now response is slowe, beacuse proxychains using tor
