### ISSUE TITLE
No module named 'Crypto' - but I have it

### ISSUE THREAD

**Issue by ilpoppattuso** [xtekky/gpt4free#1402]
When I try to `import g4f`, I obtain this error:

```
Traceback (most recent call last):
  File "<pyshell#1>", line 1, in <module>
    import g4f
  File "C:\Users\matte\AppData\Local\Programs\Python\Python310\lib\site-packages\g4f\__init__.py", line 6, in <module>
    from .models   import Model, ModelUtils, _all_models
  File "C:\Users\matte\AppData\Local\Programs\Python\Python310\lib\site-packages\g4f\models.py", line 4, in <module>
    from .Provider   import BaseProvider, RetryProvider
  File "C:\Users\matte\AppData\Local\Programs\Python\Python310\lib\site-packages\g4f\Provider\__init__.py", line 6, in <module>
    from .needs_auth     import *
  File "C:\Users\matte\AppData\Local\Programs\Python\Python310\lib\site-packages\g4f\Provider\needs_auth\__init__.py", line 6, in <module>
    from .OpenaiChat    import OpenaiChat
  File "C:\Users\matte\AppData\Local\Programs\Python\Python310\lib\site-packages\g4f\Provider\needs_auth\OpenaiChat.py", line 4, in <module>
    from py_arkose_generator.arkose import get_values_for_request
  File "C:\Users\matte\AppData\Local\Programs\Python\Python310\lib\site-packages\py_arkose_generator\arkose.py", line 3, in <module>
    from . import util
  File "C:\Users\matte\AppData\Local\Programs\Python\Python310\lib\site-packages\py_arkose_generator\util.py", line 7, in <module>
    from .crypt import encrypt
  File "C:\Users\matte\AppData\Local\Programs\Python\Python310\lib\site-packages\py_arkose_generator\crypt.py", line 6, in <module>
    from Crypto.Cipher import AES
ModuleNotFoundError: No module named 'Crypto'

```

I have installed the Crypto and pycryptodome:
```
pip install Crypto pycryptodome
Requirement already satisfied: Crypto in c:\users\matte\appdata\local\programs\python\python310\lib\site-packages (1.4.1)
Requirement already satisfied: pycryptodome in c:\users\matte\appdata\local\programs\python\python310\lib\site-packages (3.14.1)
Requirement already satisfied: Naked in c:\users\matte\appdata\local\programs\python\python310\lib\site-packages (from Crypto) (0.1.31)
Requirement already satisfied: shellescape in c:\users\matte\appdata\local\programs\python\python310\lib\site-packages (from Crypto) (3.8.1)
Requirement already satisfied: requests in c:\users\matte\appdata\local\programs\python\python310\lib\site-packages (from Naked->Crypto) (2.31.0)
Requirement already satisfied: pyyaml in c:\users\matte\appdata\local\programs\python\python310\lib\site-packages (from Naked->Crypto) (6.0)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\matte\appdata\local\programs\python\python310\lib\site-packages (from requests->Naked->Crypto) (2.1.1)
Requirement already satisfied: idna<4,>=2.5 in c:\users\matte\appdata\local\programs\python\python310\lib\site-packages (from requests->Naked->Crypto) (3.6)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\matte\appdata\local\programs\python\python310\lib\site-packages (from requests->Naked->Crypto) (2.1.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\matte\appdata\local\programs\python\python310\lib\site-packages (from requests->Naked->Crypto) (2023.11.17)

```

**Comment by devAdityaa** [comment]
Pretty sure you installed the wrong package. It's called _pycrypto_ not _Crypto_.
Try installing with
_pip install pycrypto_
