### ISSUE TITLE
Chatgpt4Online is not working (RuntimeError: No nonce found)

### ISSUE THREAD

**Issue by thanhtoan1196** [xtekky/gpt4free#1403]
**Bug description**
Chatgpt4Online is not working (RuntimeError: No nonce found)

Logs:
```
Traceback (most recent call last):
    result = g4f.ChatCompletion.create(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/g4f/__init__.py", line 79, in create
    return result if stream else ''.join(result)
                                 ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/g4f/Provider/base_provider.py", line 109, in create_completion
    yield loop.run_until_complete(coro)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/g4f/Provider/Chatgpt4Online.py", line 35, in create_async
    raise RuntimeError("No nonce found")
RuntimeError: No nonce found
````

**Environment**
- python version: 3.11.6
- g4f version: 0.1.9.7

**Comment by hlohaus** [comment]
https://github.com/xtekky/gpt4free/pull/1413
