### ISSUE TITLE
ChatgptNext is not working (aiohttp.client_exceptions.ClientResponseError: 400, message='Bad Request')

### ISSUE THREAD

**Issue by thanhtoan1196** [xtekky/gpt4free#1404]
**Bug description**
ChatgptNext is not working:
```
aiohttp.client_exceptions.ClientResponseError: 400, message='Bad Request', url=URL('https://chat.fstha.com/api/openai/v1/chat/completions')
```

Logs:
```
Traceback (most recent call last):
    result = g4f.ChatCompletion.create(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/g4f/__init__.py", line 79, in create
    return result if stream else ''.join(result)
                                 ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/g4f/Provider/base_provider.py", line 142, in create_completion
    yield loop.run_until_complete(gen.__anext__())
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/g4f/Provider/ChatgptNext.py", line 54, in create_async_generator
    response.raise_for_status()
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client_reqrep.py", line 1005, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 400, message='Bad Request', url=URL('https://chat.fstha.com/api/openai/v1/chat/completions')
````

**Environment**
- python version: 3.11.6
- g4f version: 0.1.9.7

**Comment by devAdityaa** [comment]
Is this resolved?

**Comment by hlohaus** [comment]
I can't reproduce it.
