### ISSUE TITLE
G4f api get AttributeError: module 'eventlet.green.select' has no attribute 'epoll'

### ISSUE THREAD

**Issue by artiomborovinskii** [xtekky/gpt4free#1455]
When i try comand g4f api im have
```
┌──(root㉿localhost)-[~]
└─# g4f api                                                                 Traceback (most recent call last):
  File "/usr/local/bin/g4f", line 5, in <module>                                from g4f.cli import main
  File "/usr/local/lib/python3.11/dist-packages/g4f/__init__.py", line 6, in <module>
    from .models   import Model, ModelUtils, _all_models                      File "/usr/local/lib/python3.11/dist-packages/g4f/models.py", line 3, in <module>                                                                         from .Provider   import RetryProvider, ProviderType                       File "/usr/local/lib/python3.11/dist-packages/g4f/Provider/__init__.py", line 7, in <module>
    from .deprecated      import *                                            File "/usr/local/lib/python3.11/dist-packages/g4f/Provider/deprecated/__init__.py", line 18, in <module>
    from .Aibn          import Aibn                                           File "/usr/local/lib/python3.11/dist-packages/g4f/Provider/deprecated/Aibn.py", line 7, in <module>
    from ...requests import StreamSession
  File "/usr/local/lib/python3.11/dist-packages/g4f/requests.py", line 8, in <module>
    from curl_cffi.requests import AsyncSession, Session, Response            File "/usr/local/lib/python3.11/dist-packages/curl_cffi/requests/__init__.py", line 29, in <module>                                                       from .session import AsyncSession, BrowserType, Session
  File "/usr/local/lib/python3.11/dist-packages/curl_cffi/requests/session.py", line 30, in <module>
    import eventlet.tpool                                                     File "/usr/local/lib/python3.11/dist-packages/eventlet/__init__.py", line 11, in <module>                                                                 from eventlet import convenience
  File "/usr/local/lib/python3.11/dist-packages/eventlet/convenience.py", line 7, in <module>
    from eventlet.green import socket                                         File "/usr/local/lib/python3.11/dist-packages/eventlet/green/socket.py", line 21, in <module>                                                             from eventlet.support import greendns
  File "/usr/local/lib/python3.11/dist-packages/eventlet/support/greendns.py", line 79, in <module>
    setattr(dns, pkg, import_patched('dns.' + pkg))                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^                            File "/usr/local/lib/python3.11/dist-packages/eventlet/support/greendns.py", line 61, in import_patched                                                   return patcher.import_patched(module_name, **modules)                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/eventlet/patcher.py", line 132, in import_patched                                                           return inject(                                                                     ^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/eventlet/patcher.py", line 109, in inject
    module = __import__(module_name, {}, {}, module_name.split('.')[:-1])                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^     File "/usr/local/lib/python3.11/dist-packages/dns/asyncquery.py", line 40, in <module>                                                                    from dns.query import (                                                   File "/usr/local/lib/python3.11/dist-packages/dns/query.py", line 58, in <module>                                                                         import httpx                                                              File "/usr/local/lib/python3.11/dist-packages/httpx/__init__.py", line 2, in <module>
    from ._api import delete, get, head, options, patch, post, put, request, stream
  File "/usr/local/lib/python3.11/dist-packages/httpx/_api.py", line 4, in <module>                                                                         from ._client import Client                                               File "/usr/local/lib/python3.11/dist-packages/httpx/_client.py", line 30, in <module>                                                                     from ._transports.default import AsyncHTTPTransport, HTTPTransport
  File "/usr/local/lib/python3.11/dist-packages/httpx/_transports/default.py", line 30, in <module>
    import httpcore                                                           File "/usr/local/lib/python3.11/dist-packages/httpcore/__init__.py", line 1, in <module>                                                                  from ._api import request, stream                                         File "/usr/local/lib/python3.11/dist-packages/httpcore/_api.py", line 5, in <module>
    from ._sync.connection_pool import ConnectionPool                         File "/usr/local/lib/python3.11/dist-packages/httpcore/_sync/__init__.py", line 1, in <module>                                                            from .connection import HTTPConnection
  File "/usr/local/lib/python3.11/dist-packages/httpcore/_sync/connection.py", line 12, in <module>
    from .._synchronization import Lock
  File "/usr/local/lib/python3.11/dist-packages/httpcore/_synchronization.py", line 11, in <module>
    import trio                                                               File "/usr/local/lib/python3.11/dist-packages/trio/__init__.py", line 20, in <module>                                                                     from ._core import TASK_STATUS_IGNORED as TASK_STATUS_IGNORED  # isort: split                                                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/trio/_core/__init__.py", line 21, in <module>                                                               from ._local import RunVar, RunVarToken                                   File "/usr/local/lib/python3.11/dist-packages/trio/_core/_local.py", line 9, in <module>                                                                  from . import _run
  File "/usr/local/lib/python3.11/dist-packages/trio/_core/_run.py", line 2762, in <module>                                                                 from ._io_epoll import (                                                  File "/usr/local/lib/python3.11/dist-packages/trio/_core/_io_epoll.py", line 202, in <module>                                                             class EpollIOManager:
  File "/usr/local/lib/python3.11/dist-packages/trio/_core/_io_epoll.py", line 203, in EpollIOManager                                                       _epoll: select.epoll = attr.ib(factory=select.epoll)                                                               ^^^^^^^^^^^^                     AttributeError: module 'eventlet.green.select' has no attribute 'epoll'     
┌──(root㉿localhost)-[~]                                                    └─#
```
Help

**Comment by hlohaus** [comment]
Try to uninstall eventlet, because it's broken.

```bash
pip uninstall eventlet
```

**Comment by artiomborovinskii** [comment]
Its work thanks
