### ISSUE TITLE
ModuleNotFoundError: No module named 'distutils'

### ISSUE THREAD

**Issue by GolikovStepan48** [xtekky/gpt4free#1467]
Traceback (most recent call last):
  File "a:\Python\RobotAI\main.py", line 1, in <module>
    import g4f
  File "A:\Python 312\Lib\site-packages\g4f\__init__.py", line 6, in <module>
    from .models   import Model, ModelUtils, _all_models
  File "A:\Python 312\Lib\site-packages\g4f\models.py", line 3, in <module>
    from .Provider   import RetryProvider, ProviderType
  File "A:\Python 312\Lib\site-packages\g4f\Provider\__init__.py", line 7, in <module>
    from .deprecated      import *
  File "A:\Python 312\Lib\site-packages\g4f\Provider\deprecated\__init__.py", line 18, in <module>
    from .Aibn          import Aibn
  File "A:\Python 312\Lib\site-packages\g4f\Provider\deprecated\Aibn.py", line 7, in <module>
    from ...requests import StreamSession
  File "A:\Python 312\Lib\site-packages\g4f\requests.py", line 9, in <module>
    from .webdriver import WebDriver, WebDriverSession, bypass_cloudflare, get_driver_cookies
  File "A:\Python 312\Lib\site-packages\g4f\webdriver.py", line 5, in <module>
    from undetected_chromedriver import Chrome, ChromeOptions
  File "A:\Python 312\Lib\site-packages\undetected_chromedriver\__init__.py", line 44, in <module>
    from .patcher import IS_POSIX
  File "A:\Python 312\Lib\site-packages\undetected_chromedriver\patcher.py", line 4, in <module>
    from distutils.version import LooseVersion
ModuleNotFoundError: No module named 'distutils'

**Comment by hlohaus** [comment]
You have to install setuptools, to solve the issue.

pip install setuptools

**Comment by GolikovStepan48** [comment]
thanks
