### ISSUE TITLE
Bing - 'NoneType' object has no attribute 'get'

### ISSUE THREAD

**Issue by l4v3nx** [xtekky/gpt4free#1470]
**Bug description**
What did you do, what happened, which file did you try to run, in which directory
Describe what you did after downloading repo, such as moving to this repo, running this file.

ex.
1. use gpt4-turbo and Bing as a provider
2. ask any info
3. See error in traceback

```
ERROR:root:'NoneType' object has no attribute 'get'
Traceback (most recent call last):
  File "/home/user1/g4f/g4f/gui/server/backend.py", line 97, in try_response
    for chunk in ChatCompletion.create(
  File "/home/user1/g4f/g4f/Provider/create_images.py", line 45, in create_completion
    for chunk in self.provider.create_completion(model, messages, stream, **kwargs):
  File "/home/user1/g4f/g4f/Provider/base_provider.py", line 141, in create_completion
    yield loop.run_until_complete(gen.__anext__())
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/user1/g4f/g4f/Provider/Bing.py", line 278, in stream_generate
    await wss.send_str(create_message(conversation, prompt, tone, context, image_response, web_search, gpt4_turbo))
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user1/g4f/g4f/Provider/Bing.py", line 232, in create_message
    if image_response.get('imageUrl') and image_response.get('originalImageUrl'):
       ^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get'
```
PS using git version of g4f package (cloned repo)

**Comment by iG8R** [comment]
Have the same issue.

**Comment by iG8R** [comment]
Everything is already fine in version 0.2.0.3.
