### ISSUE TITLE
ERROR:root:403 when using the Chatgpt4Online provider

### ISSUE THREAD

**Issue by iG8R** [xtekky/gpt4free#1475]
**Bug description**
ERROR:root:403 appears when using the Chatgpt4Online provider, although while using Chatgpt4Online through a browser everything is OK.
```
Using Chatgpt4Online provider and gpt-3.5-long model
ERROR:root:403, message='Forbidden', url=URL('https://chatgpt4online.org/')
Traceback (most recent call last):
  File "c:\gpt4free\venv\Lib\site-packages\g4f-0.2.0.3-py3.12.egg\g4f\gui\server\backend.py", line 186, in _create_response_stream
    for chunk in ChatCompletion.create(**kwargs):
  File "c:\gpt4free\venv\Lib\site-packages\g4f-0.2.0.3-py3.12.egg\g4f\Provider\base_provider.py", line 186, in create_completion
    yield loop.run_until_complete(gen.__anext__())
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\asyncio\base_events.py", line 664, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "c:\gpt4free\venv\Lib\site-packages\g4f-0.2.0.3-py3.12.egg\g4f\Provider\Chatgpt4Online.py", line 43, in create_async_generator
    response.raise_for_status()
  File "c:\gpt4free\venv\Lib\site-packages\aiohttp\client_reqrep.py", line 1059, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 403, message='Forbidden', url=URL('https://chatgpt4online.org/')
127.0.0.1 - - [15/Jan/2024 21:24:35] "POST /backend-api/v2/conversation HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [15/Jan/2024 21:24:35] "POST /backend-api/v2/conversation HTTP/1.1" 200 -


Using Chatgpt4Online provider and gpt-4 model
ERROR:root:403, message='Forbidden', url=URL('https://chatgpt4online.org/')
Traceback (most recent call last):
  File "c:\gpt4free\venv\Lib\site-packages\g4f-0.2.0.3-py3.12.egg\g4f\gui\server\backend.py", line 186, in _create_response_stream
    for chunk in ChatCompletion.create(**kwargs):
  File "c:\gpt4free\venv\Lib\site-packages\g4f-0.2.0.3-py3.12.egg\g4f\Provider\base_provider.py", line 186, in create_completion
    yield loop.run_until_complete(gen.__anext__())
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\asyncio\base_events.py", line 664, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "c:\gpt4free\venv\Lib\site-packages\g4f-0.2.0.3-py3.12.egg\g4f\Provider\Chatgpt4Online.py", line 43, in create_async_generator
    response.raise_for_status()
  File "c:\gpt4free\venv\Lib\site-packages\aiohttp\client_reqrep.py", line 1059, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 403, message='Forbidden', url=URL('https://chatgpt4online.org/')
127.0.0.1 - - [15/Jan/2024 21:25:05] "POST /backend-api/v2/conversation HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [15/Jan/2024 21:25:05] "POST /backend-api/v2/conversation HTTP/1.1" 200 -
```

**Screenshots**
<img src="https://github.com/xtekky/gpt4free/assets/11407417/702a5cb1-7929-4477-ba4a-9502278ab84f" width="550">

**Environment**
- python version 3.12
- location ( are you in a cloudfare flagged country ) Ukraine

**Comment by iG8R** [comment]
UP

**Comment by xtekky** [comment]
This site is using cloudfare, this is the reason why it does not work, please use other providers
