### ISSUE TITLE
Error reading cookies from chrome [Errno 13] Permission denied (OpenaiChat and HuggingChat)

### ISSUE THREAD

**Issue by iG8R** [xtekky/gpt4free#1476]
**Bug description**
The following error occurs when using OpenaiChat and HuggingChat providers:
`Error reading cookies from chrome for chat.openai.com: [Errno 13] Permission denied: 'C:\\Users\\iG8R\\AppData\\Roaming\\..\\Local\\Google\\Chrome\\User Data\\Default\\Network\\Cookies'`
BUT.
In the case of OpenaiChat, this does not affect the functionality, as cookie are read from Firefox.
```
Using OpenaiChat provider and gpt-4-turbo model
Error reading cookies from chrome for chat.openai.com: [Errno 13] Permission denied: 'C:\\Users\\iG8R\\AppData\\Roaming\\..\\Local\\Google\\Chrome\\User Data\\Default\\Network\\Cookies'
Read cookies from firefox for chat.openai.com
Open browser with config dir: C:\Users\iG8R\AppData\Local\g4f\g4f
127.0.0.1 - - [15/Jan/2024 21:27:07] "POST /backend-api/v2/conversation HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [15/Jan/2024 21:27:07] "POST /backend-api/v2/conversation HTTP/1.1" 200 -
Using OpenaiChat provider and gpt-4-turbo model
127.0.0.1 - - [15/Jan/2024 21:27:33] "POST /backend-api/v2/conversation HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [15/Jan/2024 21:27:33] "POST /backend-api/v2/conversation HTTP/1.1" 200 -
```
In the case of HuggingChat, however, things are different.
```
Using HuggingChat provider and gpt-4-turbo model
Error reading cookies from chrome for .huggingface.co: [Errno 13] Permission denied: 'C:\\Users\\iG8R\\AppData\\Roaming\\..\\Local\\Google\\Chrome\\User Data\\Default\\Network\\Cookies'
ERROR:root:'conversationId'
Traceback (most recent call last):
  File "c:\gpt4free\venv\Lib\site-packages\g4f-0.2.0.3-py3.12.egg\g4f\gui\server\backend.py", line 186, in _create_response_stream
    for chunk in ChatCompletion.create(**kwargs):
  File "c:\gpt4free\venv\Lib\site-packages\g4f-0.2.0.3-py3.12.egg\g4f\Provider\base_provider.py", line 186, in create_completion
    yield loop.run_until_complete(gen.__anext__())
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\asyncio\base_events.py", line 664, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "c:\gpt4free\venv\Lib\site-packages\g4f-0.2.0.3-py3.12.egg\g4f\Provider\needs_auth\HuggingChat.py", line 46, in create_async_generator
    conversation_id = (await response.json())["conversationId"]
                      ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
KeyError: 'conversationId'
127.0.0.1 - - [15/Jan/2024 21:32:19] "POST /backend-api/v2/conversation HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [15/Jan/2024 21:32:19] "POST /backend-api/v2/conversation HTTP/1.1" 200 -
```

**Environment**
- python version 3.12
- location ( are you in a cloudfare flagged country ) Ukraine

**Comment by hlohaus** [comment]
If your Provider works, you can disable the logging of this execption. Then this message will not displayed.
```python
g4f.debug.logging = False
```

**Comment by iG8R** [comment]
The fact of the matter is that HuggingChat initially does not work, showing this error, and OpenaiChat initially works, although it shows this error, but after a while it stops working, but with other additional errors, for example this:
```
Using OpenaiChat provider and gpt-4 model
Read cookies from firefox for chat.openai.com
Open browser with config dir: C:\Users\iG8R\AppData\Local\g4f\g4f
ERROR:root:Response 413: {"detail":{"message":"The message you submitted was too long, please reload the conversation and submit something shorter.","code":"message_length_exceeds_limit"}}
Traceback (most recent call last):
  File "c:\gpt4free\venv\Lib\site-packages\g4f-0.2.0.4-py3.12.egg\g4f\gui\server\backend.py", line 185, in _create_response_stream
    for chunk in ChatCompletion.create(**kwargs):
  File "c:\gpt4free\venv\Lib\site-packages\g4f-0.2.0.4-py3.12.egg\g4f\Provider\base_provider.py", line 199, in create_completion
    yield loop.run_until_complete(gen.__anext__())
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\asyncio\base_events.py", line 664, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "c:\gpt4free\venv\Lib\site-packages\g4f-0.2.0.4-py3.12.egg\g4f\Provider\needs_auth\OpenaiChat.py", line 375, in create_async_generator
    raise RuntimeError(f"Response {response.status_code}: {await response.text()}")
RuntimeError: Response 413: {"detail":{"message":"The message you submitted was too long, please reload the conversation and submit something shorter.","code":"message_length_exceeds_limit"}}
127.0.0.1 - - [21/Jan/2024 15:02:38] "POST /backend-api/v2/conversation HTTP/1.1" 200 -
```
And no matter what I do, only the complete removal of config dir `C:\Users\iG8R\AppData\Local\g4f\g4f` helps to restore its functionality.
After deleting this dir, the operation of OpenaiChat is restored, but after a while everything repeats again.

**Comment by iG8R** [comment]
Is there any way to determine what exactly in the config dir renderes OpenaiChat non-working?

**Comment by hlohaus** [comment]
It is the config dir for the Browser. The are only needed for the cookies / the access token. You can pass the access token directly. Then the Browser are not needed.

**Comment by BinhPQ2** [comment]
How do you guys fix it?
