### ISSUE TITLE
[Bard] ERROR:root:Message: unknown error: ChromeDriver only supports characters in the BMP

### ISSUE THREAD

**Issue by iG8R** [xtekky/gpt4free#1477]
**Bug description**
The following error occurs when using the Bard provider:
```
Using Bard provider and gpt-4-turbo model
Open browser with config dir: C:\Users\iG8R\AppData\Local\g4f\g4f
ERROR:root:Message: unknown error: ChromeDriver only supports characters in the BMP
  (Session info: chrome=120.0.6099.217)
Stacktrace:
        GetHandleVerifier [0x01136EE3+174339]
        (No symbol) [0x01060A51]
        (No symbol) [0x00D76FF6]
        (No symbol) [0x00DD5A71]
        (No symbol) [0x00DA5E6C]
        (No symbol) [0x00DA53FB]
        (No symbol) [0x00DC700C]
        (No symbol) [0x00DA25B0]
        (No symbol) [0x00DC7414]
        (No symbol) [0x00DDA104]
        (No symbol) [0x00DC6DA6]
        (No symbol) [0x00DA1034]
        (No symbol) [0x00DA1F8D]
        GetHandleVerifier [0x011D4B1C+820540]
        sqlite3_dbdata_init [0x012953EE+653550]
        sqlite3_dbdata_init [0x01294E09+652041]
        sqlite3_dbdata_init [0x012897CC+605388]
        sqlite3_dbdata_init [0x01295D9B+656027]
        (No symbol) [0x0106FE6C]
        (No symbol) [0x010683B8]
        (No symbol) [0x010684DD]
        (No symbol) [0x01055818]
        BaseThreadInitThunk [0x764600F9+25]
        RtlGetAppContainerNamedObjectPath [0x77657BBE+286]
        RtlGetAppContainerNamedObjectPath [0x77657B8E+238]
Traceback (most recent call last):
  File "c:\gpt4free\venv\Lib\site-packages\g4f-0.2.0.3-py3.12.egg\g4f\gui\server\backend.py", line 186, in _create_response_stream
    for chunk in ChatCompletion.create(**kwargs):
  File "c:\gpt4free\venv\Lib\site-packages\g4f-0.2.0.3-py3.12.egg\g4f\Provider\needs_auth\Bard.py", line 70, in create_completion
    textarea.send_keys(line)
  File "c:\gpt4free\venv\Lib\site-packages\selenium\webdriver\remote\webelement.py", line 231, in send_keys
    self._execute(
  File "c:\gpt4free\venv\Lib\site-packages\selenium\webdriver\remote\webelement.py", line 395, in _execute
    return self._parent.execute(command, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\gpt4free\venv\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 348, in execute
    self.error_handler.check_response(response)
  File "c:\gpt4free\venv\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: ChromeDriver only supports characters in the BMP
  (Session info: chrome=120.0.6099.217)
Stacktrace:
        GetHandleVerifier [0x01136EE3+174339]
        (No symbol) [0x01060A51]
        (No symbol) [0x00D76FF6]
        (No symbol) [0x00DD5A71]
        (No symbol) [0x00DA5E6C]
        (No symbol) [0x00DA53FB]
        (No symbol) [0x00DC700C]
        (No symbol) [0x00DA25B0]
        (No symbol) [0x00DC7414]
        (No symbol) [0x00DDA104]
        (No symbol) [0x00DC6DA6]
        (No symbol) [0x00DA1034]
        (No symbol) [0x00DA1F8D]
        GetHandleVerifier [0x011D4B1C+820540]
        sqlite3_dbdata_init [0x012953EE+653550]
        sqlite3_dbdata_init [0x01294E09+652041]
        sqlite3_dbdata_init [0x012897CC+605388]
        sqlite3_dbdata_init [0x01295D9B+656027]
        (No symbol) [0x0106FE6C]
        (No symbol) [0x010683B8]
        (No symbol) [0x010684DD]
        (No symbol) [0x01055818]
        BaseThreadInitThunk [0x764600F9+25]
        RtlGetAppContainerNamedObjectPath [0x77657BBE+286]
        RtlGetAppContainerNamedObjectPath [0x77657B8E+238]

127.0.0.1 - - [15/Jan/2024 21:34:50] "POST /backend-api/v2/conversation HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [15/Jan/2024 21:34:50] "POST /backend-api/v2/conversation HTTP/1.1" 200 -
```

**Environment**
- python version 3.12
- location ( are you in a cloudfare flagged country ) Ukraine

**Comment by iG8R** [comment]
In version 2.0.4 it started working fine.

**Comment by iG8R** [comment]
Unfortunately, after the first try the issue appeared again:(
```
Using Bard provider and gpt-4 model
Open browser with config dir: C:\Users\iG8R\AppData\Local\g4f\g4f
ERROR:root:Message: unknown error: cannot connect to chrome at 127.0.0.1:52478
from chrome not reachable
Stacktrace:
        GetHandleVerifier [0x00EA6EE3+174339]
        (No symbol) [0x00DD0A51]
        (No symbol) [0x00AE6E8A]
        (No symbol) [0x00ADC8A3]
        (No symbol) [0x00B0DE94]
        (No symbol) [0x00B07B12]
        (No symbol) [0x00B07927]
        (No symbol) [0x00B3E259]
        (No symbol) [0x00B3DBBA]
        (No symbol) [0x00B36DA6]
        (No symbol) [0x00B11034]
        (No symbol) [0x00B11F8D]
        GetHandleVerifier [0x00F44B1C+820540]
        sqlite3_dbdata_init [0x010053EE+653550]
        sqlite3_dbdata_init [0x01004E09+652041]
        sqlite3_dbdata_init [0x00FF97CC+605388]
        sqlite3_dbdata_init [0x01005D9B+656027]
        (No symbol) [0x00DDFE6C]
        (No symbol) [0x00DD83B8]
        (No symbol) [0x00DD84DD]
        (No symbol) [0x00DC5818]
        BaseThreadInitThunk [0x764600F9+25]
        RtlGetAppContainerNamedObjectPath [0x77657BBE+286]
        RtlGetAppContainerNamedObjectPath [0x77657B8E+238]
Traceback (most recent call last):
  File "c:\gpt4free\venv\Lib\site-packages\g4f-0.2.0.4-py3.12.egg\g4f\gui\server\backend.py", line 185, in _create_response_stream
    for chunk in ChatCompletion.create(**kwargs):
  File "c:\gpt4free\venv\Lib\site-packages\g4f-0.2.0.4-py3.12.egg\g4f\Provider\needs_auth\Bard.py", line 34, in create_completion
    with session as driver:
  File "c:\gpt4free\venv\Lib\site-packages\g4f-0.2.0.4-py3.12.egg\g4f\webdriver.py", line 167, in __enter__
    self.default_driver = get_browser(self.user_data_dir, self.headless, self.proxy, self.options)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\gpt4free\venv\Lib\site-packages\g4f-0.2.0.4-py3.12.egg\g4f\webdriver.py", line 48, in get_browser
    return Chrome(
           ^^^^^^^
  File "c:\gpt4free\venv\Lib\site-packages\undetected_chromedriver\__init__.py", line 466, in __init__
    super(Chrome, self).__init__(
  File "c:\gpt4free\venv\Lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 45, in __init__
    super().__init__(
  File "c:\gpt4free\venv\Lib\site-packages\selenium\webdriver\chromium\webdriver.py", line 61, in __init__
    super().__init__(command_executor=executor, options=options)
  File "c:\gpt4free\venv\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 209, in __init__
    self.start_session(capabilities)
  File "c:\gpt4free\venv\Lib\site-packages\undetected_chromedriver\__init__.py", line 724, in start_session
    super(selenium.webdriver.chrome.webdriver.WebDriver, self).start_session(
  File "c:\gpt4free\venv\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 293, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\gpt4free\venv\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 348, in execute
    self.error_handler.check_response(response)
  File "c:\gpt4free\venv\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot connect to chrome at 127.0.0.1:52478
from chrome not reachable
Stacktrace:
        GetHandleVerifier [0x00EA6EE3+174339]
        (No symbol) [0x00DD0A51]
        (No symbol) [0x00AE6E8A]
        (No symbol) [0x00ADC8A3]
        (No symbol) [0x00B0DE94]
        (No symbol) [0x00B07B12]
        (No symbol) [0x00B07927]
        (No symbol) [0x00B3E259]
        (No symbol) [0x00B3DBBA]
        (No symbol) [0x00B36DA6]
        (No symbol) [0x00B11034]
        (No symbol) [0x00B11F8D]
        GetHandleVerifier [0x00F44B1C+820540]
        sqlite3_dbdata_init [0x010053EE+653550]
        sqlite3_dbdata_init [0x01004E09+652041]
        sqlite3_dbdata_init [0x00FF97CC+605388]
        sqlite3_dbdata_init [0x01005D9B+656027]
        (No symbol) [0x00DDFE6C]
        (No symbol) [0x00DD83B8]
        (No symbol) [0x00DD84DD]
        (No symbol) [0x00DC5818]
        BaseThreadInitThunk [0x764600F9+25]
        RtlGetAppContainerNamedObjectPath [0x77657BBE+286]
        RtlGetAppContainerNamedObjectPath [0x77657B8E+238]

127.0.0.1 - - [21/Jan/2024 14:45:06] "POST /backend-api/v2/conversation HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [21/Jan/2024 14:45:06] "POST /backend-api/v2/conversation HTTP/1.1" 200 -
```
