### ISSUE TITLE
ERROR:root:Response 413:"The message you submitted was too long, please reload the conversation and submit something shorter."

### ISSUE THREAD

**Issue by iG8R** [xtekky/gpt4free#1521]
Every now and then I get the following error when using the OpenaiChat provider, albeit I only send very small commands, e.g. `hi`.
Is there a way to fix it?
```
ERROR:root:Response 413: {"detail":{"message":"The message you submitted was too long, please reload the conversation and submit something shorter.","code":"message_length_exceeds_limit"}}
Traceback (most recent call last):
  File "c:\gpt4free\venv\Lib\site-packages\g4f-0.2.0.7-py3.12.egg\g4f\gui\server\backend.py", line 185, in _create_response_stream
    for chunk in ChatCompletion.create(**kwargs):
  File "c:\gpt4free\venv\Lib\site-packages\g4f-0.2.0.7-py3.12.egg\g4f\Provider\base_provider.py", line 200, in create_completion
    yield loop.run_until_complete(gen.__anext__())
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\asyncio\base_events.py", line 664, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "c:\gpt4free\venv\Lib\site-packages\g4f-0.2.0.7-py3.12.egg\g4f\Provider\needs_auth\OpenaiChat.py", line 379, in create_async_generator
    raise RuntimeError(f"Response {response.status_code}: {await response.text()}")
RuntimeError: Response 413: {"detail":{"message":"The message you submitted was too long, please reload the conversation and submit something shorter.","code":"message_length_exceeds_limit"}}
127.0.0.1 - - [27/Jan/2024 19:12:02] "POST /backend-api/v2/conversation HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [27/Jan/2024 19:12:02] "POST /backend-api/v2/conversation HTTP/1.1" 200 -
```
![image](https://github.com/xtekky/gpt4free/assets/11407417/ed1fb553-9978-4770-8cfe-d30ad34ddfdf)

**Comment by hlohaus** [comment]
It sends the History too. Maybe start a new conversation.

**Comment by iG8R** [comment]
Thanks, you are right!
Is it possible in this case to reset a conversation or start a new one automatically, only alerting the user to what exactly happened, or at least not just show "An error occurred, please try again..." but a more meaningful explanation of what exactly the error is?

**Comment by iG8R** [comment]
up
