### ISSUE TITLE
error when generating any image

### ISSUE THREAD

**Issue by QueenDekim** [xtekky/gpt4free#1526]
when generating any image (via gui), I get the following error:

```log
Exception ignored in: <async_generator object stream_generate at 0x0000022036B04EE0>
Traceback (most recent call last):
  File "C:\Users\Dekim\gpt4free\venv\lib\site-packages\g4f\Provider\retry_provider.py", line 54, in create_completion
    yield token
RuntimeError: async generator ignored GeneratorExit
ERROR:root:Create images failed: we can't create your images right now
Traceback (most recent call last):
  File "C:\Users\Dekim\gpt4free\venv\lib\site-packages\g4f\gui\server\backend.py", line 185, in _create_response_stream
    for chunk in ChatCompletion.create(**kwargs):
  File "C:\Users\Dekim\gpt4free\venv\lib\site-packages\g4f\Provider\create_images.py", line 103, in create_completion
    yield from self.create_images(prompt)
  File "C:\Users\Dekim\gpt4free\venv\lib\site-packages\g4f\Provider\bing\create_images.py", line 214, in create_completion
    yield asyncio.run(self.create_async(prompt))
  File "C:\Users\Dekim\AppData\Local\Programs\Python\Python39\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\Dekim\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "C:\Users\Dekim\gpt4free\venv\lib\site-packages\g4f\Provider\bing\create_images.py", line 231, in create_async
    images = await create_images(session, prompt, self.proxy)
  File "C:\Users\Dekim\gpt4free\venv\lib\site-packages\g4f\Provider\bing\create_images.py", line 117, in create_images
    raise RuntimeError(f"Create images failed: {error}")
RuntimeError: Create images failed: we can't create your images right now
```

in the gui enabled web access and image generator

 ![image](https://github.com/xtekky/gpt4free/assets/85904783/119680a4-20ad-470c-aecf-acd6774fac9e)

**Comment by hlohaus** [comment]
You need maybe more boosts token. You can earn some by using the bing search. Or you wait for one day.
