### ISSUE TITLE
Why all of a sudden using g4f and getting the GPT with the corresponding empty string?

### ISSUE THREAD

**Issue by lotusnowshen** [xtekky/gpt4free#1540]
```python 
def request_chatgpt(content):
    response = g4f.ChatCompletion.create(
        model=g4f.models.gpt_35_turbo,
        messages=[{"role": "user", "content": content}],
        provider=OpenaiChat,
        auth=cookie,
    )  # Alternative model setting
    print('ChatGPT响应: ', response)
    return response
``` 

I've been using g4f and it's working fine, however, just now I realized that I'm getting responses that are all empty, but it's fine to post a dialog to GPT on the web.

Is the openai server detecting this client.

I upgraded to the latest version (2.0.9) and still no result.

<img width="541" alt="image" src="https://github.com/xtekky/gpt4free/assets/5267701/e3b154c8-a1de-4b65-8a33-c63975821bc4">

**Comment by lotusnowshen** [comment]
```
Traceback (most recent call last):
  File "/app/g4f/gui/server/backend.py", line 185, in _create_response_stream
    for chunk in ChatCompletion.create(**kwargs):
  File "/app/g4f/Provider/base_provider.py", line 201, in create_completion
    yield loop.run_until_complete(gen.__anext__())
  File "/home/g4f/.local/lib/python3.10/site-packages/nest_asyncio.py", line 98, in run_until_complete
    return f.result()
  File "/usr/lib/python3.10/asyncio/futures.py", line 201, in result
    raise self._exception.with_traceback(self._exception_tb)
  File "/usr/lib/python3.10/asyncio/tasks.py", line 232, in __step
    result = coro.send(None)
  File "/app/g4f/Provider/needs_auth/OpenaiChat.py", line 378, in create_async_generator
    raise RuntimeError(f"Response {response.status_code}: {await response.text()}")
RuntimeError: Response 400: {"detail":{"message":"Requests with `action=continue` must have a conversation_id and parent_message_id.","code":"continue_with_messages"}}
```

I ran the client with docker and then saw this error log in the terminal.

**Comment by houtarchat-cyber** [comment]
The typical logic of g4f is to gather available free GPT service providers from the web rather than requesting the OpenAI API. the availability of ChatGPT does not equate to the availability of the provider used by g4f. Remove the provider from the code and you'll get a provider with auto-retry logic like this:

```python
def request_chatgpt(content):
    response = g4f.ChatCompletion.create(
        model=g4f.models.gpt_35_turbo,
        messages=[{"role": "user", "content": content}],
        # provider=OpenaiChat,
        # this should be removed to switch provider back to "Auto"
        auth=cookie,
    )  # Alternative model setting
    print('ChatGPT响应: ', response)
    return response
```

**Comment by hlohaus** [comment]
How did you called OpenaiChat. Did you set a api_key?
