### ISSUE TITLE
Problem with GEEKGPT

### ISSUE THREAD

**Issue by Juonior** [xtekky/gpt4free#1545]
I need the GEEKGPT provider, I have been using it all this time, but for the last 3 days it has been giving an error. What to do?

```
using GeekGpt provider and gpt-3.5-turbo-16k model
Traceback (most recent call last):
  File "/Users/daniiltitov/Desktop/snapchat/gpt.py", line 31, in <module>
    print(get_answer([{'role': 'user', 'content': 'Hello'}]))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/daniiltitov/Desktop/snapchat/gpt.py", line 15, in get_answer
    response = g4f.ChatCompletion.create(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/g4f/__init__.py", line 138, in create
    return result if stream else ''.join(result)
                                 ^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/g4f/Provider/GeekGpt.py", line 58, in create_completion
    response.raise_for_status()
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 521 Server Error:  for url: https://ai.fakeopen.com/v1/chat/completions
```

**Comment by BuninSil** [comment]
provider GeekGPT is close(

**Comment by lotusnowshen** [comment]
https://linux.do/t/topic/1051

Unfortunately, the author has shut down the service, refer to the link above.
