### ISSUE TITLE
OpenaiChat ERROR:root:name 'headers' is not defined

### ISSUE THREAD

**Issue by iG8R** [xtekky/gpt4free#1566]
Gpt4Free 0.2.1.1
```
Using OpenaiChat provider and gpt-4 model
Error reading cookies from chrome for chat.openai.com: [Errno 13] Permission denied: 'C:\\Users\\iG8R\\AppData\\Roaming\\..\\Local\\Google\\Chrome\\User Data\\Default\\Network\\Cookies'
Read cookies from firefox for chat.openai.com
Open browser with config dir: C:\Users\iG8R\AppData\Local\g4f\g4f
127.0.0.1 - - [09/Feb/2024 12:53:56] "POST /backend-api/v2/conversation HTTP/1.1" 200 -
ERROR:root:name 'headers' is not defined
NoneType: None
ERROR:root:name 'headers' is not defined
NoneType: None
ERROR:root:name 'headers' is not defined
NoneType: None
ERROR:root:name 'headers' is not defined
NoneType: None
ERROR:root:name 'headers' is not defined
NoneType: None
ERROR:root:name 'headers' is not defined
NoneType: None
ERROR:root:name 'headers' is not defined
NoneType: None
ERROR:root:name 'headers' is not defined
NoneType: None
ERROR:root:name 'headers' is not defined
NoneType: None
ERROR:root:name 'headers' is not defined
NoneType: None
ERROR:root:name 'headers' is not defined
NoneType: None
ERROR:root:name 'headers' is not defined
NoneType: None
ERROR:root:name 'headers' is not defined
NoneType: None
ERROR:root:name 'headers' is not defined
NoneType: None
ERROR:root:name 'headers' is not defined
NoneType: None
ERROR:root:name 'headers' is not defined
Traceback (most recent call last):
  File "c:\gpt4free\venv\Lib\site-packages\g4f\gui\server\backend.py", line 185, in _create_response_stream
    for chunk in ChatCompletion.create(**kwargs):
  File "c:\gpt4free\venv\Lib\site-packages\g4f\Provider\base_provider.py", line 201, in create_completion
    yield loop.run_until_complete(gen.__anext__())
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\asyncio\base_events.py", line 664, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "c:\gpt4free\venv\Lib\site-packages\g4f\Provider\needs_auth\OpenaiChat.py", line 437, in create_async_generator
    await cls.delete_conversation(session, headers, conversation_id)
                                           ^^^^^^^
NameError: name 'headers' is not defined
```

**Comment by nullstreak** [comment]
When model is set to `g4f.models.default`, it unable do determine the default model and throws an error:
```
Traceback (most recent call last):
  File "/home/vlad/Documents/Apps/gpt4free/test.py", line 29, in <module>
    for message in response:
  File "/home/vlad/Documents/Apps/gpt4free/venv/lib/python3.11/site-packages/g4f/Provider/base_provider.py", line 201, in create_completion
    yield loop.run_until_complete(gen.__anext__())
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/vlad/Documents/Apps/gpt4free/venv/lib/python3.11/site-packages/g4f/Provider/needs_auth/OpenaiChat.py", line 359, in create_async_generator
    model = cls.get_model(model or await cls.get_default_model(session, auth_headers))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vlad/Documents/Apps/gpt4free/venv/lib/python3.11/site-packages/g4f/Provider/base_provider.py", line 274, in get_model
    raise ModelNotSupportedError(f"Model is not supported: {model} in: {cls.__name__}")
g4f.errors.ModelNotSupportedError: Model is not supported: text-davinci-002-render-sha in: OpenaiChat
```

**Comment by hlohaus** [comment]
Okay, I will later take a look. OpenAi changed today the API. That are the reason for an update. If you disable auto_continue, the headers error is away.

**Comment by iG8R** [comment]
Thanks for the quick response.
How could I disable auto_continue if I start gpt4free from console (`g4f gui`) and use WebUI?

**Comment by hlohaus** [comment]
I set auto_continue for the GUI in backend.py
But you could simply checkout the git version. I changed already the broken line.

**Comment by iG8R** [comment]
I don't see any changes in backend.py in the git version, for I changed it myself
```
148        if provider == 'OpenaiChat':
149            kwargs['auto_continue'] = False  #change True->False
```

And got the following log:
```
Using OpenaiChat provider and gpt-4 model
127.0.0.1 - - [09/Feb/2024 16:31:39] "POST /backend-api/v2/conversation HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [09/Feb/2024 16:31:39] "POST /backend-api/v2/conversation HTTP/1.1" 200 -
ERROR:root:name 'headers' is not defined
NoneType: None
ERROR:root:name 'headers' is not defined
NoneType: None
ERROR:root:name 'headers' is not defined
NoneType: None
ERROR:root:name 'headers' is not defined
NoneType: None
ERROR:root:name 'headers' is not defined
NoneType: None
.
.
.
```

**Comment by hlohaus** [comment]
Here are the commit: https://github.com/xtekky/gpt4free/commit/2054acce0a71e501490f5c6488b1d0bdc74384d0
I am on the way. I can update g4f first, when I am home again.

**Comment by iG8R** [comment]
Thanks a lot!

**Comment by hlohaus** [comment]
I released now a update for all issues. :)

**Comment by iG8R** [comment]
Thank you so much!
It works:)
