### ISSUE TITLE
[OpenaiChat] ERROR:root:HTTP Error 404: Not Found

### ISSUE THREAD

**Issue by iG8R** [xtekky/gpt4free#1591]
Yesterday, OpenaiChat worked fine, but today after update to 0.2.1.4 (maybe it is a coincidence) any request to it brings up the following error, and there is no flashing Chrome window with the attempt to login, although I can use Open AI chat in a browser with no problems.
BTW, the same error appears with Bard and Pi providers.
```
Using OpenaiChat provider
Error reading cookies from chrome for chat.openai.com: [Errno 13] Permission denied: 'C:\\Users\\iG8R\\AppData\\Roaming\\..\\Local\\Google\\Chrome\\User Data\\Default\\Network\\Cookies'
Read cookies from firefox for chat.openai.com
Open browser with config dir: C:\Users\iG0R\AppData\Local\g4f\g4f
ERROR:root:HTTP Error 404: Not Found
Traceback (most recent call last):
  File "c:\gpt4free\venv\Lib\site-packages\g4f\gui\server\backend.py", line 191, in _create_response_stream
    for chunk in ChatCompletion.create(**kwargs):
  File "c:\gpt4free\venv\Lib\site-packages\g4f\Provider\base_provider.py", line 205, in create_completion
    yield loop.run_until_complete(await_callback(gen.__anext__))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\asyncio\base_events.py", line 664, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "c:\gpt4free\venv\Lib\site-packages\g4f\Provider\base_provider.py", line 201, in await_callback
    return await callback()
           ^^^^^^^^^^^^^^^^
  File "c:\gpt4free\venv\Lib\site-packages\g4f\Provider\needs_auth\OpenaiChat.py", line 341, in create_async_generator
    access_token, cookies = cls.browse_access_token(proxy)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\gpt4free\venv\Lib\site-packages\g4f\Provider\needs_auth\OpenaiChat.py", line 448, in browse_access_token
    driver = get_browser(proxy=proxy)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\gpt4free\venv\Lib\site-packages\g4f\webdriver.py", line 64, in get_browser
    return Chrome(
           ^^^^^^^
  File "c:\gpt4free\venv\Lib\site-packages\undetected_chromedriver\__init__.py", line 258, in __init__
    self.patcher.auto()
  File "c:\gpt4free\venv\Lib\site-packages\undetected_chromedriver\patcher.py", line 178, in auto
    self.unzip_package(self.fetch_package())
                       ^^^^^^^^^^^^^^^^^^^^
  File "c:\gpt4free\venv\Lib\site-packages\undetected_chromedriver\patcher.py", line 287, in fetch_package
    return urlretrieve(download_url)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\urllib\request.py", line 240, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
                            ^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\urllib\request.py", line 215, in urlopen
    return opener.open(url, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\urllib\request.py", line 521, in open
    response = meth(req, response)
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\urllib\request.py", line 630, in http_response
    response = self.parent.error(
               ^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\urllib\request.py", line 559, in error
    return self._call_chain(*args)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\urllib\request.py", line 492, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "C:\Python312\Lib\urllib\request.py", line 639, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
127.0.0.1 - - [17/Feb/2024 00:03:54] "POST /backend-api/v2/conversation HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [17/Feb/2024 00:03:54] "POST /backend-api/v2/conversation HTTP/1.1" 200 -
```

**Comment by iG8R** [comment]
Found out the cause of this issue.
This happened due to Google changed the URL for `chrome-for-testing` and corresponding issue in the `undetected_chromedriver` package. https://github.com/ultrafunkamsterdam/undetected-chromedriver/issues/1743
You need to manually either fix the URL in `patcher.py` or re-install `undetected_chromedriver`
```
pip uninstall undetected-chromedriver
pip install undetected-chromedriver
```

**Comment by xenmods** [comment]
Please close the issue if it is solved, and thanks for the fix!
