### ISSUE TITLE
After installing g4f manually, its version in WebUi shows as 0.0.0.

### ISSUE THREAD

**Issue by iG8R** [xtekky/gpt4free#1593]
I preferably install g4f manually cause I need to make some corrections to the `css` and `html` files so that the WebUI matches to my preferences via:
```
git clone https://github.com/xtekky/gpt4free.git
cd gpt4free
pip install .
```
And every time its version in WebUI shows as 0.0.0.
<img src="https://github.com/xtekky/gpt4free/assets/11407417/23afee13-9652-45c2-95ba-6c8142443cf1" width="200">

It started, I don't remember exactly, around version 0.1.9.6.
To see the correct version, every time I need to correct `setup.py` before manual installation in the following way:
```
64:	VERSION = '0.2.1.4'
65:	DESCRIPTION = (
66:	    'The official gpt4free repository | various collection of powerful language models'
67:	)
68:	
69:	# Setting up
70:	setup(
71:	    name='g4f',
72:	    version=VERSION,
```
Why does such an issue appear with manual installation?
Is there a way to fix it?

**Comment by hlohaus** [comment]
The version number are not saved in the project. It try to read it from git or pip. But also you can set a env:
export G4F_VERSION=0.1.1.2

**Comment by iG8R** [comment]
Thanks for the advice.
Do you mean to implement this through the following code or I didn't get it where I could insert `export G4F_VERSION=0.1.1.2`?
```
import os
os.environ["G4F_VERSION"] = "0.2.1.4"
```
If to use the code above, then it would be more easier in term of manual labor to correct the version number in `setup.py`

**Comment by hlohaus** [comment]
Why in setup.py? The pip version hasn't the problem. Only if you checkout git, is there no version. G4F can't know which branch you have checkout.

**Comment by iG8R** [comment]
> Why in setup.py?

Because:
>I preferably install g4f manually cause I need to make some corrections to the css and html files so that the WebUI matches to my preferences via:

```
git clone https://github.com/xtekky/gpt4free.git
cd gpt4free
pip install .
```

**Comment by hlohaus** [comment]
Also it try to read it from git:

```python
from subprocess import check_output, CalledProcessError, PIPE

command = ["git", "describe", "--tags", "--abbrev=0"]
print(check_output(command, text=True, stderr=PIPE).strip())
```

Do you have a error, if you execute this?

**Comment by iG8R** [comment]
**If `git` is not installed on the machine, then:**

Modified `setup.py`
```
1:	import codecs
2:	import os
3:	
4:	from setuptools import find_packages, setup
5:	from subprocess import check_output, CalledProcessError, PIPE
...
65:	command = ["git", "describe", "--tags", "--abbrev=0"]
66:	VERSION = print(check_output(command, text=True, stderr=PIPE).strip())
67:	DESCRIPTION = (
68:	    'The official gpt4free repository | various collection of powerful language models'
69:	)
```

Resulted log:

```
(venv) c:\gpt4free>pip install .
Processing c:\gpt4free
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [31 lines of output]
      Traceback (most recent call last):
        File "c:\gpt4free\venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "c:\gpt4free\venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "c:\gpt4free\venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\iG8R\AppData\Local\Temp\pip-build-env-rtip614c\overlay\Lib\site-packages\setuptools\build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\iG8R\AppData\Local\Temp\pip-build-env-rtip614c\overlay\Lib\site-packages\setuptools\build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "C:\Users\iG8R\AppData\Local\Temp\pip-build-env-rtip614c\overlay\Lib\site-packages\setuptools\build_meta.py", line 480, in run_setup
          super().run_setup(setup_script=setup_script)
        File "C:\Users\iG8R\AppData\Local\Temp\pip-build-env-rtip614c\overlay\Lib\site-packages\setuptools\build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 66, in <module>
        File "C:\Python312\Lib\subprocess.py", line 466, in check_output
          return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Python312\Lib\subprocess.py", line 548, in run
          with Popen(*popenargs, **kwargs) as process:
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Python312\Lib\subprocess.py", line 1026, in __init__
          self._execute_child(args, executable, preexec_fn, close_fds,
        File "C:\Python312\Lib\subprocess.py", line 1538, in _execute_child
          hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      FileNotFoundError: [WinError 2] The system cannot find the file specified
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

But in the absence of **`git`** installed and in the presence of manually cloned **`g4f`**, when the version number is lower than the latest build, the console can still inform the user about new version.
Is there any way to use this mechanism to derive the build number?

```
(venv) c:\gpt4free>g4f gui -debug
Running on port 8080
 * Serving Flask app 'g4f.gui.server.app'
 * Debug mode: on
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.0.3:8080
Press CTRL+C to quit
 * Restarting with stat
Running on port 8080
 * Debugger is active!
 * Debugger PIN: 724-350-439
127.0.0.1 - - [22/Feb/2024 14:11:00] "GET / HTTP/1.1" 302 -
127.0.0.1 - - [22/Feb/2024 14:11:00] "GET /chat/ HTTP/1.1" 200 -
127.0.0.1 - - [22/Feb/2024 14:11:01] "GET /assets/js/highlightjs-copy.min.js HTTP/1.1" 200 -
127.0.0.1 - - [22/Feb/2024 14:11:01] "GET /assets/js/icons.js HTTP/1.1" 200 -
127.0.0.1 - - [22/Feb/2024 14:11:01] "GET /assets/css/style.css HTTP/1.1" 200 -
127.0.0.1 - - [22/Feb/2024 14:11:01] "GET /assets/js/highlight.min.js HTTP/1.1" 200 -
127.0.0.1 - - [22/Feb/2024 14:11:01] "GET /assets/js/chat.v1.js HTTP/1.1" 200 -
127.0.0.1 - - [22/Feb/2024 14:11:02] "GET /backend-api/v2/models HTTP/1.1" 200 -
127.0.0.1 - - [22/Feb/2024 14:11:02] "GET /assets/img/gpt.png HTTP/1.1" 200 -
127.0.0.1 - - [22/Feb/2024 14:11:02] "GET /backend-api/v2/providers HTTP/1.1" 200 -
127.0.0.1 - - [22/Feb/2024 14:11:02] "GET /backend-api/v2/version HTTP/1.1" 200 -
127.0.0.1 - - [22/Feb/2024 14:11:54] "GET /assets/img/user.png HTTP/1.1" 200 -
New g4f version: 0.2.1.6 (current: 0.2.1.5) | pip install -U g4f
Using OpenaiChat provider and gpt-4 model
Read cookies from chrome for chat.openai.com
Read cookies from firefox for chat.openai.com
Open browser with config dir: C:\Users\iG0R\AppData\Local\g4f\g4f
127.0.0.1 - - [22/Feb/2024 14:12:05] "POST /backend-api/v2/conversation HTTP/1.1" 200 -
```

Although, IMHO, it would be much simpler, easier and more convenient, so as not to get confused, just leave the build number in the sources themselves.

**Comment by hlohaus** [comment]
I don't want commit the version number. Without it is much easier. Maybe we can add "which" to the git command. You are using Windows. So you have a git.exe

**Comment by iG8R** [comment]
Yes, on my personal system I have git, but on my corporate machine I can not install it:(

**Comment by hlohaus** [comment]
Why you are not using the package manager? Maybe we can commit automatically the version after the release to a file.

**Comment by iG8R** [comment]
I use it on my PC, but om my corporate laptop - I just can't due to the stupid security policies.
