### ISSUE TITLE
Liaobots: ServerDisconnectedError: Server disconnected

### ISSUE THREAD

**Issue by weiyideai520** [xtekky/gpt4free#1613]
I run in a Docker environment and set up the Env.

G4F_PROXY: socks5://192.168.198.1:1080

Dialogue content (Chat4)
```
Hello! How can I assist you today?

What model are you currently using?

oops ! something went wrong, please try again / reload. [stacktrace in console]
```

Error Log
```
INFO:     Started server process [12]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:1337 (Press CTRL+C to quit)
172.18.0.1 - - [23/Feb/2024 10:22:49] "GET /backend-api/v2/version HTTP/1.0" 200 -
172.18.0.1 - - [23/Feb/2024 10:22:57] "GET /assets/img/user.png HTTP/1.0" 304 -
ERROR:root:RetryProvider failed:
Liaobots: ServerDisconnectedError: Server disconnected
Bing: RuntimeError: Response: 
Traceback (most recent call last):
  File "/app/g4f/gui/server/backend.py", line 191, in _create_response_stream
    for chunk in ChatCompletion.create(**kwargs):
  File "/app/g4f/Provider/retry_provider.py", line 65, in create_completion
    self.raise_exceptions()
  File "/app/g4f/Provider/retry_provider.py", line 114, in raise_exceptions
    raise RetryProviderError("RetryProvider failed:\n" + "\n".join([
g4f.errors.RetryProviderError: RetryProvider failed:
Liaobots: ServerDisconnectedError: Server disconnected
Bing: RuntimeError: Response: 
172.18.0.1 - - [23/Feb/2024 10:24:09] "POST /backend-api/v2/conversation HTTP/1.0" 200 -
INFO:werkzeug:172.18.0.1 - - [23/Feb/2024 10:24:09] "POST /backend-api/v2/conversation HTTP/1.0" 200 -

```

**Comment by hlohaus** [comment]
Maybe your proxy are not working. Does working other providers with this config?

**Comment by Cha14ka** [comment]
I have the same problem. Proxy works with Bing, but if I use Gemini I get aiohttp.client_exceptions.ServerDisconnectedError: Server disconnected

**Comment by hlohaus** [comment]
We are using aiohttp socks for the support.
But also aiohttp socks5 exist. Should I add support for that too?

https://github.com/HMaker/aiohttp-socks5

**Comment by weiyideai520** [comment]
> Maybe your proxy are not working. Does working other providers with this config?

I can confirm that the proxy is working.

because I have other applications using the same proxy.

**Comment by hlohaus** [comment]
Yes. Maybe a bug from aiohttp_socks.

Can you test this package?: 
  aiohttp_socks5

I replace it then in g4f.

**Comment by weiyideai520** [comment]
I was still able to use Gemini Pro and ChatGPT4.

However, I have tried to use ChatGPT3.5; this is OK.

```
hello？

(1 words, 2 tokens)
your avatar
[You](https://you.com/) with gpt-3.5-turbo
Hello! How can I assist you today?

(7 words, 9 tokens)
your avatar
Hello

your avatar
oops ! something went wrong, please try again / reload. [stacktrace in console]
```


```
172.18.0.1 - - [26/Feb/2024 08:57:08] "GET /assets/img/user.png HTTP/1.0" 304 -
ERROR:root:RetryProvider failed:
GeminiProChat: ServerDisconnectedError: Server disconnected
FreeChatgpt: ServerDisconnectedError: Server disconnected
Traceback (most recent call last):
  File "/app/g4f/gui/server/backend.py", line 191, in _create_response_stream
    for chunk in ChatCompletion.create(**kwargs):
  File "/app/g4f/providers/retry_provider.py", line 66, in create_completion
    self.raise_exceptions()
  File "/app/g4f/providers/retry_provider.py", line 115, in raise_exceptions
    raise RetryProviderError("RetryProvider failed:\n" + "\n".join([
g4f.errors.RetryProviderError: RetryProvider failed:
GeminiProChat: ServerDisconnectedError: Server disconnected
FreeChatgpt: ServerDisconnectedError: Server disconnected
172.18.0.1 - - [26/Feb/2024 08:57:09] "POST /backend-api/v2/conversation HTTP/1.0" 200 -
INFO:werkzeug:172.18.0.1 - - [26/Feb/2024 08:57:09] "POST /backend-api/v2/conversation HTTP/1.0" 200 -
172.18.0.1 - - [26/Feb/2024 08:57:12] "GET /serviceWorker.js HTTP/1.0" 404 -
INFO:werkzeug:172.18.0.1 - - [26/Feb/2024 08:57:12] "GET /serviceWorker.js HTTP/1.0" 404 -
172.18.0.1 - - [26/Feb/2024 08:57:36] "POST /backend-api/v2/conversation HTTP/1.0" 200 -
INFO:werkzeug:172.18.0.1 - - [26/Feb/2024 08:57:36] "POST /backend-api/v2/conversation HTTP/1.0" 200 -
ERROR:root:RetryProvider failed:
Bing: RuntimeError: Response: 
Liaobots: ServerDisconnectedError: Server disconnected
Traceback (most recent call last):
  File "/app/g4f/gui/server/backend.py", line 191, in _create_response_stream
    for chunk in ChatCompletion.create(**kwargs):
  File "/app/g4f/providers/retry_provider.py", line 66, in create_completion
    self.raise_exceptions()
  File "/app/g4f/providers/retry_provider.py", line 115, in raise_exceptions
    raise RetryProviderError("RetryProvider failed:\n" + "\n".join([
g4f.errors.RetryProviderError: RetryProvider failed:
Bing: RuntimeError: Response: 
Liaobots: ServerDisconnectedError: Server disconnected
172.18.0.1 - - [26/Feb/2024 08:58:54] "POST /backend-api/v2/conversation HTTP/1.0" 200 -
INFO:werkzeug:172.18.0.1 - - [26/Feb/2024 08:58:54] "POST /backend-api/v2/conversation HTTP/1.0" 200 -
```

**Comment by hlohaus** [comment]
I found this with google:
  https://stackoverflow.com/questions/76656539/requests-aiohttp-with-socks5-0x05-connection-refused
Maybe you need to enable rdns for the proxy.
I added support for that in g4f here:
 https://github.com/xtekky/gpt4free/pull/1633/files#diff-42d2716a94706c6411d14705a811e5c42f3f1961d43f32b12697171d9b7e9868
