### ISSUE TITLE
[GeminiPro] ERROR:root:Invalid variable type: value should be str, int or float, got None of type <class 'NoneType'>

### ISSUE THREAD

**Issue by iG8R** [xtekky/gpt4free#1620]
```
Using GeminiPro provider and gemini-pro model
ERROR:root:Invalid variable type: value should be str, int or float, got None of type <class 'NoneType'>
Traceback (most recent call last):
  File "c:\gpt4free\venv\Lib\site-packages\g4f\gui\server\backend.py", line 191, in _create_response_stream
    for chunk in ChatCompletion.create(**kwargs):
  File "c:\gpt4free\venv\Lib\site-packages\g4f\providers\base_provider.py", line 204, in create_completion
    yield loop.run_until_complete(await_callback(gen.__anext__))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\asyncio\base_events.py", line 664, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "c:\gpt4free\venv\Lib\site-packages\g4f\providers\base_provider.py", line 200, in await_callback
    return await callback()
           ^^^^^^^^^^^^^^^^
  File "c:\gpt4free\venv\Lib\site-packages\g4f\Provider\GeminiPro.py", line 64, in create_async_generator
    async with session.post(url, params={"key": api_key}, json=data, proxy=proxy) as response:
  File "c:\gpt4free\venv\Lib\site-packages\aiohttp\client.py", line 1187, in __aenter__
    self._resp = await self._coro
                 ^^^^^^^^^^^^^^^^
  File "c:\gpt4free\venv\Lib\site-packages\aiohttp\client.py", line 541, in _request
    req = self._request_class(
          ^^^^^^^^^^^^^^^^^^^^
  File "c:\gpt4free\venv\Lib\site-packages\aiohttp\client_reqrep.py", line 302, in __init__
    url2 = url.with_query(params)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "c:\gpt4free\venv\Lib\site-packages\yarl\_url.py", line 1010, in with_query
    new_query = self._get_str_query(*args, **kwargs) or ""
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\gpt4free\venv\Lib\site-packages\yarl\_url.py", line 971, in _get_str_query
    query = "&".join(self._query_seq_pairs(quoter, query.items()))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\gpt4free\venv\Lib\site-packages\yarl\_url.py", line 934, in _query_seq_pairs
    yield quoter(key) + "=" + quoter(cls._query_var(val))
                                     ^^^^^^^^^^^^^^^^^^^
  File "c:\gpt4free\venv\Lib\site-packages\yarl\_url.py", line 949, in _query_var
    raise TypeError(
TypeError: Invalid variable type: value should be str, int or float, got None of type <class 'NoneType'>
127.0.0.1 - - [23/Feb/2024 23:49:26] "POST /backend-api/v2/conversation HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [23/Feb/2024 23:49:26] "POST /backend-api/v2/conversation HTTP/1.1" 200 -
```

**Comment by iG8R** [comment]
This error occurs because I'm in the country which geo-banned in GedminiPro.
All that was needed to fix this error was to manually input the API key and use a proxy host.
```
...
26:	        api_key: str = "enter your api key here",
...
38:	            url = f"https://xxxxx.netlify.app/v1beta/models/{model}:{method}"
...
```

**Comment by hlohaus** [comment]
I added a missing API key error message
