### ISSUE TITLE
[GeminiPro] 0.2.2.1 ERROR:root:Method doesn't allow unregistered callers (callers without established identity).

### ISSUE THREAD

**Issue by iG8R** [xtekky/gpt4free#1632]
My GeminiPro.py
```
from __future__ import annotations

import base64
import json
from aiohttp import ClientSession

from ..typing import AsyncResult, Messages, ImageType
from .base_provider import AsyncGeneratorProvider, ProviderModelMixin
from ..image import to_bytes, is_accepted_format
from ..errors import MissingAuthError

class GeminiPro(AsyncGeneratorProvider, ProviderModelMixin):
    url = "https://ai.google.dev"
    working = True
    supports_message_history = True
    needs_auth = True
    default_model = "gemini-pro"
    models = ["gemini-pro", "gemini-pro-vision"]

    @classmethod
    async def create_async_generator(
        cls,
        model: str,
        messages: Messages,
        stream: bool = False,
        proxy: str = None,
        api_key: str = "AIzaSxxxxxxxxxxxxxxxxxxxxxxxxxxxx", # my api_key
        api_base: str = f"https://xxxxxxx-xxxxx-xxxxxx.netlify.app/v1beta", # my api_base
        image: ImageType = None,
        **kwargs
    ) -> AsyncResult:
        model = "gemini-pro-vision" if not model and image else model
        model = cls.get_model(model)

        if not api_key:
            raise MissingAuthError('Missing "api_key"')
        if not api_base:
            api_base = f"https://generativelanguage.googleapis.com/v1beta"

        method = "streamGenerateContent" if stream else "generateContent"
        url = f"{api_base.rstrip('/')}/models/{model}:{method}"
        headers = None
        if api_base:
            headers = {f"Authorization": "Bearer {api_key}"}
        else:
            url += f"?key={api_key}"

        async with ClientSession(headers=headers) as session:
            contents = [
                {
                    "role": "model" if message["role"] == "assistant" else message["role"],
                    "parts": [{"text": message["content"]}]
                }
                for message in messages
            ]
            if image:
                image = to_bytes(image)
                contents[-1]["parts"].append({
                    "inline_data": {
                        "mime_type": is_accepted_format(image),
                        "data": base64.b64encode(image).decode()
                    }
                })
            data = {
                "contents": contents,
                "generationConfig": {
                    "stopSequences": kwargs.get("stop"),
                    "temperature": kwargs.get("temperature"),
                    "maxOutputTokens": kwargs.get("max_tokens"),
                    "topP": kwargs.get("top_p"),
                    "topK": kwargs.get("top_k"),
                }
            }
            async with session.post(url, json=data, proxy=proxy) as response:
                if not response.ok:
                    data = await response.json()
                    raise RuntimeError(data[0]["error"]["message"])
                if stream:
                    lines = []
                    async for chunk in response.content:
                        if chunk == b"[{\n":
                            lines = [b"{\n"]
                        elif chunk == b",\r\n" or chunk == b"]":
                            try:
                                data = json.loads(b"".join(lines))
                                yield data["candidates"][0]["content"]["parts"][0]["text"]
                            except:
                                data = data.decode() if isinstance(data, bytes) else data
                                raise RuntimeError(f"Read chunk failed: {data}")
                            lines = []
                        else:
                            lines.append(chunk)
                else:
                    data = await response.json()
                    yield data["candidates"][0]["content"]["parts"][0]["text"]
```

Log:

```
Using GeminiPro provider
ERROR:root:Method doesn't allow unregistered callers (callers without established identity). Please use API Key or other form of API consumer identity to call this API.
Traceback (most recent call last):
  File "c:\gpt4free\venv\Lib\site-packages\g4f\gui\server\backend.py", line 191, in _create_response_stream
    for chunk in ChatCompletion.create(**kwargs):
  File "c:\gpt4free\venv\Lib\site-packages\g4f\providers\base_provider.py", line 204, in create_completion
    yield loop.run_until_complete(await_callback(gen.__anext__))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\asyncio\base_events.py", line 664, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "c:\gpt4free\venv\Lib\site-packages\g4f\providers\base_provider.py", line 200, in await_callback
    return await callback()
           ^^^^^^^^^^^^^^^^
  File "c:\gpt4free\venv\Lib\site-packages\g4f\Provider\GeminiPro.py", line 77, in create_async_generator
    raise RuntimeError(data[0]["error"]["message"])
RuntimeError: Method doesn't allow unregistered callers (callers without established identity). Please use API Key or other form of API consumer identity to call this API.
127.0.0.1 - - [26/Feb/2024 00:08:32] "POST /backend-api/v2/conversation HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [26/Feb/2024 00:08:32] "POST /backend-api/v2/conversation HTTP/1.1" 200 -
```

**Comment by iG8R** [comment]
I corrected some code and GeminiPro started working again:
`74:	            async with session.post(url, params={"key": api_key}, json=data, proxy=proxy) as response:`

But every now and then the following error appears:
```
Using GeminiPro provider
ERROR:root:Please ensure that multiturn requests ends with a user role or a function response.
Traceback (most recent call last):
  File "c:\gpt4free\venv\Lib\site-packages\g4f\gui\server\backend.py", line 191, in _create_response_stream
    for chunk in ChatCompletion.create(**kwargs):
  File "c:\gpt4free\venv\Lib\site-packages\g4f\providers\base_provider.py", line 204, in create_completion
    yield loop.run_until_complete(await_callback(gen.__anext__))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\asyncio\base_events.py", line 664, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "c:\gpt4free\venv\Lib\site-packages\g4f\providers\base_provider.py", line 200, in await_callback
    return await callback()
           ^^^^^^^^^^^^^^^^
  File "c:\gpt4free\venv\Lib\site-packages\g4f\Provider\GeminiPro.py", line 77, in create_async_generator
    raise RuntimeError(data[0]["error"]["message"])
RuntimeError: Please ensure that multiturn requests ends with a user role or a function response.
127.0.0.1 - - [26/Feb/2024 00:32:47] "POST /backend-api/v2/conversation HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [26/Feb/2024 00:32:47] "POST /backend-api/v2/conversation HTTP/1.1" 200 -
```

**Comment by iG8R** [comment]
Still the same error in version 0.2.2.3
```
Using GeminiPro provider
ERROR:root:Method doesn't allow unregistered callers (callers without established identity). Please use API Key or other form of API consumer identity to call this API.
Traceback (most recent call last):
  File "c:\gpt4free\venv\Lib\site-packages\g4f\gui\server\backend.py", line 191, in _create_response_stream
    for chunk in ChatCompletion.create(**kwargs):
  File "c:\gpt4free\venv\Lib\site-packages\g4f\providers\base_provider.py", line 204, in create_completion
    yield loop.run_until_complete(await_callback(gen.__anext__))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\asyncio\base_events.py", line 664, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "c:\gpt4free\venv\Lib\site-packages\g4f\providers\base_provider.py", line 200, in await_callback
    return await callback()
           ^^^^^^^^^^^^^^^^
  File "c:\gpt4free\venv\Lib\site-packages\g4f\Provider\GeminiPro.py", line 81, in create_async_generator
    raise RuntimeError(data["error"]["message"])
RuntimeError: Method doesn't allow unregistered callers (callers without established identity). Please use API Key or other form of API consumer identity to call this API.
127.0.0.1 - - [26/Feb/2024 14:54:32] "POST /backend-api/v2/conversation HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [26/Feb/2024 14:54:32] "POST /backend-api/v2/conversation HTTP/1.1" 200 -
 * Detected change in 'c:\\gpt4free\\venv\\Lib\\site-packages\\g4f\\Provider\\GeminiPro.py', reloading
INFO:werkzeug: * Detected change in 'c:\\gpt4free\\venv\\Lib\\site-packages\\g4f\\Provider\\GeminiPro.py', reloading
 * Restarting with stat
Running on port 8080
 * Debugger is active!
 * Debugger PIN: 724-350-439
Using GeminiPro provider
127.0.0.1 - - [26/Feb/2024 14:56:47] "POST /backend-api/v2/conversation HTTP/1.1" 200 -
Using GeminiPro provider
127.0.0.1 - - [26/Feb/2024 14:57:12] "POST /backend-api/v2/conversation HTTP/1.1" 200 -
```

Only after fixing the code to the following, GeminiPro started working properly:
`77:	            async with session.post(url, params={"key": api_key}, json=data, proxy=proxy) as response:`

**Comment by iG8R** [comment]
Yes, I'm sure. I've tested it about 15-16 times already, and each time, unless there was a modification in line 77 mentioned above, I got the same error.

**Comment by hlohaus** [comment]
Oh, I see you set a base_url. The base_url are for Vertex. Maybe I should add a no_vertex flag

**Comment by iG8R** [comment]
It doesn't work either:(
```
Using GeminiPro provider
ERROR:root:Method doesn't allow unregistered callers (callers without established identity). Please use API Key or other form of API consumer identity to call this API.
Traceback (most recent call last):
  File "c:\gpt4free\venv\Lib\site-packages\g4f\gui\server\backend.py", line 191, in _create_response_stream
    for chunk in ChatCompletion.create(**kwargs):
  File "c:\gpt4free\venv\Lib\site-packages\g4f\providers\base_provider.py", line 204, in create_completion
    yield loop.run_until_complete(await_callback(gen.__anext__))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\asyncio\base_events.py", line 664, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "c:\gpt4free\venv\Lib\site-packages\g4f\providers\base_provider.py", line 200, in await_callback
    return await callback()
           ^^^^^^^^^^^^^^^^
  File "c:\gpt4free\venv\Lib\site-packages\g4f\Provider\GeminiPro.py", line 82, in create_async_generator
    raise RuntimeError(data["error"]["message"])
RuntimeError: Method doesn't allow unregistered callers (callers without established identity). Please use API Key or other form of API consumer identity to call this API.
127.0.0.1 - - [27/Feb/2024 04:39:49] "POST /backend-api/v2/conversation HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [27/Feb/2024 04:39:49] "POST /backend-api/v2/conversation HTTP/1.1" 200 -
```

**Comment by hlohaus** [comment]
Did you add use_auth_header=False in your call?

**Comment by iG8R** [comment]
Oh... exactly!!! I completely forgot...
I changed to
`30:	        use_auth_header: bool = False,`
and everything went well.

Thank you so much for your relentless work.
