### ISSUE TITLE
RuntimeError: Event loop is closed in Linux

### ISSUE THREAD

**Issue by chefexperte** [xtekky/gpt4free#1657]
**Bug description**
When normally using the package with text streaming, I get the following error (not all of the time, but most of the time)

**My code**
```python
import os
import shutil
import textwrap

from g4f.Provider import Bing
from g4f.client import Client

client = Client(
)

# ANSI escape codes for colors and formatting
ANSI_GREEN = "\033[92m"
ANSI_CYAN = "\033[96m"
ANSI_ENDC = "\033[0m"


def ask_gpt(question):
    try:
        response = client.chat.completions.create(
            provider=Bing,
            model="gpt-4",
            messages=[{"role": "user", "content": question}],
            max_tokens=150,
            stream=True
        )
        for response_part in response:
            chunk = response_part.choices[0].delta.content
            if chunk is not None:
                # chunk = chunk.strip()
                # Highlighting quotes and code blocks
                # chunk = chunk.replace('\"', ANSI_GREEN + '\"' + ANSI_ENDC)
                # chunk = chunk.replace('`', ANSI_CYAN + '`' + ANSI_ENDC)
                try:
                    console_width = os.get_terminal_size().columns
                except OSError:
                    console_width = shutil.get_terminal_size((80, 20)).columns
                chunk = textwrap.fill(chunk, width=console_width)
                print(chunk, end='', flush=True)
    except Exception as e:
        if type(e) is KeyboardInterrupt:
            print("Interrupted")
            return
        print(type(e))
        print(f"An error occurred: {e}")


def main():
    question = input("Your question: ")
    print("Getting response... ")
    ask_gpt(question)


if __name__ == "__main__":
    main()

```

**Screenshots**
```python
Traceback (most recent call last):
  File "/home/aaron/Documents/AskYourTerminal/.venv/lib64/python3.12/site-packages/aiohttp/client_reqrep.py", line 881, in __del__
    self._connection.release()
  File "/home/aaron/Documents/AskYourTerminal/.venv/lib64/python3.12/site-packages/aiohttp/connector.py", line 173, in release
    self._connector._release(
  File "/home/aaron/Documents/AskYourTerminal/.venv/lib64/python3.12/site-packages/aiohttp/connector.py", line 667, in _release
    protocol.close()
  File "/home/aaron/Documents/AskYourTerminal/.venv/lib64/python3.12/site-packages/aiohttp/client_proto.py", line 65, in close
    transport.close()
  File "/usr/lib64/python3.12/asyncio/sslproto.py", line 116, in close
    self._ssl_protocol._start_shutdown()
  File "/usr/lib64/python3.12/asyncio/sslproto.py", line 624, in _start_shutdown
    self._shutdown_timeout_handle = self._loop.call_later(
                                    ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/asyncio/base_events.py", line 759, in call_later
    timer = self.call_at(self.time() + delay, callback, *args,
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/asyncio/base_events.py", line 772, in call_at
    self._check_closed()
  File "/usr/lib64/python3.12/asyncio/base_events.py", line 540, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7fa2481cce90>
```

**Environment**
- Python 1.12
- g4f 0.2.2.7
- Fedora Linux

**Additional context**
Since the other erros all seemed to be for Windows and the asyncio EventLoop Policy fix does not work (since it is Windows specific) I decided it would be best to open a new issue for this, hope it's okay.

**Comment by hlohaus** [comment]
What are the other errors? The "event loop is closed" error is no error which we can fix. The question is: why is the event loop closed? The reason is mostly the issue for this.

**Comment by CSEC-ADMINS** [comment]
same problem , what can I do if it raises that error
