### ISSUE TITLE
Error module Phind

### ISSUE THREAD

**Issue by CanandNac** [xtekky/gpt4free#166]
Errors appear on startup: File "/home/canandnac/.local/lib/python3.11/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 565, in _run_script    exec(code, module.__dict__)File "/home/canandnac/Рабочий стол/gpt4free-main/gui/streamlit_app.py", line 2, in <module>
    import phind

**Comment by 9xN** [comment]
this is what i got :

Traceback (most recent call last):
  File "main.py", line 14, in <module>
    results     = phind.Search.create(prompt, actualSearch = True), # create search (set actualSearch to False to disable internet)
  File "/home/runner/ai-api/phind/__init__.py", line 98, in create
    'browserLanguage': language}).json()['rawBingResults']
  File "/home/runner/ai-api/venv/lib/python3.10/site-packages/curl_cffi/requests/cookies.py", line 54, in json
    return loads(self.content, **kw)
  File "/nix/store/hd4cc9rh83j291r5539hkf6qd8lgiikb-python3-3.10.8/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/nix/store/hd4cc9rh83j291r5539hkf6qd8lgiikb-python3-3.10.8/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/nix/store/hd4cc9rh83j291r5539hkf6qd8lgiikb-python3-3.10.8/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
