### ISSUE TITLE
we can't create your images right now

### ISSUE THREAD

**Issue by QueenDekim** [xtekky/gpt4free#1671]
when I try to generate an image, I get the answer "we can't create your images right now"

```
Traceback (most recent call last):
  File "c:\Users\Dekim\gpt4free\img.py", line 7, in <module>
    response = client.images.generate(
  File "c:\Users\Dekim\gpt4free\g4f\client.py", line 194, in generate
    for chunk in response:
  File "c:\Users\Dekim\gpt4free\g4f\Provider\BingCreateImages.py", line 38, in create
    yield asyncio.run(self.create_async(prompt))
  File "C:\Users\Dekim\AppData\Local\Programs\Python\Python39\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\Dekim\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "c:\Users\Dekim\gpt4free\g4f\Provider\BingCreateImages.py", line 55, in create_async
    images = await create_images(session, prompt, proxy)
  File "c:\Users\Dekim\gpt4free\g4f\Provider\bing\create_images.py", line 130, in create_images
    raise RuntimeError(f"Create images failed: {error}")
RuntimeError: Create images failed: we can't create your images right now
```

my code:

```
from g4f.client import Client
from sys import argv

input = argv[1]

client = Client()
response = client.images.generate(
  model="GPT-4",
  prompt= input,
)
image_url = response.data[0].url
print(image_url)
```

**Comment by QueenDekim** [comment]
although this code returns the url before that

**Comment by QueenDekim** [comment]
before this a task is created

```
Id     Name            PSJobTypeName   State         HasMoreData     Location             Command
--     ----            -------------   -----         -----------     --------             -------
5      Job5            BackgroundJob   Running       True            localhost            c
```

**Comment by hlohaus** [comment]
You don't have enough coints in your account, if you become this error message. Use a other Account or wait some time.

**Comment by QueenDekim** [comment]
but I can generate images on the site
I can't do it only through g4f

**Comment by hlohaus** [comment]
Do you are using the same account? You need boosts for creating images with Bing.

**Comment by QueenDekim** [comment]
> Do you are using the same account? You need boosts for creating images with Bing.

yes
