### ISSUE TITLE
Response 404: Can't create a new chat

### ISSUE THREAD

**Issue by daniellachev** [xtekky/gpt4free#1689]
Hey guys. I tried to run g4f with Bing provider in Python and it worked pretty good. But when I changed the query and ran it for the second time this error occurred:

Traceback (most recent call last):
  File "/Users/macbook/Developer/vAIralify/testing.py", line 12, in <module>
    for message in response:
  File "/opt/homebrew/lib/python3.12/site-packages/g4f/providers/base_provider.py", line 204, in create_completion
    yield loop.run_until_complete(await_callback(gen.__anext__))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.2_1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/base_events.py", line 685, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.12/site-packages/g4f/providers/base_provider.py", line 200, in await_callback
    return await callback()
           ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.12/site-packages/g4f/Provider/Bing.py", line 326, in stream_generate
    conversation = await create_conversation(session)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.12/site-packages/g4f/Provider/bing/conversation.py", line 55, in create_conversation
    raise ResponseStatusError(f"Response {response.status}: Can't create a new chat")
g4f.errors.ResponseStatusError: Response 404: Can't create a new chat

Here is my code:

```
import g4f

query = "How many letters can I prompt you with?"

response = g4f.ChatCompletion.create(
    model="gpt-3.5-turbo",
    provider=g4f.Provider.Bing,
    messages=[{"role": "user", "content": query}],
    stream=True,
)

for message in response:
    print(message, flush=True, end='')
```

What might the issue be?

**Comment by hlohaus** [comment]
You have become a Ban from Bing. Only a new ip address help.
The new version from yesterday has now a wait and retry logic.
That helps to become no ban.

**Comment by wangwchcs** [comment]
I'm also getting this error today. Is there any way to resolve it?

**Comment by hlohaus** [comment]
The error comes from there firewall.

With Bing Web you can't do so many requests without solving a captcha too.

I am fine with the rate limit from Bing.

Bing works for my use cases.
