### ISSUE TITLE
[You] Any request results in "ERROR:root:Response 403: Cloudflare detected"

### ISSUE THREAD

**Issue by iG8R** [xtekky/gpt4free#1707]
**Bug description**
Making any request through the g4f WebUI results in:

```
Using You provider
ERROR:root:Response 403: Cloudflare detected
Traceback (most recent call last):
  File "c:\gpt4free\venv\Lib\site-packages\g4f\gui\server\backend.py", line 191, in _create_response_stream
    for chunk in ChatCompletion.create(**kwargs):
  File "c:\gpt4free\venv\Lib\site-packages\g4f\providers\base_provider.py", line 204, in create_completion
    yield loop.run_until_complete(await_callback(gen.__anext__))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\asyncio\base_events.py", line 664, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "c:\gpt4free\venv\Lib\site-packages\g4f\providers\base_provider.py", line 200, in await_callback
    return await callback()
           ^^^^^^^^^^^^^^^^
  File "c:\gpt4free\venv\Lib\site-packages\g4f\Provider\You.py", line 108, in create_async_generator
    await raise_for_status(response)
  File "c:\gpt4free\venv\Lib\site-packages\g4f\requests\__init__.py", line 89, in raise_for_status_async
    raise ResponseStatusError(f"Response {response.status}: Cloudflare detected")
g4f.errors.ResponseStatusError: Response 403: Cloudflare detected
127.0.0.1 - - [15/Mar/2024 12:58:01] "POST /backend-api/v2/conversation HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [15/Mar/2024 12:58:01] "POST /backend-api/v2/conversation HTTP/1.1" 200 -
```

**Comment by hlohaus** [comment]
I changed the request session from aiohttp to curl_cffi in my pull request. That bypass cloudflare here.

**Comment by iG8R** [comment]
Excellent! I now use 0.2.4.1 version, what is your PR that contains these changes?

**Comment by Invisibilities** [comment]
Gettting the same error
