### ISSUE TITLE
Binary Location must be a string

### ISSUE THREAD

**Issue by Baldi89989** [xtekky/gpt4free#1708]
**Bug description**
When trying to send a request to the api, i get this error.

```
ERROR:root:Binary Location Must be a String
Traceback (most recent call last):
  File "D:\Clyde\main.py", line 39, in on_message
    response = await chatgpt.chat.completions.create(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\benja\AppData\Local\Programs\Python\Python312\Lib\site-packages\g4f\client.py", line 163, in create
    return response if stream else next(response)
                                   ^^^^^^^^^^^^^^
  File "c:\Users\benja\AppData\Local\Programs\Python\Python312\Lib\site-packages\g4f\client.py", line 84, in iter_append_model_and_provider
    for chunk in response:
  File "c:\Users\benja\AppData\Local\Programs\Python\Python312\Lib\site-packages\g4f\client.py", line 49, in iter_response
    for idx, chunk in enumerate(response):
  File "c:\Users\benja\AppData\Local\Programs\Python\Python312\Lib\site-packages\g4f\providers\base_provider.py", line 204, in create_completion
    yield loop.run_until_complete(await_callback(gen.__anext__))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\benja\AppData\Local\Programs\Python\Python312\Lib\site-packages\nest_asyncio.py", line 98, in run_until_complete
    return f.result()
           ^^^^^^^^^^
  File "c:\Users\benja\AppData\Local\Programs\Python\Python312\Lib\asyncio\futures.py", line 203, in result
    raise self._exception.with_traceback(self._exception_tb)
  File "c:\Users\benja\AppData\Local\Programs\Python\Python312\Lib\asyncio\tasks.py", line 314, in __step_run_and_handle_result
    result = coro.send(None)
             ^^^^^^^^^^^^^^^
  File "c:\Users\benja\AppData\Local\Programs\Python\Python312\Lib\site-packages\g4f\providers\base_provider.py", line 200, in await_callback
    return await callback()
           ^^^^^^^^^^^^^^^^
  File "c:\Users\benja\AppData\Local\Programs\Python\Python312\Lib\site-packages\g4f\Provider\You.py", line 55, in create_async_generator
    cls._args = get_args_from_browser(cls.url, webdriver, proxy)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\benja\AppData\Local\Programs\Python\Python312\Lib\site-packages\g4f\requests\__init__.py", line 41, in get_args_from_browser
    with WebDriverSession(webdriver, "", proxy=proxy, virtual_display=virtual_display) as driver:
  File "c:\Users\benja\AppData\Local\Programs\Python\Python312\Lib\site-packages\g4f\webdriver.py", line 224, in __enter__
    self.default_driver = get_browser(self.user_data_dir, self.headless, self.proxy, self.options)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\benja\AppData\Local\Programs\Python\Python312\Lib\site-packages\g4f\webdriver.py", line 81, in get_browser
    return Chrome(
           ^^^^^^^
  File "c:\Users\benja\AppData\Local\Programs\Python\Python312\Lib\site-packages\undetected_chromedriver\__init__.py", line 372, in __init__
    options.binary_location = (
    ^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\benja\AppData\Local\Programs\Python\Python312\Lib\site-packages\selenium\webdriver\chromium\options.py", line 52, in binary_location
    raise TypeError(self.BINARY_LOCATION_ERROR)
TypeError: Binary Location Must be a String
```

Is there any way to fix this?

**Environment**
Python version: 3.12.1

**Comment by hlohaus** [comment]
You need to install the Google Chrome Browser for the Webdriver features.
