### ISSUE TITLE
TypeError: OpenaiChat.iter_messages_chunk() takes 4 positional arguments but 5 were given

### ISSUE THREAD

**Issue by ozipoetra** [xtekky/gpt4free#1718]
I got this error when using `OpenaiChat` provider

```log
{"error": {"message": "TypeError: OpenaiChat.iter_messages_chunk() takes 4 positional arguments but 5 were given"}, "model": "gpt-3.5-turbo", "provider": "OpenaiChat"}
```

**Comment by iG8R** [comment]
The same issue:
```
Using OpenaiChat provider and gpt-3.5-turbo model
ERROR:root:OpenaiChat.iter_messages_chunk() takes 4 positional arguments but 5 were given
Traceback (most recent call last):
  File "c:\gpt4free\venv\Lib\site-packages\g4f\gui\server\api.py", line 144, in _create_response_stream
    for chunk in ChatCompletion.create(**kwargs):
  File "c:\gpt4free\venv\Lib\site-packages\g4f\providers\base_provider.py", line 206, in create_completion
    yield loop.run_until_complete(await_callback(gen.__anext__))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\asyncio\base_events.py", line 664, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "c:\gpt4free\venv\Lib\site-packages\g4f\providers\base_provider.py", line 202, in await_callback
    return await callback()
           ^^^^^^^^^^^^^^^^
  File "c:\gpt4free\venv\Lib\site-packages\g4f\Provider\needs_auth\OpenaiChat.py", line 453, in create_async_generator
    async for chunk in cls.iter_messages_chunk(response.iter_lines(), session, fields, websocket_request_id):
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: OpenaiChat.iter_messages_chunk() takes 4 positional arguments but 5 were given
127.0.0.1 - - [19/Mar/2024 06:34:59] "POST /backend-api/v2/conversation HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2024 06:34:59] "POST /backend-api/v2/conversation HTTP/1.1" 200 -
```
