### ISSUE TITLE
docker won't run gui and api

### ISSUE THREAD

**Issue by Woukim** [xtekky/gpt4free#1720]
**Bug description**
docker won't run gui. new update [g4f v0.2.5.4](https://github.com/xtekky/gpt4free/releases/tag/0.2.5.4)

**Screenshots**
![image](https://github.com/xtekky/gpt4free/assets/138323639/c6384ae0-d79f-467f-8bc7-dd164c840383)

**Environment**
Docker 4.28.0

upd. 

I reinstalled the image and run this command, it works. docker run -p 8080:8080 -p 1337:1337 -p 7900:7900 --shm-size="2g" hlohaus789/g4f:latest

**Comment by hlohaus** [comment]
@exfly Are your changes are working? I have bad internet here. I can't download it right now.

**Comment by jackfood** [comment]
I got the following error when running API via docker. Anyone know what happened, how do i change the provider / model selection?

```
Model not found: gpt-4-turbo-preview
2024-03-23 07:50:54 Traceback (most recent call last):
2024-03-23 07:50:54   File "/app/g4f/api/__init__.py", line 91, in chat_completions
2024-03-23 07:50:54     response = self.client.chat.completions.create(
2024-03-23 07:50:54                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-03-23 07:50:54   File "/app/g4f/client.py", line 141, in create
2024-03-23 07:50:54     model, provider = get_model_and_provider(
2024-03-23 07:50:54                       ^^^^^^^^^^^^^^^^^^^^^^^
2024-03-23 07:50:54   File "/app/g4f/__init__.py", line 63, in get_model_and_provider
2024-03-23 07:50:54     raise ModelNotFoundError(f'Model not found: {model}')
2024-03-23 07:50:54 g4f.errors.ModelNotFoundError: Model not found: gpt-4-turbo-preview
2024-03-23 07:50:54 INFO:     172.17.0.1:33926 - "POST /v1/chat/completions HTTP/1.1" 500 Internal Server Error
2024-03-23 07:52:21 Trapped SIGTERM/SIGINT/x so shutting down supervisord...
2024-03-23 07:52:22 2024-03-22 23:52:22,500 WARN received SIGTERM indicating exit request
2024-03-23 07:52:22 2024-03-22 23:52:22,501 INFO waiting for xvfb, vnc, novnc, g4f-api, g4f-gui to die
2024-03-23 07:52:22 2024-03-22 23:52:22,505 WARN stopped: g4f-gui (terminated by SIGTERM)
```

**Comment by hlohaus** [comment]
We have no gpt-4-turbo-preview model jet.
Can you change your selected model to: 
gpt-4-turbo or somethings else?
