### ISSUE TITLE
Bing image generation broken in 0.2.5.4

### ISSUE THREAD

**Issue by AuroraWright** [xtekky/gpt4free#1723]
When asking bing to generate something, it refuses in balanced/creative/precise modes. In copilot mode it seems to work, but there's an error after waiting for a while:

ERROR:root:Object of type ImageResponse is not JSON serializable
Traceback (most recent call last):
  File "/Users/aurora/.pyenv/versions/gpt4free/lib/python3.12/site-packages/g4f/gui/server/api.py", line 155, in _create_response_stream
    yield self._format_json("content", chunk)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aurora/.pyenv/versions/gpt4free/lib/python3.12/site-packages/g4f/gui/server/backend.py", line 109, in _format_json
    return json.dumps(super()._format_json(response_type, content)) + "\n"
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.2_1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.2_1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.2_1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/json/encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.2_1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type ImageResponse is not JSON serializable

**Comment by xtekky** [comment]
Have you tried installing a version prior to 0.2.5.4 ?
like 
```
pip install g4f=0.2.5.3
```
