### ISSUE TITLE
MissingRequirementsError: Install "curl_cffi" package

### ISSUE THREAD

**Issue by messizqin** [xtekky/gpt4free#1724]
```py
client = Client()
response = client.chat.completions.create(
    model="gpt-3.5-turbo",
    messages=[{"role":"user","content":"hi there"}],
    stream=True,
)

for message in response:
    print(message, flush=True, end='')
```

```txt
Traceback (most recent call last):
  File "/var/www/ai/ai/manage.py", line 22, in <module>
    main()
  File "/var/www/ai/ai/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/var/www/ai/lib/python3.11/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/var/www/ai/lib/python3.11/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/var/www/ai/lib/python3.11/site-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/var/www/ai/lib/python3.11/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/www/ai/lib/python3.11/site-packages/django/core/management/commands/shell.py", line 127, in handle
    exec(sys.stdin.read(), globals())
  File "<string>", line 38, in <module>
  File "/var/www/ai/lib/python3.11/site-packages/g4f/client.py", line 84, in iter_append_model_and_provider
    for chunk in response:
  File "/var/www/ai/lib/python3.11/site-packages/g4f/client.py", line 49, in iter_response
    for idx, chunk in enumerate(response):
  File "/var/www/ai/lib/python3.11/site-packages/g4f/providers/retry_provider.py", line 81, in create_completion
    raise_exceptions(exceptions)
  File "/var/www/ai/lib/python3.11/site-packages/g4f/providers/retry_provider.py", line 201, in raise_exceptions
    raise RetryProviderError("RetryProvider failed:\n" + "\n".join([
g4f.errors.RetryProviderError: RetryProvider failed:
You: MissingRequirementsError: Install "curl_cffi" package
Chatgpt4Online: HTTPError: HTTP Error 404: Not Found
```

I have installed `curl_cffi` package for sure, and it seems g4f is handling this exception wrongly without prompting its real issue.

curl cffi version 0.6.0b7
g4f version 0.2.5.7

**Comment by iG8R** [comment]
Have the same issue, e.g. with the You provider.

**Comment by anath3m98** [comment]
I also have the same issue

**Comment by hlohaus** [comment]
It works for me, but only gpt-3 are working currently.

What are the output, when you do:

pip install -U curl_cffi 

Which version will be installed?
