### ISSUE TITLE
OpenAI Plus Subscriber are not working

### ISSUE THREAD

**Issue by TheFlyingPirate** [xtekky/gpt4free#1734]
ERROR:root:OpenAI Plus Subscriber are not working
Traceback (most recent call last):
  File "/app/g4f/gui/server/api.py", line 228, in _create_response_stream
    for chunk in ChatCompletion.create(**kwargs):
  File "/app/g4f/providers/base_provider.py", line 206, in create_completion
    yield loop.run_until_complete(await_callback(gen.__anext__))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/app/g4f/providers/base_provider.py", line 202, in await_callback
    return await callback()
           ^^^^^^^^^^^^^^^^
  File "/app/g4f/Provider/needs_auth/OpenaiChat.py", line 442, in create_async_generator
    raise ProviderNotWorkingError("OpenAI Plus Subscriber are not working")
g4f.errors.ProviderNotWorkingError: OpenAI Plus Subscriber are not working

I keep getting this error, I use the provided docker image on multiple machines and always get this error when using Openaichat as provider, I am in Germany

**Comment by hlohaus** [comment]
OpenAI has changed the ArkoseToken. The ArkoseToken Generator are not working anymore. I change it. But free Accounts are still working.

**Comment by hlohaus** [comment]
I fixed:
ProviderNotWorkingError: OpenAI Plus Subscriber are not working
I added .har file support for OpenaiChat.
Simple download the .har file from the OpenAI Chat and place them in current dir ./ or in a sub dir.
