### ISSUE TITLE
[OpenaiChat] Response 404: {"detail":{"message":"Conversation not found","code":"conversation_not_found"}}

### ISSUE THREAD

**Issue by iG8R** [xtekky/gpt4free#1767]
The second request to OpenaiChat in the g4f WebUI (0.2.7.1) results in the following error:
```
Using OpenaiChat provider and gpt-3.5-turbo model
127.0.0.1 - - [30/Mar/2024 13:37:28] "GET /static/img/user.png HTTP/1.1" 304 -
INFO:werkzeug:127.0.0.1 - - [30/Mar/2024 13:37:28] "GET /static/img/user.png HTTP/1.1" 304 -
127.0.0.1 - - [30/Mar/2024 13:37:29] "POST /backend-api/v2/conversation HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [30/Mar/2024 13:37:29] "POST /backend-api/v2/conversation HTTP/1.1" 200 -
Using OpenaiChat provider and gpt-3.5-turbo model
ERROR:root:Response 404: {"detail":{"message":"Conversation not found","code":"conversation_not_found"}}
Traceback (most recent call last):
  File "c:\gpt4free\venv\Lib\site-packages\g4f\gui\server\api.py", line 229, in _create_response_stream
    for chunk in ChatCompletion.create(**kwargs):
  File "c:\gpt4free\venv\Lib\site-packages\g4f\providers\base_provider.py", line 206, in create_completion
    yield loop.run_until_complete(await_callback(gen.__anext__))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\asyncio\base_events.py", line 664, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "c:\gpt4free\venv\Lib\site-packages\g4f\providers\base_provider.py", line 202, in await_callback
    return await callback()
           ^^^^^^^^^^^^^^^^
  File "c:\gpt4free\venv\Lib\site-packages\g4f\Provider\needs_auth\OpenaiChat.py", line 425, in create_async_generator
    await raise_for_status(response)
  File "c:\gpt4free\venv\Lib\site-packages\g4f\requests\raise_for_status.py", line 23, in raise_for_status_async
    raise ResponseStatusError(f"Response {response.status}: {message}")
g4f.errors.ResponseStatusError: Response 404: {"detail":{"message":"Conversation not found","code":"conversation_not_found"}}
127.0.0.1 - - [30/Mar/2024 13:37:48] "POST /backend-api/v2/conversation HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [30/Mar/2024 13:37:48] "POST /backend-api/v2/conversation HTTP/1.1" 200 -
```

**Comment by iG8R** [comment]
Thank you @hlohaus 

PS. This issue has been resolved in version 0.2.7.2.
