### ISSUE TITLE
asks to install packages that are installed

### ISSUE THREAD

**Issue by gmankab** [xtekky/gpt4free#1778]
code:
```python
client = Client()
response = client.chat.completions.create(
    model="gpt-3.5-turbo",
    messages=[{"role": "user", "content": "Hello"}],
)
```

error:
```shell
python ./test.py 
Traceback (most recent call last):
  File "/var/home/hmk/proj/test/./test.py", line 7, in <module>
    response = client.chat.completions.create(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/home/hmk/.pyenv/versions/3.12.2/lib/python3.12/site-packages/g4f/client.py", line 163, in create
    return response if stream else next(response)
                                   ^^^^^^^^^^^^^^
  File "/var/home/hmk/.pyenv/versions/3.12.2/lib/python3.12/site-packages/g4f/client.py", line 84, in iter_append_model_and_provider
    for chunk in response:
  File "/var/home/hmk/.pyenv/versions/3.12.2/lib/python3.12/site-packages/g4f/client.py", line 49, in iter_response
    for idx, chunk in enumerate(response):
  File "/var/home/hmk/.pyenv/versions/3.12.2/lib/python3.12/site-packages/g4f/providers/retry_provider.py", line 81, in create_completion
    raise_exceptions(exceptions)
  File "/var/home/hmk/.pyenv/versions/3.12.2/lib/python3.12/site-packages/g4f/providers/retry_provider.py", line 201, in raise_exceptions
    raise RetryProviderError("RetryProvider failed:\n" + "\n".join([
g4f.errors.RetryProviderError: RetryProvider failed:
You: CloudflareError: Response 403: Cloudflare detected
Chatgpt4Online: MissingRequirementsError: Install "undetected_chromedriver" and "platformdirs" package
```

this packages are already installed:
```
pip freeze | grep 'undetected-chromedriver\|platformdirs'
platformdirs==4.2.0
undetected-chromedriver==3.5.5
```

**Environment**
- python 3.12.2
- united states proxy that works with chat.openai.com in browser

**Comment by gmankab** [comment]
`pip install setuptools undetected_chromedriver platformdirs rich g4f`

this helped

can you please indicate in the error message that setuptools must be installed?

**Comment by hlohaus** [comment]
I updated the error message.

**Comment by gmankab** [comment]
thanks
