### ISSUE TITLE
response 401

### ISSUE THREAD

**Issue by haishengXie0712** [xtekky/gpt4free#1796]
[2024-04-07 06:54:06,589] ERROR in app: Exception on /backend-api/v2/version [GET]
Traceback (most recent call last):
  File "/usr/lib/python3.11/importlib/metadata/__init__.py", line 563, in from_name
    return next(cls.discover(name=name))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/g4f/version.py", line 101, in latest_version
    get_package_version(PACKAGE_NAME)
  File "/usr/lib/python3.11/importlib/metadata/__init__.py", line 1008, in version
    return distribution(distribution_name).version
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/metadata/__init__.py", line 981, in distribution
    return Distribution.from_name(distribution_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/metadata/__init__.py", line 565, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: No package metadata was found for g4f

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/g4f/.local/lib/python3.11/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/g4f/.local/lib/python3.11/site-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/g4f/.local/lib/python3.11/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/g4f/.local/lib/python3.11/site-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/g4f/gui/server/api.py", line 91, in get_version
    "latest_version": version.utils.latest_version,
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/functools.py", line 1001, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/app/g4f/version.py", line 103, in latest_version
    return get_github_version(GITHUB_REPOSITORY)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/g4f/version.py", line 48, in get_github_version
    return response["tag_name"]
           ~~~~~~~~^^^^^^^^^^^^
KeyError: 'tag_name'
172.17.0.1 - - [07/Apr/2024 06:54:06] "GET /backend-api/v2/version HTTP/1.1" 500 -

**Comment by hlohaus** [comment]
The version check raised this error. How do you use the g4f package. 
If you include g4f in your script,  you could disable the version check.

**Comment by AksLolCoding** [comment]
Btw you can disable version check by running
```python
g4f.debug.version_check = False
```
before using a client.
