### ISSUE TITLE
An error occured: TypeError: network error

### ISSUE THREAD

**Issue by qdins2077** [xtekky/gpt4free#1800]
I cant get it to work on any model. Anyone encountered similar issue?

ERROR:root:'Conversation' object has no attribute 'conversationSignature'
Traceback (most recent call last):
  File "/app/g4f/gui/server/api.py", line 128, in _create_response_stream
    for chunk in ChatCompletion.create(**kwargs):
  File "/app/g4f/providers/retry_provider.py", line 79, in create_completion
    raise e
  File "/app/g4f/providers/retry_provider.py", line 69, in create_completion
    for token in provider.create_completion(model, messages, stream, **kwargs):
  File "/app/g4f/providers/base_provider.py", line 208, in create_completion
    yield loop.run_until_complete(await_callback(gen.__anext__))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/app/g4f/providers/base_provider.py", line 40, in await_callback
    return await callback()
           ^^^^^^^^^^^^^^^^
  File "/app/g4f/Provider/Bing.py", line 425, in stream_generate
    params={'sec_access_token': conversation.conversationSignature},
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Conversation' object has no attribute 'conversationSignature'

**Comment by AksLolCoding** [comment]
I cannot reproduce but the issue might be that the api is blocked. Check that the following links return json files:
https://[copilot.microsoft.com/turing/conversation/create?bundleVersion=1.1634.3-nodesign2](https://copilot.microsoft.com/turing/conversation/create?bundleVersion=1.1634.3-nodesign2)
https://www.[bing.com/turing/conversation/create?bundleVersion=1.1626.1&adlt=strict&toWww=1&redig=36B06E6B16E147DAAE8DDC588EF9EF69](https://www.bing.com/turing/conversation/create?bundleVersion=1.1626.1&adlt=strict&toWww=1&redig=36B06E6B16E147DAAE8DDC588EF9EF69)
