### ISSUE TITLE
Docker container for arm64 has stopped working for hlohaus789/g4f:0.2.8.1

### ISSUE THREAD

**Issue by George-Seven** [xtekky/gpt4free#1804]
#### Bug description
Docker container `hlohaus789/g4f:0.2.8.1` for `linux/amd64` is working, but for `linux/arm64` it has stopped working.

Older tag `hlohaus789/g4f:0.2.8.0` is still working.

Here is stack trace -

```
2024-04-07 14:56:22,119 INFO Included extra file "/etc/supervisor/conf.d/gui.conf" during parsing
2024-04-07 14:56:22,120 INFO Included extra file "/etc/supervisor/conf.d/selenium.conf" during parsing
2024-04-07 14:56:22,135 INFO RPC interface 'supervisor' initialized
2024-04-07 14:56:22,135 CRIT Server 'unix_http_server' running without any HTTP authentication checking
2024-04-07 14:56:22,136 INFO supervisord started with pid 9
2024-04-07 14:56:23,142 INFO spawned: 'xvfb' with pid 10
2024-04-07 14:56:23,148 INFO spawned: 'vnc' with pid 11
2024-04-07 14:56:23,153 INFO spawned: 'novnc' with pid 12
2024-04-07 14:56:23,165 INFO spawned: 'g4f-api' with pid 13
2024-04-07 14:56:23,170 INFO spawned: 'g4f-gui' with pid 16
2024-04-07 14:56:24,223 INFO success: xvfb entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2024-04-07 14:56:24,225 INFO success: vnc entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2024-04-07 14:56:24,225 INFO success: novnc entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2024-04-07 14:56:24,227 INFO success: g4f-api entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2024-04-07 14:56:24,228 INFO success: g4f-gui entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
Traceback (most recent call last):
Traceback (most recent call last):
  File "<frozen runpy>", line 189, in _run_module_as_main
  File "<frozen runpy>", line 112, in _get_module_details
  File "/app/g4f/__init__.py", line 6, in <module>
  File "<frozen runpy>", line 189, in _run_module_as_main
  File "<frozen runpy>", line 112, in _get_module_details
    from .models import Model
  File "/app/g4f/models.py", line 5, in <module>
  File "/app/g4f/__init__.py", line 6, in <module>
        from .models import Model
  File "/app/g4f/models.py", line 5, in <module>
    from .Provider import RetryProvider, ProviderType
  File "/app/g4f/Provider/__init__.py", line 36, in <module>
from .Provider import RetryProvider, ProviderType
  File "/app/g4f/Provider/__init__.py", line 36, in <module>
    from .Local            import Local
  File "/app/g4f/Provider/Local.py", line 5, in <module>
        from ..locals.provider import LocalProvider
  File "/app/g4f/locals/provider.py", line 5, in <module>
from .Local            import Local    from gpt4all import GPT4All
  File "/home/g4f/.local/lib/python3.11/site-packages/gpt4all/__init__.py", line 1, in <module>

  File "/app/g4f/Provider/Local.py", line 5, in <module>
        from ..locals.provider import LocalProvider
  File "/app/g4f/locals/provider.py", line 5, in <module>
    from . import gpt4all # noqa
    ^^^^^^^^^^^^^^^^^^^^^
  File "/home/g4f/.local/lib/python3.11/site-packages/gpt4all/gpt4all.py", line 6, in <module>
from gpt4all import GPT4All
  File "/home/g4f/.local/lib/python3.11/site-packages/gpt4all/__init__.py", line 1, in <module>
    from . import pyllmodel
  File "/home/g4f/.local/lib/python3.11/site-packages/gpt4all/pyllmodel.py", line 39, in <module>
        llmodel, llama = load_llmodel_library()
                     ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/g4f/.local/lib/python3.11/site-packages/gpt4all/pyllmodel.py", line 32, in load_llmodel_library
from . import gpt4all # noqa    llama_lib = ctypes.CDLL(llama_dir, mode=ctypes.RTLD_GLOBAL)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/ctypes/__init__.py", line 376, in __init__

       self._handle = _dlopen(self._name, mode)
 ^^^^^^^^^^^^^^^^^^^^^
   File "/home/g4f/.local/lib/python3.11/site-packages/gpt4all/gpt4all.py", line 6, in <module>
     from . import pyllmodel
  File "/home/g4f/.local/lib/python3.11/site-packages/gpt4all/pyllmodel.py", line 39, in <module>
     llmodel, llama = load_llmodel_library()
                     ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/g4f/.local/lib/python3.11/site-packages/gpt4all/pyllmodel.py", line 32, in load_llmodel_library
    llama_lib = ctypes.CDLL(llama_dir, mode=ctypes.RTLD_GLOBAL)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: /home/g4f/.local/lib/python3.11/site-packages/gpt4all/llmodel_DO_NOT_MODIFY/build/libllama.so: cannot open shared object file: No such file or directory
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/ctypes/__init__.py", line 376, in __init__
    self._handle = _dlopen(self._name, mode)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: /home/g4f/.local/lib/python3.11/site-packages/gpt4all/llmodel_DO_NOT_MODIFY/build/libllama.so: cannot open shared object file: No such file or directory
2024-04-07 14:56:27,080 WARN exited: g4f-api (exit status 1; not expected)
```

**Comment by George-Seven** [comment]
New update `hlohaus789/g4f:0.2.8.2` has resolved previous error. But now new error appears when selecting a model say `gpt-3.5-turbo` -

```
ERROR:root:
                ---------------------
                Failed to connect to browser
                ---------------------
                One of the causes could be when you are running as root.
                In that case you need to pass no_sandbox=True

Traceback (most recent call last):
  File "/app/g4f/gui/server/api.py", line 128, in _create_response_stream
    for chunk in ChatCompletion.create(**kwargs):
  File "/app/g4f/providers/base_provider.py", line 208, in create_completion
    yield loop.run_until_complete(await_callback(gen.__anext__))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/app/g4f/providers/base_provider.py", line 40, in await_callback
    return await callback()
           ^^^^^^^^^^^^^^^^
  File "/app/g4f/Provider/needs_auth/OpenaiChat.py", line 371, in create_async_generator
    await cls.nodriver_access_token()
  File "/app/g4f/Provider/needs_auth/OpenaiChat.py", line 584, in nodriver_access_token
    browser = await uc.start(user_data_dir=user_data_dir)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/g4f/.local/lib/python3.11/site-packages/nodriver/core/util.py", line 74, in start
    return await Browser.create(config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/g4f/.local/lib/python3.11/site-packages/nodriver/core/browser.py", line 87, in create
    await instance.start()
  File "/home/g4f/.local/lib/python3.11/site-packages/nodriver/core/browser.py", line 343, in start
    raise Exception(
Exception:
                ---------------------
                Failed to connect to browser
                ---------------------
                One of the causes could be when you are running as root.
                In that case you need to pass no_sandbox=True
```

**Comment by hlohaus** [comment]
I have disabled the nodriver in the docker image. However, it is not possible to log in to OpenaiChat in the image without nodriver. The error message has changed, but the issue persists.
