### ISSUE TITLE
PlayWright conflict/crash

### ISSUE THREAD

**Issue by szymcelo** [xtekky/gpt4free#1831]
**Bug description**
Crash when used with playwright

basically import playwright and g4f, call both and it will crash

**Screenshots**

**Environment**
-3.11.0
- (No requests made yet) 

**Additional context**
```
Traceback (most recent call last):
  File "C:\Users\szymt\OneDrive\Dokumenty\szymcelo gens\playwright-issue\venv\Lib\site-packages\playwright\_impl\_transport.py", line 120, in connect
    self._proc = await asyncio.create_subprocess_exec(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\szymt\AppData\Local\Programs\Python\Python311\Lib\asyncio\subprocess.py", line 218, in create_subprocess_exec
    transport, protocol = await loop.subprocess_exec(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\szymt\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 1680, in subprocess_exec
    transport = await self._make_subprocess_transport(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\szymt\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 502, in _make_subprocess_transport
    raise NotImplementedError
NotImplementedError
```
part of an error here

**Comment by hlohaus** [comment]
Please test this update:
 https://github.com/xtekky/gpt4free/pull/1833

**Comment by 1x6** [comment]
I'm still experiencing this on the latest version of g4f.

**Comment by hlohaus** [comment]
Hey, you gotta uninstall duckduckgo-search.  It messed with the event loop too. @1x6

**Comment by 1x6** [comment]
@hlohaus Thanks a lot! No idea why I had that installed but that completely fixed it! Really appreciate your response.
