### ISSUE TITLE
pictures are not generated

### ISSUE THREAD

**Issue by none21323** [xtekky/gpt4free#1839]
from g4f.client import Client

client = Client()
response = client.images.generate(
  model="gemini",
  prompt="a white siamese cat",
)
image_url = response.data[0].url

response:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.10/dist-packages/g4f/client/client.py", line 151, in generate
    image = iter_image_response(response)
  File "/usr/local/lib/python3.10/dist-packages/g4f/client/client.py", line 123, in iter_image_response
    for chunk in list(response):
  File "/usr/local/lib/python3.10/dist-packages/g4f/providers/base_provider.py", line 211, in create_completion
    yield loop.run_until_complete(await_callback(gen.__anext__))
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.10/dist-packages/g4f/providers/base_provider.py", line 40, in await_callback
    return await callback()
  File "/usr/local/lib/python3.10/dist-packages/g4f/Provider/needs_auth/Gemini.py", line 102, in create_async_generator
    raise MissingAuthError('Missing "__Secure-1PSID" cookie')
g4f.errors.MissingAuthError: Missing "__Secure-1PSID" cookie

**Comment by none21323** [comment]
>>> client = Client()
>>> response = client.images.generate(
...   model="gemini",
...   prompt="a white siamese cat",
... )
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.10/dist-packages/g4f/client/client.py", line 151, in generate
    image = iter_image_response(response)
  File "/usr/local/lib/python3.10/dist-packages/g4f/client/client.py", line 123, in iter_image_response
    for chunk in list(response):
  File "/usr/local/lib/python3.10/dist-packages/g4f/providers/base_provider.py", line 211, in create_completion
    yield loop.run_until_complete(await_callback(gen.__anext__))
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.10/dist-packages/g4f/providers/base_provider.py", line 40, in await_callback
    return await callback()
  File "/usr/local/lib/python3.10/dist-packages/g4f/Provider/needs_auth/Gemini.py", line 105, in create_async_generator
    raise RuntimeError("Invalid auth. SNlM0e not found")
RuntimeError: Invalid auth. SNlM0e not found


with cookie

**Comment by fw-real** [comment]
did u fix this issue by any chance until now?

**Comment by mrbuslov** [comment]
@none21323 @fw-real 

You should copy all of your cookies, that start with `__Secure-1PSID`
To find cookies, follow these steps:

- login into the account [gemini.google.com/app](https://gemini.google.com/app)
- F12 > Applications > Cookies > accounts... or gemini...  > Filter (input) > __Secure-1PSID

Example (insert it before `client.images.generate` as pointed in tutorial readme)
```
set_cookies(
    ".google.com",
    {
        "__Secure-1PSID": "g.a000hwiteqQb...0076",
        "__Secure-1PSIDCC": "AKEy...Xl8dc7g",
        "__Secure-1PSIDTS": "sidts-CjEB...SEAA"
    },
)
```

**Comment by fw-real** [comment]
ah i see thanks @mrbuslov for the insight
