### ISSUE TITLE
[Feature request] Productive and functional REST API.

### ISSUE THREAD

**Issue by Hydra566** [xtekky/gpt4free#1852]
**Is your feature request related to the issue? Please describe.**
When working with REST API in multi-threaded mode, a number of problems arise:
1) If you send more than 10-15 requests to the API at the same time, it freezes and sends error 500. You have to restart.
2) Due to the lack of the ability to transfer Proxy in the REST API, after a few minutes of active use I receive a Rate Limit from providers.
3) There is no way to transfer substitute USER AGENT data to the REST API; this would at least partially solve the problems with the Rate Limit.
4) It is not possible to transfer several providers to the REST API, which does not make it possible to immediately use several providers at the same time. If you do not specify a provider, then it takes them automatically, but it does not always do this correctly.

**Describe your desired solution**
I would like the REST API to be fully functional, support a large number of simultaneous requests and be identical in functionality to Python clients, namely:
1) Ability to specify Proxy, Multiple providers and, ideally, User Agent data.
2) Endpoint for generating images.

**Describe alternatives you have considered**
I had only 2 alternatives:
1) Go the long way, learn Python and write your own REST API client.
2) Do it as you please! Namely, just run several API ports, which is what I did by making copies of the run.py file from the API folder and registering different ports. You can now make up to 10 requests on each port stably. BUT, this does not solve the problem with the lack of Proxy and other functions.

@xtekky @hlohaus

**Comment by Hydra566** [comment]
@xtekky

**Comment by hlohaus** [comment]
Hey, 10 requests at once are more than I thought. We could switch to the new AsyncClient in the API for more requests. But please stop using g4f to spam our providers. G4f is for small-sized free projects.

**Comment by Hydra566** [comment]
> Hey, 10 requests at once are more than I thought. We could switch to the new AsyncClient in the API for more requests. But please stop using g4f to spam our providers. G4f is for small-sized free projects.

It would be good if you switched to AsyncClient. I don’t send thousands of requests through G4F. There is simply a need to get several dozen answers quickly. I understand that this solution is not for receiving hundreds and thousands of responses from AI per hour.

The presence of Proxies in the API would also not be superfluous, and not only for me. Since some providers require IP only from certain countries.

But to be honest, based on your G4F there are already commercial solutions that make hundreds of thousands of requests to your providers per day. Yes, most likely the code has been partially rewritten, but the basis is definitely yours and the providers are 90% yours.

**Comment by Hydra566** [comment]
@hlohaus, also why can't I use G4F as a single API endpoint for OpenRouter, Openai, GeminiPro and GigaChat. Since it uses private API keys, I'm not hurting anyone. But it’s convenient to use one endpoint for different providers, and there I can make at least thousands of requests, if the tariff allows it.

But GeminiPro requires a proxy. Since it only works with US IP.

OpenRouter, Openai and GigaChat allow you to send at least hundreds of requests simultaneously using paid plans.

**Comment by hlohaus** [comment]
Good. I changed the client already locally. Maybe i released it today.

**Comment by Hydra566** [comment]
> Good. I changed the client already locally. Maybe i released it today.

Thanks a lot!

**Comment by hlohaus** [comment]
Hi, can you make enough requests now? Maybe I can add a setting for the number of threads for the API.

**Comment by Hydra566** [comment]
> Hi, can you make enough requests now? Maybe I can add a setting for the number of threads for the API.

Thank you! Now I can send a sufficient number of requests.

If you have the time and opportunity, you can add a thread count setting for the API. I think that this will not be superfluous, but not critical, in my opinion.

Is it possible to add a proxy setting via REST API only for providers working with an API key? To avoid the temptation of people to spam reverse API providers. It's just that if I set a general proxy via set G4F_PROXY=http://host:port, GigaChat does not want to work with US proxies, and GeminiPro does not work without them. Well, of course, if it's possible.

**Comment by hlohaus** [comment]
"proxy" has been added as an argument in the API, allowing you to set a proxy for each request.

**Comment by Hydra566** [comment]
> "proxy" has been added as an argument in the API, allowing you to set a proxy for each request. Also you can now set the number of workers.

@hlohaus Thank you very much! The workers are working well, the proxies are installed.

But in GeminiPro, when working through the API, for some reason a problem arises. It works via WEB UI, I tried to make a request via the API to the model: "gemini-pro" provider: "Liaobots", everything is fine too. And when requesting the model: “gemini-pro” from the supplier: “GeminiPro” an error occurs. I specified the API key.

```shell
←[32mINFO←[0m:     127.0.0.1:51994 - "←[1mPOST /v1/chat/completions HTTP/1.1←[0m" ←[91m500 Internal Server Error←[0m
←[31mERROR←[0m:    Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 407, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\uvicorn\middleware\proxy_headers.py", line 69, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\fastapi\applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\middleware\errors.py", line 186, in __call__
    raise exc
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\middleware\errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\middleware\exceptions.py", line 65, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\routing.py", line 756, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\routing.py", line 776, in app
    await route.handle(scope, receive, send)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\routing.py", line 297, in handle
    await self.app(scope, receive, send)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\routing.py", line 77, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\routing.py", line 72, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\fastapi\routing.py", line 278, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\fastapi\routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\g4f\api\__init__.py", line 113, in chat_completions
    return JSONResponse((await response).to_json())
                         ^^^^^^^^^^^^^^
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\g4f\client\async_client.py", line 63, in iter_append_model_and_provider
    async for chunk in response:
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\g4f\client\async_client.py", line 37, in iter_response
    async for chunk in response:
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\g4f\Provider\GeminiPro.py", line 79, in create_async_generator
    raise RuntimeError(f"Response {response.status}: {data['error']['message']}")
RuntimeError: Response 400: Please ensure that multiturn requests ends with a user role or a function response.
```

**Comment by hlohaus** [comment]
Hey, which messages do you send? Gemini pro doesn't support system messages and the last message has to be from a user.

**Comment by Hydra566** [comment]
> Hey, which messages do you send? Gemini pro doesn't support system messages and the last message has to be from a user.

That's it, I found the problem! I formulated my request carelessly. I sent 
```
{"model": "gemini-pro","provider": "GeminiPro","api_key": "AIz***W5o","proxy": "http://38.162.25.104:3128", "temperature": 0.8,"messages": [{"role": "system", "content": ""},{"role": "user", "content": "What is the sky?"}]} 
``` 
, although it is empty, the system parameter is still present.

I need to send like this: 
```
{"model": "gemini-pro","provider": "GeminiPro","api_key": "AIz***W5o","proxy": "http://38.162.25.104: 3128", "temperature": 0.8,"messages": [{"role": "user", "content": "What is the sky?"}]}
``` 
 Here's how it works.

Sorry for the inconvenience, the error occurred due to my carelessness!
