### ISSUE TITLE
Image Generation. Invalid auth. SNlM0e not found

### ISSUE THREAD

**Issue by mrbuslov** [xtekky/gpt4free#1867]
**Bug description**
When I entered my cookie in set_cookies (I copied it from dev console on [gemini.google.com/app](gemini.google.com/app) website), it still raises error

ex.
```
from g4f.client import Client
from g4f.cookies import set_cookies


set_cookies(
    ".google.com",
    {
        "__Secure-1PSID": "g.a000hwi...0076"
    },
)


client = Client()
response = client.images.generate(
    model="gemini",
    prompt="a white siamese cat",
)
image_url = response.data[0].url

```

**Environment**
- python version - 3.11.6

**Additional context**
Full traceback:
```
Traceback (most recent call last):
  File "/home/dmitry/Desktop/g4f-snippet.py", line 14, in <module>
    response = client.images.generate(
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dmitry/.pyenv/versions/3.11.6/lib/python3.11/site-packages/g4f/client/client.py", line 150, in generate
    image = iter_image_response(response)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dmitry/.pyenv/versions/3.11.6/lib/python3.11/site-packages/g4f/client/client.py", line 122, in iter_image_response
    for chunk in list(response):
                 ^^^^^^^^^^^^^^
  File "/home/dmitry/.pyenv/versions/3.11.6/lib/python3.11/site-packages/g4f/providers/base_provider.py", line 211, in create_completion
    yield loop.run_until_complete(await_callback(gen.__anext__))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dmitry/.pyenv/versions/3.11.6/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/dmitry/.pyenv/versions/3.11.6/lib/python3.11/site-packages/g4f/providers/base_provider.py", line 40, in await_callback
    return await callback()
           ^^^^^^^^^^^^^^^^
  File "/home/dmitry/.pyenv/versions/3.11.6/lib/python3.11/site-packages/g4f/Provider/needs_auth/Gemini.py", line 105, in create_async_generator
    raise RuntimeError("Invalid auth. SNlM0e not found")
RuntimeError: Invalid auth. SNlM0e not found
```

**Comment by mrbuslov** [comment]
You should copy all of your cookies, that start with `__Secure-1PSID`
To find cookies, follow these steps:

- login into the account [gemini.google.com/app](https://gemini.google.com/app)
- F12 > Applications > Cookies > accounts... or gemini...  > Filter (input) > __Secure-1PSID

Example (insert it before `client.images.generate`)
```
set_cookies(
    ".google.com",
    {
        "__Secure-1PSID": "g.a000hwiteqQb...0076",
        "__Secure-1PSIDCC": "AKEy...Xl8dc7g",
        "__Secure-1PSIDTS": "sidts-CjEB...SEAA"
    },
)
```
