### ISSUE TITLE
metadata-generation-failed

### ISSUE THREAD

**Issue by AbelEthan** [xtekky/gpt4free#187]
deepin@deepin-PC:~/Desktop/gpt4free-main$ pip install --no-cache-dir -r requirements.txt
Defaulting to user installation because normal site-packages is not writeable
Looking in indexes: http://pypi.douban.com/simple
Collecting websocket-client (from -r requirements.txt (line 1))
  Downloading http://pypi.doubanio.com/packages/6d/9a/6c793729c9d48fcca155ce55e4dfafacffb7fb52a62e3ae2198846c31af6/websocket_client-1.5.1-py3-none-any.whl (55 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 55.9/55.9 kB 926.6 kB/s eta 0:00:00
Requirement already satisfied: requests in /home/deepin/.local/lib/python3.10/site-packages (from -r requirements.txt (line 2)) (2.28.2)
Collecting tls-client (from -r requirements.txt (line 3))
  Downloading http://pypi.doubanio.com/packages/f1/6e/71e44f668658c22f7be486bc4bd3ed49d9c2bc1398a7cb6b218c0a1f641d/tls_client-0.2-py3-none-any.whl (35.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 35.2/35.2 MB 29.5 MB/s eta 0:00:00
Collecting pypasser (from -r requirements.txt (line 4))
  Downloading http://pypi.doubanio.com/packages/dc/18/405c919c0398ecdb9ff5fa62a6c092751d7c6d5865191633967f95ded134/PyPasser-0.0.5.tar.gz (10 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [62 lines of output]
      running dist_info
      creating /tmp/pip-modern-metadata-34hz5lyc/PyPasser.egg-info
      writing /tmp/pip-modern-metadata-34hz5lyc/PyPasser.egg-info/PKG-INFO
      writing dependency_links to /tmp/pip-modern-metadata-34hz5lyc/PyPasser.egg-info/dependency_links.txt
      writing requirements to /tmp/pip-modern-metadata-34hz5lyc/PyPasser.egg-info/requires.txt
      writing top-level names to /tmp/pip-modern-metadata-34hz5lyc/PyPasser.egg-info/top_level.txt
      writing manifest file '/tmp/pip-modern-metadata-34hz5lyc/PyPasser.egg-info/SOURCES.txt'
      reading manifest file '/tmp/pip-modern-metadata-34hz5lyc/PyPasser.egg-info/SOURCES.txt'
      adding license file 'LICENSE'
      writing manifest file '/tmp/pip-modern-metadata-34hz5lyc/PyPasser.egg-info/SOURCES.txt'
      creating '/tmp/pip-modern-metadata-34hz5lyc/PyPasser-0.0.5.dist-info'
      Traceback (most recent call last):
        File "/usr/local/python3/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/usr/local/python3/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/usr/local/python3/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 149, in prepare_metadata_for_build_wheel
          return hook(metadata_directory, config_settings)
        File "/tmp/pip-build-env-pl1ghata/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 377, in prepare_metadata_for_build_wheel
          self.run_setup()
        File "/tmp/pip-build-env-pl1ghata/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 484, in run_setup
          super(_BuildMetaLegacyBackend,
        File "/tmp/pip-build-env-pl1ghata/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 335, in run_setup
          exec(code, locals())
        File "<string>", line 15, in <module>
        File "/tmp/pip-build-env-pl1ghata/overlay/lib/python3.10/site-packages/setuptools/__init__.py", line 108, in setup
          return distutils.core.setup(**attrs)
        File "/tmp/pip-build-env-pl1ghata/overlay/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/tmp/pip-build-env-pl1ghata/overlay/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/tmp/pip-build-env-pl1ghata/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/tmp/pip-build-env-pl1ghata/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 1221, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-pl1ghata/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-pl1ghata/overlay/lib/python3.10/site-packages/setuptools/command/dist_info.py", line 103, in run
          bdist_wheel = self.get_finalized_command('bdist_wheel')
        File "/tmp/pip-build-env-pl1ghata/overlay/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 304, in get_finalized_command
          cmd_obj = self.distribution.get_command_obj(command, create)
        File "/tmp/pip-build-env-pl1ghata/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 860, in get_command_obj
          klass = self.get_command_class(command)
        File "/tmp/pip-build-env-pl1ghata/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 966, in get_command_class
          self.cmdclass[command] = cmdclass = ep.load()
        File "/usr/local/python3/lib/python3.10/importlib/metadata/__init__.py", line 171, in load
          module = import_module(match.group('module'))
        File "/usr/local/python3/lib/python3.10/importlib/__init__.py", line 126, in import_module
          return _bootstrap._gcd_import(name[level:], package, level)
        File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
        File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
        File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
        File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
        File "<frozen importlib._bootstrap_external>", line 883, in exec_module
        File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
        File "/tmp/pip-build-env-pl1ghata/overlay/lib/python3.10/site-packages/wheel/bdist_wheel.py", line 28, in <module>
          from .macosx_libfile import calculate_macosx_platform_tag
        File "/tmp/pip-build-env-pl1ghata/overlay/lib/python3.10/site-packages/wheel/macosx_libfile.py", line 43, in <module>
          import ctypes
        File "/usr/local/python3/lib/python3.10/ctypes/__init__.py", line 8, in <module>
          from _ctypes import Union, Structure, Array
      ModuleNotFoundError: No module named '_ctypes'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by 9fo** [comment]
What OS are u using?

**Comment by xtekky** [comment]
i can you just copy paste this into chatgpt ? I mean cmon

**Comment by AbelEthan** [comment]
使用的deepin

**Comment by AbelEthan** [comment]
> 

deepin used

**Comment by AbelEthan** [comment]
> 我可以将其复制粘贴到 chatgpt 中吗？我的意思是

deepin used

**Comment by AbelEthan** [comment]
> 我可以将其复制粘贴到 chatgpt 中吗？我的意思是

of course

**Comment by AbelEthan** [comment]
> What OS are u using?

deepin used
