### ISSUE TITLE
An error occured: Liaobots: ResponseStatusError: Response 500: Error

### ISSUE THREAD

**Issue by ainp** [xtekky/gpt4free#1895]
GPT4    -----    Liaobots

![截屏2024-04-26 17 02 05](https://github.com/xtekky/gpt4free/assets/9693302/91e51cac-d794-456d-bdb8-d6fa101f4896)

docker compose deploy

log:
--------------------------------------------------------------

    main()
  File "/app/g4f/cli.py", line 25, in main
    run_api_args(args)
  File "/app/g4f/cli.py", line 41, in run_api_args
    g4f.api.run_api(
  File "/app/g4f/api/__init__.py", line 158, in run_api
    print(f'Starting server... [g4f v-{g4f.version.utils.current_version}]' + (" (debug)" if debug else ""))
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/functools.py", line 1001, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/app/g4f/version.py", line 89, in current_version
    raise VersionNotFoundError("Version not found")
g4f.errors.VersionNotFoundError: Version not found
2024-04-26 09:10:18,205 WARN exited: g4f-api (exit status 1; not expected)
2024-04-26 09:10:19,209 INFO spawned: 'g4f-api' with pid 426
2024-04-26 09:10:20,211 INFO success: g4f-api entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/app/g4f/cli.py", line 49, in <module>
    main()
  File "/app/g4f/cli.py", line 25, in main
    run_api_args(args)
  File "/app/g4f/cli.py", line 41, in run_api_args
    g4f.api.run_api(
  File "/app/g4f/api/__init__.py", line 158, in run_api
    print(f'Starting server... [g4f v-{g4f.version.utils.current_version}]' + (" (debug)" if debug else ""))
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/functools.py", line 1001, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/app/g4f/version.py", line 89, in current_version
    raise VersionNotFoundError("Version not found")
g4f.errors.VersionNotFoundError: Version not found
2024-04-26 09:10:22,512 WARN exited: g4f-api (exit status 1; not expected)
2024-04-26 09:10:23,516 INFO spawned: 'g4f-api' with pid 428
2024-04-26 09:10:24,518 INFO success: g4f-api entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/app/g4f/cli.py", line 49, in <module>
    main()
  File "/app/g4f/cli.py", line 25, in main
    run_api_args(args)
  File "/app/g4f/cli.py", line 41, in run_api_args
    g4f.api.run_api(
  File "/app/g4f/api/__init__.py", line 158, in run_api
    print(f'Starting server... [g4f v-{g4f.version.utils.current_version}]' + (" (debug)" if debug else ""))
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/functools.py", line 1001, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/app/g4f/version.py", line 89, in current_version
    raise VersionNotFoundError("Version not found")
g4f.errors.VersionNotFoundError: Version not found
2024-04-26 09:10:25,825 WARN exited: g4f-api (exit status 1; not expected)
2024-04-26 09:10:26,828 INFO spawned: 'g4f-api' with pid 430
2024-04-26 09:10:27,831 INFO success: g4f-api entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/app/g4f/cli.py", line 49, in <module>
    main()
  File "/app/g4f/cli.py", line 25, in main
    run_api_args(args)
  File "/app/g4f/cli.py", line 41, in run_api_args
    g4f.api.run_api(
  File "/app/g4f/api/__init__.py", line 158, in run_api
    print(f'Starting server... [g4f v-{g4f.version.utils.current_version}]' + (" (debug)" if debug else ""))
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/functools.py", line 1001, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/app/g4f/version.py", line 89, in current_version
    raise VersionNotFoundError("Version not found")
g4f.errors.VersionNotFoundError: Version not found
2024-04-26 09:10:29,128 WARN exited: g4f-api (exit status 1; not expected)
2024-04-26 09:10:30,130 INFO spawned: 'g4f-api' with pid 432
2024-04-26 09:10:31,133 INFO success: g4f-api entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/app/g4f/cli.py", line 49, in <module>
    main()
  File "/app/g4f/cli.py", line 25, in main
    run_api_args(args)
  File "/app/g4f/cli.py", line 41, in run_api_args
    g4f.api.run_api(
  File "/app/g4f/api/__init__.py", line 158, in run_api
    print(f'Starting server... [g4f v-{g4f.version.utils.current_version}]' + (" (debug)" if debug else ""))
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/functools.py", line 1001, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/app/g4f/version.py", line 89, in current_version
    raise VersionNotFoundError("Version not found")
g4f.errors.VersionNotFoundError: Version not found
2024-04-26 09:10:32,458 WARN exited: g4f-api (exit status 1; not expected)
2024-04-26 09:10:33,461 INFO spawned: 'g4f-api' with pid 434

**Comment by Anonymous6598** [comment]
Currently, Liaobots provider site might have an internal issues. Try using deepinfra. It's almost the same.

**Comment by Anonymous6598** [comment]
Or it might ran out of tokens. Try using it tomorrow, therefore amount of tokens might restart.

**Comment by ainp** [comment]
Thanks!!!

**Comment by Anonymous6598** [comment]
Your welcome
