### ISSUE TITLE
Response 401: {"detail":"Unauthorized"} when using OpenaiChat provider

### ISSUE THREAD

**Issue by PsychoThinker** [xtekky/gpt4free#1918]
# Issue

When trying to run the `OpenaiChat` provider, it fails authorize using my har file and keeps throwing `ResponseStatusError: Response 401: {"detail":"Unauthorized"}` despite placing the respective har file within the current working directory under `./har_and_cookies/chat.openai.com.har` (I also tried to save the cookies in this directory exported in json format using the Cookie-Editor extension). I am using gpt4free's module within clean python virtual environment on my local machine (`pip install g4f[all] nodriver`). I tried to perform an analogous operation from the web interface running from the console (`python -m g4f.cli gui -port 8080 -debug`), but the end result is the same. Am I missing something (of course I have an active ChatGPT Plus account) ?

# Code

```python
from g4f.client import Client
from g4f.Provider import OpenaiChat

client = Client()
response = client.chat.completions.create(
    model="gpt-3.5-turbo",
    provider=OpenaiChat,
    messages=[{"role": "user", "content": """Hello World"""}]
)
print(response.choices[0].message.content)
```

# Environment

System: Linux
Python: 3.12.2
g4f: 0.3.0.7

# Stacktrace
```
Traceback (most recent call last):
  File "/g4f/main.py", line 5, in <module>
    response = client.chat.completions.create(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.12/site-packages/g4f/client/client.py", line 114, in create
    return response if stream else next(response)
                                   ^^^^^^^^^^^^^^
  File "/venv/lib/python3.12/site-packages/g4f/client/client.py", line 53, in iter_append_model_and_provider
    for chunk in response:
  File "/venv/lib/python3.12/site-packages/g4f/client/client.py", line 28, in iter_response
    for idx, chunk in enumerate(response):
  File "/venv/lib/python3.12/site-packages/g4f/providers/base_provider.py", line 216, in create_completion
    yield loop.run_until_complete(await_callback(gen.__anext__))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/asyncio/base_events.py", line 685, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/venv/lib/python3.12/site-packages/g4f/providers/base_provider.py", line 45, in await_callback
    return await callback()
           ^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.12/site-packages/g4f/Provider/needs_auth/OpenaiChat.py", line 419, in create_async_generator
    await raise_for_status(response)
  File "/venv/lib/python3.12/site-packages/g4f/requests/raise_for_status.py", line 28, in raise_for_status_async
    raise ResponseStatusError(f"Response {response.status}: {message}")
g4f.errors.ResponseStatusError: Response 401: {"detail":"Unauthorized"}
```

**Comment by PsychoThinker** [comment]
I have also tried moving the .har file and .json to the current directory, but the error still appears. Also, I don't think it's a matter of the har file not being read, because when I run the web gui from the console, I see the message:

```
Read .har file: ./har_and_cookies/chat.openai.com.har
Read cookie file: ./har_and_cookies/cookies.json
Cookies added: 4 from .openai.com
Cookies added: 9 from chat.openai.com
Cookies added: 3 from .chat.openai.com
```

And yet the authorization error continues to appear.

If this is my mistake, or my environment, I would be very, very grateful if someone could suggest what else I could change.

**Comment by xtekky** [comment]
Make sure your ip is from an authorized country, you can find the list here: https://pastebin.com/UK0gT9cn

**Comment by martinezart87** [comment]
IP form Poland, not working. Added cookies and har.

`ERROR:root:Response 401: {"detail":"Unauthorized"}
Traceback (most recent call last):
  File "/app/g4f/gui/server/api.py", line 174, in _create_response_stream
    for chunk in ChatCompletion.create(**kwargs):
  File "/app/g4f/providers/base_provider.py", line 216, in create_completion
    yield loop.run_until_complete(await_callback(gen.__anext__))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/app/g4f/providers/base_provider.py", line 45, in await_callback
    return await callback()
           ^^^^^^^^^^^^^^^^
  File "/app/g4f/Provider/needs_auth/OpenaiChat.py", line 419, in create_async_generator
    await raise_for_status(response)
  File "/app/g4f/requests/raise_for_status.py", line 28, in raise_for_status_async
    raise ResponseStatusError(f"Response {response.status}: {message}")
g4f.errors.ResponseStatusError: Response 401: {"detail":"Unauthorized"}`

**Comment by PsychoThinker** [comment]
I think this issue can be closed
