### ISSUE TITLE
Cloudflare detected for providers: You, OpenaiChat

### ISSUE THREAD

**Issue by PsychoThinker** [xtekky/gpt4free#1922]
# Issue

When trying to run the `OpenaiChat` or `You` provider, it fails authorize using my har file and keeps throwing `CloudflareError: Response 403: Cloudflare detected` (despite placing the respective har file within the directory: `./har_and_cookies`).

Does this type of error mean that it will no longer be possible to use these providers?

# Code

```python
import g4f
from g4f.client import Client
from g4f.Provider import OpenaiChat, You
from g4f.models import default

g4f.debug.logging = True

client = Client()
response = client.chat.completions.create(
    model=default,
    provider=You,
    messages=[{"role": "user", "content": "Hello"}]
)
print(response.choices[0].message.content)
```

# Environment

System: Ubuntu 
Python: 3.11
g4f: 0.3.0.8

# Stacktrace

```
Traceback (most recent call last):
  File "/g4f/main.py", line 10, in <module>
    response = client.chat.completions.create(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/g4f/.venv/lib/python3.11/site-packages/g4f/client/client.py", line 114, in create
    return response if stream else next(response)
                                   ^^^^^^^^^^^^^^
  File "/g4f/.venv/lib/python3.11/site-packages/g4f/client/client.py", line 53, in iter_append_model_and_provider
    for chunk in response:
  File "/g4f/.venv/lib/python3.11/site-packages/g4f/client/client.py", line 28, in iter_response
    for idx, chunk in enumerate(response):
  File "/g4f/.venv/lib/python3.11/site-packages/g4f/providers/base_provider.py", line 216, in create_completion
    yield loop.run_until_complete(await_callback(gen.__anext__))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/g4f/.venv/lib/python3.11/site-packages/g4f/providers/base_provider.py", line 45, in await_callback
    return await callback()
           ^^^^^^^^^^^^^^^^
  File "/g4f/.venv/lib/python3.11/site-packages/g4f/Provider/You.py", line 104, in create_async_generator
    await raise_for_status(response)
  File "/g4f/.venv/lib/python3.11/site-packages/g4f/requests/raise_for_status.py", line 24, in raise_for_status_async
    raise CloudflareError(f"Response {response.status}: Cloudflare detected")
g4f.requests.raise_for_status.CloudflareError: Response 403: Cloudflare detected
```

**Comment by PsychoThinker** [comment]
Ok, never mind - I've just realised that it's a matter of me performing operations that have been flagged for captcha checking.

Changing the IP address solved the problem
