### ISSUE TITLE
The You.com provider does not work in the API

### ISSUE THREAD

**Issue by Hydra566** [xtekky/gpt4free#1924]
@hlohaus @xtekky When working through the WEB UI, everything works, the browser opens, and receives telemetry. Everything is working normally.

When requesting through the API, it gives an error and the browser does not open.

```shell
Using You provider and gpt-4-turbo model
No telemetry in .har files found
Getting telemetry_id for you.com with nodriver
←[32mINFO←[0m:     127.0.0.1:53514 - "←[1mPOST /v1/chat/completions HTTP/1.1←[0m" ←[91m500 Internal Server Error←[0m
←[31mERROR←[0m:    Exception in ASGI application
  + Exception Group Traceback (most recent call last):
  |   File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\_utils.py", line 87, in collapse_excgroups
  |     yield
  |   File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\middleware\base.py", line 190, in __call__
  |     async with anyio.create_task_group() as task_group:
  |   File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\anyio\_backends\_asyncio.py", line 678, in __aexit__
  |     raise BaseExceptionGroup(
  | ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
  +-+---------------- 1 ----------------
    | Traceback (most recent call last):
    |   File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 407, in run_asgi
    |     result = await app(  # type: ignore[func-returns-value]
    |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\uvicorn\middleware\proxy_headers.py", line 69, in __call__
    |     return await self.app(scope, receive, send)
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\fastapi\applications.py", line 1054, in __call__
    |     await super().__call__(scope, receive, send)
    |   File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\applications.py", line 123, in __call__
    |     await self.middleware_stack(scope, receive, send)
    |   File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\middleware\errors.py", line 186, in __call__
    |     raise exc
    |   File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\middleware\errors.py", line 164, in __call__
    |     await self.app(scope, receive, _send)
    |   File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\middleware\base.py", line 189, in __call__
    |     with collapse_excgroups():
    |   File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\contextlib.py", line 158, in __exit__
    |     self.gen.throw(value)
    |   File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\_utils.py", line 93, in collapse_excgroups
    |     raise exc
    |   File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\middleware\base.py", line 191, in __call__
    |     response = await self.dispatch_func(request, call_next)
    |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\g4f\api\__init__.py", line 90, in authorization
    |     return await call_next(request)
    |            ^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\middleware\base.py", line 165, in call_next
    |     raise app_exc
    |   File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\middleware\base.py", line 151, in coro
    |     await self.app(scope, receive_or_disconnect, send_no_error)
    |   File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\middleware\exceptions.py", line 65, in __call__
    |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
    |   File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\_exception_handler.py", line 64, in wrapped_app
    |     raise exc
    |   File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    |     await app(scope, receive, sender)
    |   File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\routing.py", line 756, in __call__
    |     await self.middleware_stack(scope, receive, send)
    |   File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\routing.py", line 776, in app
    |     await route.handle(scope, receive, send)
    |   File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\routing.py", line 297, in handle
    |     await self.app(scope, receive, send)
    |   File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\routing.py", line 77, in app
    |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
    |   File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\_exception_handler.py", line 64, in wrapped_app
    |     raise exc
    |   File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    |     await app(scope, receive, sender)
    |   File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\routing.py", line 72, in app
    |     response = await func(request)
    |                ^^^^^^^^^^^^^^^^^^^
    |   File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\fastapi\routing.py", line 278, in app
    |     raw_response = await run_endpoint_function(
    |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\fastapi\routing.py", line 191, in run_endpoint_function
    |     return await dependant.call(**values)
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\g4f\api\__init__.py", line 163, in chat_completions
    |     return JSONResponse((await response).to_json())
    |                          ^^^^^^^^^^^^^^
    |   File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\g4f\client\async_client.py", line 63, in iter_append_model_and_provider
    |     async for chunk in response:
    |   File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\g4f\client\async_client.py", line 37, in iter_response
    |     async for chunk in response:
    |   File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\g4f\Provider\You.py", line 79, in create_async_generator
    |     cookies = await cls.get_cookies(session) if chat_mode != "default" else None
    |               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\g4f\Provider\You.py", line 159, in get_cookies
    |     cls._cookies = await cls.create_cookies(client)
    |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\g4f\Provider\You.py", line 186, in create_cookies
    |     cls._telemetry_ids = await get_telemetry_ids()
    |                          ^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\g4f\Provider\you\har_file.py", line 90, in get_telemetry_ids
    |     browser = await start()
    |               ^^^^^^^^^^^^^
    |   File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\nodriver\core\util.py", line 74, in start
    |     return await Browser.create(config)
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\nodriver\core\browser.py", line 87, in create
    |     await instance.start()
    |   File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\nodriver\core\browser.py", line 312, in start
    |     await asyncio.create_subprocess_exec(
    |   File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\asyncio\subprocess.py", line 224, in create_subprocess_exec
    |     transport, protocol = await loop.subprocess_exec(
    |                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 1744, in subprocess_exec
    |     transport = await self._make_subprocess_transport(
    |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 524, in _make_subprocess_transport
    |     raise NotImplementedError
    | NotImplementedError
    +------------------------------------

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 407, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\uvicorn\middleware\proxy_headers.py", line 69, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\fastapi\applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\middleware\errors.py", line 186, in __call__
    raise exc
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\middleware\errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\middleware\base.py", line 189, in __call__
    with collapse_excgroups():
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\contextlib.py", line 158, in __exit__
    self.gen.throw(value)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\_utils.py", line 93, in collapse_excgroups
    raise exc
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\middleware\base.py", line 191, in __call__
    response = await self.dispatch_func(request, call_next)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\g4f\api\__init__.py", line 90, in authorization
    return await call_next(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\middleware\base.py", line 165, in call_next
    raise app_exc
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\middleware\base.py", line 151, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\middleware\exceptions.py", line 65, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\routing.py", line 756, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\routing.py", line 776, in app
    await route.handle(scope, receive, send)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\routing.py", line 297, in handle
    await self.app(scope, receive, send)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\routing.py", line 77, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\routing.py", line 72, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\fastapi\routing.py", line 278, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\fastapi\routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\g4f\api\__init__.py", line 163, in chat_completions
    return JSONResponse((await response).to_json())
                         ^^^^^^^^^^^^^^
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\g4f\client\async_client.py", line 63, in iter_append_model_and_provider
    async for chunk in response:
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\g4f\client\async_client.py", line 37, in iter_response
    async for chunk in response:
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\g4f\Provider\You.py", line 79, in create_async_generator
    cookies = await cls.get_cookies(session) if chat_mode != "default" else None
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\g4f\Provider\You.py", line 159, in get_cookies
    cls._cookies = await cls.create_cookies(client)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\g4f\Provider\You.py", line 186, in create_cookies
    cls._telemetry_ids = await get_telemetry_ids()
                         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\g4f\Provider\you\har_file.py", line 90, in get_telemetry_ids
    browser = await start()
              ^^^^^^^^^^^^^
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\nodriver\core\util.py", line 74, in start
    return await Browser.create(config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\nodriver\core\browser.py", line 87, in create
    await instance.start()
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\nodriver\core\browser.py", line 312, in start
    await asyncio.create_subprocess_exec(
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\asyncio\subprocess.py", line 224, in create_subprocess_exec
    transport, protocol = await loop.subprocess_exec(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 1744, in subprocess_exec
    transport = await self._make_subprocess_transport(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 524, in _make_subprocess_transport
    raise NotImplementedError
NotImplementedError

```

**Comment by Hydra566** [comment]
I downgraded to version 0.3.0.7, everything works, I downgraded to version 0.3.0.6, it also works. Installed 0.3.0.8 again, error. This error appeared precisely from version 0.3.0.8.

**Comment by hlohaus** [comment]
Hey, the error messages are from nodriver. Did you change the event loop? Nodriver doesn't support that. Also, the duckduckgo-search changes the event loop, so you can't use them together. Oh, and ignore the warning from curl_cffi.

**Comment by Hydra566** [comment]
> Hey, the error messages are from nodriver. Did you change the event loop? Nodriver doesn't support that. Also, the duckduckgo-search changes the event loop, so you can't use them together. Oh, and ignore the warning from curl_cffi.

Hello. I don't use the duckduckgo-search web search, and I haven't changed the event loop in any way. I'm using a completely stock version from GitHub, and just sending requests via REST API.

Updated to the latest version 0.3.0.10.

If you run it like this: g4f api
Everything works.

If I run it like this: g4f api --ignore-cookie-files --workers 5 (or) g4f api --ignore-cookie-files (or) g4f api --workers 5
It gives an error. Is this a limitation of Nodriver? Or maybe it's because I'm using Windows? When I have time, I’ll test it on Ubuntu.

**Comment by hlohaus** [comment]
You don't need workers. If you need workers, you can't use nodriver. This isn't a bug that needs to be fixed. Just don't use workers.

**Comment by Hydra566** [comment]
> You don't need workers. If you need workers, you can't use nodriver. This isn't a bug that needs to be fixed. Just don't use workers.

Understood! Thanks for clarifying!
