### ISSUE TITLE
OpenAI style Api on port 1337 doesn't work

### ISSUE THREAD

**Issue by Wu-jiyan** [xtekky/gpt4free#1928]
**Bug description**
I deployed this project with docker on a Hong Kong server. When I updated the image to 0.3.10. The api on port 1337 cannot work porperly. Though ai can answer on the site on port 8080. (My English isn't very good😢)

**Environment**
- docker image version: 0.3.10
- location: Hong Kong

**Additional context**
```
ERROR:root:RetryProvider failed:
Bing: ValueError: Can't patch loop of type <class 'uvloop.Loop'>
Liaobots: ValueError: Can't patch loop of type <class 'uvloop.Loop'>
Traceback (most recent call last):
  File "/app/g4f/api/__init__.py", line 165, in streaming
    async for chunk in response:
  File "/app/g4f/client/async_client.py", line 63, in iter_append_model_and_provider
    async for chunk in response:
  File "/app/g4f/client/async_client.py", line 37, in iter_response
    async for chunk in response:
  File "/app/g4f/client/helper.py", line 46, in cast_iter_async
    for chunk in iter:
  File "/app/g4f/providers/retry_provider.py", line 95, in create_completion
    raise_exceptions(exceptions)
  File "/app/g4f/providers/retry_provider.py", line 231, in raise_exceptions
    raise RetryProviderError("RetryProvider failed:\n" + "\n".join([
g4f.errors.RetryProviderError: RetryProvider failed:
Bing: ValueError: Can't patch loop of type <class 'uvloop.Loop'>
Liaobots: ValueError: Can't patch loop of type <class 'uvloop.Loop'>
INFO:     154.64.252.2:44614 - "POST /v1/chat/completions HTTP/1.1" 200 OK
ERROR:root:RetryProvider failed:
Liaobots: ValueError: Can't patch loop of type <class 'uvloop.Loop'>
Bing: ValueError: Can't patch loop of type <class 'uvloop.Loop'>
Traceback (most recent call last):
  File "/app/g4f/api/__init__.py", line 165, in streaming
    async for chunk in response:
  File "/app/g4f/client/async_client.py", line 63, in iter_append_model_and_provider
    async for chunk in response:
  File "/app/g4f/client/async_client.py", line 37, in iter_response
    async for chunk in response:
  File "/app/g4f/client/helper.py", line 46, in cast_iter_async
    for chunk in iter:
  File "/app/g4f/providers/retry_provider.py", line 95, in create_completion
    raise_exceptions(exceptions)
  File "/app/g4f/providers/retry_provider.py", line 231, in raise_exceptions
    raise RetryProviderError("RetryProvider failed:\n" + "\n".join([
g4f.errors.RetryProviderError: RetryProvider failed:
Liaobots: ValueError: Can't patch loop of type <class 'uvloop.Loop'>
Bing: ValueError: Can't patch loop of type <class 'uvloop.Loop'>
```

**Comment by Mahesh0253** [comment]
I'm also facing same problem. v0.3.0.8 is working fine.

**Comment by sharemen** [comment]
i have the same problem

**Comment by asiryan** [comment]
I have the same problem too!

**Comment by 1xiongyuwen1** [comment]
I have the same problem too!

**Comment by cloudygtosis** [comment]
Me too ,Have u solved this problem?

**Comment by AHiXilTOr** [comment]
loop='asyncio'

**Comment by hlohaus** [comment]
I fixed the uvloop issue.
