### ISSUE TITLE
BingCreateImages error

### ISSUE THREAD

**Issue by ufoptg** [xtekky/gpt4free#1973]
**Bug description**
after updating to latest g4f i get this error 
An unexpected error occurred: 'BingCreateImages' object has no attribute 'name'

**Comment by hlohaus** [comment]
Do you have stacktrace for this error?

**Comment by ufoptg** [comment]
> Do you have stacktrace for this error?

ill show you

**Comment by ufoptg** [comment]
`05/19/2024, 17:36:21 | ⛧Nim⛧pyLogs [INFO] : 'BingCreateImages' object has no attribute '__name__'
Traceback (most recent call last):
  File "addons/chatgpt.py", line 135, in handle_bigen
    response = await imgclient.images.generate(prompt=query, model="dall-e-3")
  File "/home/loki/ts/.ult/lib/python3.9/site-packages/g4f/client/async_client.py", line 224, in generate
    response = create_image(
  File "/home/loki/ts/.ult/lib/python3.9/site-packages/g4f/client/async_client.py", line 187, in create_image
    if provider.__name__ == "You":
AttributeError: 'BingCreateImages' object has no attribute '__name__'

File: chatgpt.py, Line 135`

**Comment by ufoptg** [comment]
This is what i get when trying to use Normal Client 
```
👩‍💻 Ⲉⳳⲁⳑ (in 0.672ms)
from g4f.client import Client

client = Client()
response = client.images.generate(
    model="dall-e-3",
    prompt="a white siamese cat",
)
image_url = response.data[0].url

p(image_url)
 

👨‍💻 Ⲟυⲧⲣυⲧ: 
Traceback (most recent call last):
  File "/home/loki/ts/Nimbus/plugins/devtools.py", line 267, in _
    value = await aexec(cmd, event)
  File "/home/loki/ts/Nimbus/plugins/devtools.py", line 351, in aexec
    return await locals()["__aexec"](event, event.client)
  File "<string>", line 10, in __aexec
  File "/home/loki/ts/.ult/lib/python3.9/site-packages/g4f/client/client.py", line 150, in generate
    response = list(provider.create(prompt))
AttributeError: 'BingCreateImages' object has no attribute 'create'
```

and this what happens with AsyncClient

```
👩‍💻 Ⲉⳳⲁⳑ (in 0.396ms)
from g4f.client import AsyncClient

client = AsyncClient()
response = await client.images.generate(
    model="dall-e-3",
    prompt="a white siamese cat",
)
image_url = response.data[0].url

p(image_url)
 

👨‍💻 Ⲟυⲧⲣυⲧ: 
Traceback (most recent call last):
  File "/home/loki/ts/Nimbus/plugins/devtools.py", line 267, in _
    value = await aexec(cmd, event)
  File "/home/loki/ts/Nimbus/plugins/devtools.py", line 351, in aexec
    return await locals()["__aexec"](event, event.client)
  File "<string>", line 10, in __aexec
  File "/home/loki/ts/.ult/lib/python3.9/site-packages/g4f/client/async_client.py", line 224, in generate
    response = create_image(
  File "/home/loki/ts/.ult/lib/python3.9/site-packages/g4f/client/async_client.py", line 187, in create_image
    if provider.__name__ == "You":
AttributeError: 'BingCreateImages' object has no attribute '__name__'
```

**Comment by ufoptg** [comment]
works fine when i downgrade back to v3.1.0

**Comment by hlohaus** [comment]
Hello, I fixed this problem in the latest version of the code.

AttributeError: 'BingCreateImages' object has no attribute '__name__'

**Comment by ufoptg** [comment]
beautiful! :) Great job
