### ISSUE TITLE
You Provider (Vision doesn't work)

### ISSUE THREAD

**Issue by noneherel** [xtekky/gpt4free#1992]
when i try to use You vision AI i got an error (g4f.errors.ResponseStatusError: Response 500: {"error":"Failed to upload"}) i will give more details, This is my Code:

```
from g4f.client import Client
from g4f.Provider import You
client_vision = Client(provider=You,image_provider=You)
response = client_vision.chat.completions.create(
    model=You.default_vision_model,
    messages=[{"role": "user", "content": 'what is in the picture?'}],
    image=open(f"./hello.jpg", "rb")
)
print(response.choices[0].message.content)
```

and this is the error i got:

```
Traceback (most recent call last):
  File "d:\VisualStudio\AI_tests\vision.py", line 35, in <module>
    response = client_vision.chat.completions.create(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python312\Lib\site-packages\g4f\client\client.py", line 114, in create
    return response if stream else next(response)
                                   ^^^^^^^^^^^^^^
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python312\Lib\site-packages\g4f\client\client.py", line 53, in iter_append_model_and_provider
    for chunk in response:
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python312\Lib\site-packages\g4f\client\client.py", line 28, in iter_response
    for idx, chunk in enumerate(response):
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python312\Lib\site-packages\g4f\providers\base_provider.py", line 216, in create_completion
    yield loop.run_until_complete(await_callback(gen.__anext__))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python312\Lib\site-packages\g4f\providers\base_provider.py", line 45, in await_callback
    return await callback()
           ^^^^^^^^^^^^^^^^
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python312\Lib\site-packages\g4f\Provider\You.py", line 83, in create_async_generator
    upload_file = await cls.upload_file(
                  ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python312\Lib\site-packages\g4f\Provider\You.py", line 154, in upload_file
    await raise_for_status(response)
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python312\Lib\site-packages\g4f\requests\raise_for_status.py", line 28, in raise_for_status_async
    raise ResponseStatusError(f"Response {response.status}: {message}")
g4f.errors.ResponseStatusError: Response 500: {"error":"Failed to upload"}
successfully removed temp profile C:\Users\XXX\AppData\Local\Temp\uc_jt2m51mi
```

**Comment by fw-real** [comment]
this is still an issue and got the same in bing as well
