### ISSUE TITLE
OpenAi Provider Error (add api_key and I've added it already)

### ISSUE THREAD

**Issue by noneherel** [xtekky/gpt4free#1993]
this is my code:

```
from g4f.client import Client as client_ai
from g4f.Provider import OpenaiChat

client = client_ai(provider=OpenaiChat)
response = client.chat.completions.create(
    api_key='sk-proj-XvUaNpdorLWIbFWhq0ctT...etc',
    model="gpt-4-turbo",
    messages=[{"role": "user", "content": 'how are you?'}],
)
mess= response.choices[0].message.content
print(mess)
```

this is the error i got:

```
Traceback (most recent call last):
  File "d:\VisualStudio\AI_tests\chatting.py", line 19, in <module>
    response = client.chat.completions.create(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python312\Lib\site-packages\g4f\client\client.py", line 114, in create
    return response if stream else next(response)
                                   ^^^^^^^^^^^^^^
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python312\Lib\site-packages\g4f\client\client.py", line 53, in iter_append_model_and_provider
    for chunk in response:
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python312\Lib\site-packages\g4f\client\client.py", line 28, in iter_response
    for idx, chunk in enumerate(response):
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python312\Lib\site-packages\g4f\providers\base_provider.py", line 216, in create_completion  
    yield loop.run_until_complete(await_callback(gen.__anext__))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python312\Lib\site-packages\g4f\providers\base_provider.py", line 45, in await_callback
    return await callback()
           ^^^^^^^^^^^^^^^^
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python312\Lib\site-packages\g4f\Provider\needs_auth\OpenaiChat.py", line 379, in create_async_generator
    cls.default_model = cls.get_model(await cls.get_default_model(session, cls._headers))
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python312\Lib\site-packages\g4f\Provider\needs_auth\OpenaiChat.py", line 199, in get_default_model
    raise MissingAuthError('Add a "api_key" or a .har file' if cls._api_key is None else "Invalid api key")
g4f.errors.MissingAuthError: Add a "api_key" or a .har file
```

**Comment by Anuragmukati** [comment]
`from g4f.client import Client as client_ai
from g4f.Provider import OpenaiChat

# Initialize the client with the provider and API key
client = client_ai(provider=OpenaiChat, api_key='sk-proj-XvUaNpdorLWIbFWhq0ctT...etc')

# Create a completion
response = client.chat.completions.create(
    model="gpt-4-turbo",
    messages=[{"role": "user", "content": 'how are you?'}],
)

# Extract and print the message content
mess = response.choices[0].message.content
print(mess)
`


try this... Maybe it works

**Comment by hlohaus** [comment]
Try this:

client = client_ai(provider=Openai, api_key='sk-proj-XvUaNpdorLWIbFWhq0ctT...etc')

Not: OpenaiChat

**Comment by noneherel** [comment]
> Try this:
> 
> client = client_ai(provider=Openai, api_key='sk-proj-XvUaNpdorLWIbFWhq0ctT...etc')
> 
> Not: OpenaiChat

i tried this and i got this error:
```
g4f.errors.ResponseStatusError: Response 404: {
    "error": {
        "message": "The model `gpt-4-turbo` does not exist or you do not have access to it.",
        "type": "invalid_request_error",
        "param": null,
        "code": "model_not_found"
    }
}
```

any model i put in models it gives me this error, and then i tried this

client = client_ai(provider=Openai, api_key='sk-proj-qhL1QHdCQV7XyQW0kL...')
response = client.chat.completions.create(
    model="gpt-4",
    messages=[{"role": "user", "content": 'how are you?'}],
)
without (turbo) and i got this error:
`curl_cffi.requests.errors.RequestsError: Failed to perform, curl: (6) Could not resolve host: api.openai.com. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.`

**Comment by noneherel** [comment]
> `from g4f.client import Client as client_ai from g4f.Provider import OpenaiChat
> 
> # Initialize the client with the provider and API key
> client = client_ai(provider=OpenaiChat, api_key='sk-proj-XvUaNpdorLWIbFWhq0ctT...etc')
> 
> # Create a completion
> response = client.chat.completions.create( model="gpt-4-turbo", messages=[{"role": "user", "content": 'how are you?'}], )
> 
> # Extract and print the message content
> mess = response.choices[0].message.content print(mess) `
> 
> try this... Maybe it works

thank you for your reply but it didn't work )':

**Comment by mak448a** [comment]
Sorry to bother you, but I'm having the same error. I grabbed my token from https://chatgpt.com/api/auth/session and stuck in my access token like this:
```python
response = await g4f.ChatCompletion.create_async(
        model=g4f.models.gpt_35_turbo,
        provider=g4f.Provider.OpenaiChat,
        messages=messages,
        access_token=chatgpt_key_taken_from_chatgpt,
        stream=False
)
```
and then I got the error.
`g4f.errors.MissingAuthError: Add a "api_key" or a .har file`

Am I doing something wrong @hlohaus?

**Comment by dayajiji** [comment]
Same error 

_MissingAuthError('Add a "api_key" or a .har file' if cls._api_key is None else "Invalid api key")
g4f.errors.MissingAuthError: Add a "api_key" or a .har file_

**Comment by dayajiji** [comment]
Same 

`MissingAuthError('Add a "api_key" or a .har file' if cls._api_key is None else "Invalid api key")
g4f.errors.MissingAuthError: Add a "api_key" or a .har file`

**Comment by mak448a** [comment]
Stop closing this stuff bot. bump.

**Comment by mak448a** [comment]
BUMP!!!

**Comment by iG8R** [comment]
up

**Comment by mak448a** [comment]
Bump

**Comment by mak448a** [comment]
Bumping this issue because this bot keeps wanting to close.

**Comment by mak448a** [comment]
Stop it @github-actions.

**Comment by mak448a** [comment]
I give up. I'm probably going to stop bumping this issue.
