### ISSUE TITLE
GeminiProChat is broken.

### ISSUE THREAD

**Issue by gamelist1990** [xtekky/gpt4free#2025]
GeminiProChat.py not working https://geminiprochat.com/

**Comment by Zedai00** [comment]
Hi, What do you mean by that can you explain more

**Comment by gamelist1990** [comment]
It seems to be sending a request to the URL of https://gemini-chatbot-sigma.vercel.app, but it has an error and it doesn't work.

**Comment by Zedai00** [comment]
Is it solved yet? if not can you do a step by step guide on how to produce the error and more details if possible

**Comment by gamelist1990** [comment]
I can't reproduce it because I'm currently on the train, so I'll send it again later.

**Comment by gamelist1990** [comment]
Sure, here is the English translation of your text:

"When I run this code:
`from g4f.client import Client
from g4f.Provider import GeminiProChat
import g4f
import g4f.debug
g4f.debug.logging = True

client = Client(
    provider=GeminiProChat
)
response = client.chat.completions.create(
    model=g4f.models.default,
    messages=[{"role": "user", "content": "Hello"}],
)
print(response.choices[0].message.content)`  I get the following error message: `PS C:\Users\PC_User\Desktop\test> & c:/Users/PC_User/Desktop/test/.venv/Scripts/python.exe c:/Users/PC_User/Desktop/test/test.py
Failed to check g4f version: Version not found
Using GeminiProChat provider
Traceback (most recent call last):
  File "c:\Users\PC_User\Desktop\test\test.py", line 11, in <module>
    response = client.chat.completions.create(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\PC_User\Desktop\test\g4f\client\client.py", line 118, in create
    return response if stream else next(response)
                                   ^^^^^^^^^^^^^^
  File "c:\Users\PC_User\Desktop\test\g4f\client\client.py", line 57, in iter_append_model_and_provider
    for chunk in response:
  File "c:\Users\PC_User\Desktop\test\g4f\client\client.py", line 29, in iter_response
    for idx, chunk in enumerate(response):
  File "c:\Users\PC_User\Desktop\test\g4f\providers\base_provider.py", line 223, in create_completion
    yield loop.run_until_complete(await_callback(gen.__anext__))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\asyncio\base_events.py", line 685, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "c:\Users\PC_User\Desktop\test\g4f\providers\base_provider.py", line 52, in await_callback
    return await callback()
           ^^^^^^^^^^^^^^^^
  File "c:\Users\PC_User\Desktop\test\g4f\Provider\GeminiProChat.py", line 56, in create_async_generator
    await raise_for_status(response)
  File "c:\Users\PC_User\Desktop\test\g4f\requests\raise_for_status.py", line 28, in raise_for_status_async  
    raise ResponseStatusError(f"Response {response.status}: {message}")
g4f.errors.ResponseStatusError: Response 500: {"error":{"code":"Error","message":"API Key not found. Please pass a valid API key. [{\"@type\":\"type.googleapis.com/google.rpc.ErrorInfo\",\"reason\":\"API_KEY_INVALID\",\"domain\":\"googleapis.com\",\"metadata\":{\"service\":\"generativelanguage.googleapis.com\"}}]"}}
PS C:\Users\PC_User\Desktop\test>
` is returned."

**Comment by gamelist1990** [comment]
Running this code: from g4f.client import Client
from g4f.Provider import GeminiProChat
import g4f.debug
import g4f.debug
g4f.debug.logging = True


client = Client(
    provider=GeminiProChat
    )
response = client.chat.completions.create(
    model=g4f.models.default,.
    messages=[{“role”: “user”, “content”: “Hello”}],.
)
print(response.choices[0].message.content) error message is:  PS C:\Users\PC_User\Desktop\test> & c:/Users/PC_User/Desktop/test/.venv/Scripts/python.exe c:/Users/PC_User/Desktop/test/test.py
Failed to check g4f version: Version not found
Using GeminiProChat provider
Traceback (most recent call last):
  File "c:\Users\PC_User\Desktop\test\test.py", line 11, in <module>
    response = client.chat.completions.create(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\PC_User\Desktop\test\g4f\client\client.py", line 118, in create
    return response if stream else next(response)
                                   ^^^^^^^^^^^^^^
  File "c:\Users\PC_User\Desktop\test\g4f\client\client.py", line 57, in iter_append_model_and_provider
    for chunk in response:
  File "c:\Users\PC_User\Desktop\test\g4f\client\client.py", line 29, in iter_response
    for idx, chunk in enumerate(response):
  File "c:\Users\PC_User\Desktop\test\g4f\providers\base_provider.py", line 223, in create_completion
    yield loop.run_until_complete(await_callback(gen.__anext__))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\asyncio\base_events.py", line 685, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "c:\Users\PC_User\Desktop\test\g4f\providers\base_provider.py", line 52, in await_callback
    return await callback()
           ^^^^^^^^^^^^^^^^
  File "c:\Users\PC_User\Desktop\test\g4f\Provider\GeminiProChat.py", line 56, in create_async_generator
    await raise_for_status(response)
  File "c:\Users\PC_User\Desktop\test\g4f\requests\raise_for_status.py", line 28, in raise_for_status_async  
    raise ResponseStatusError(f"Response {response.status}: {message}")
g4f.errors.ResponseStatusError: Response 500: {"error":{"code":"Error","message":"API Key not found. Please pass a valid API key. [{\"@type\":\"type.googleapis.com/google.rpc.ErrorInfo\",\"reason\":\"API_KEY_INVALID\",\"domain\":\"googleapis.com\",\"metadata\":{\"service\":\"generativelanguage.googleapis.com\"}}]"}}
PS C:\Users\PC_User\Desktop\test> returned

**Comment by Zedai00** [comment]
After looking into the geminiprochat source code 
```py
    url = "https://gemini-chatbot-sigma.vercel.app"
```
they are using this url when I went there it was not working looked into their github they have change theri url 
repo:- https://github.com/expertbeacon/gemini-chatbot
url:- https://www.chatgemini.net/
Ill do a pull request to fix this
