### ISSUE TITLE
Image Generation error

### ISSUE THREAD

**Issue by BDXBB** [xtekky/gpt4free#2038]
**Image Generation error **

PS C:\Users\SILVER> & "D:/Program Files/Python312/python.exe" "c:/Users/SILVER/Desktop/import requests.py"
Traceback (most recent call last):
  File "c:\Users\SILVER\Desktop\import requests.py", line 4, in <module>
    response = client.images.generate(
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Program Files\Python312\Lib\site-packages\g4f\client\client.py", line 158, in generate
    image = iter_image_response(response)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Program Files\Python312\Lib\site-packages\g4f\client\client.py", line 127, in iter_image_response
    for chunk in list(response):
                 ^^^^^^^^^^^^^^
  File "D:\Program Files\Python312\Lib\site-packages\g4f\providers\base_provider.py", line 223, in create_completion
    yield loop.run_until_complete(await_callback(gen.__anext__))
  File "D:\Program Files\Python312\Lib\asyncio\base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "D:\Program Files\Python312\Lib\site-packages\g4f\providers\base_provider.py", line 52, in await_callback
    return await callback()
           ^^^^^^^^^^^^^^^^
  File "D:\Program Files\Python312\Lib\site-packages\g4f\Provider\needs_auth\Gemini.py", line 149, in create_async_generator
    raise MissingAuthError('Missing "__Secure-1PSID" cookie')
g4f.errors.MissingAuthError: Missing "__Secure-1PSID" cookie
PS C:\Users\SILVER> & "D:/Program Files/Python312/python.exe" "c:/Users/SILVER/Desktop/import requests.py"
Traceback (most recent call last):
  File "c:\Users\SILVER\Desktop\import requests.py", line 4, in <module>
    response = client.images.generate(
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Program Files\Python312\Lib\site-packages\g4f\client\client.py", line 158, in generate
    image = iter_image_response(response)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Program Files\Python312\Lib\site-packages\g4f\client\client.py", line 127, in iter_image_response
    for chunk in list(response):
                 ^^^^^^^^^^^^^^
  File "D:\Program Files\Python312\Lib\site-packages\g4f\providers\base_provider.py", line 223, in create_completion
    yield loop.run_until_complete(await_callback(gen.__anext__))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Program Files\Python312\Lib\asyncio\base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "D:\Program Files\Python312\Lib\site-packages\g4f\providers\base_provider.py", line 52, in await_callback
    return await callback()
           ^^^^^^^^^^^^^^^^
  File "D:\Program Files\Python312\Lib\site-packages\g4f\Provider\needs_auth\Gemini.py", line 149, in create_async_generator
    raise MissingAuthError('Missing "__Secure-1PSID" cookie')
g4f.errors.MissingAuthError: Missing "__Secure-1PSID" cookie
PS C:\Users\SILVER>

**Comment by TheFirstNoob** [comment]
you didnt set on your env.
__Secure-1PSID cookie

**Comment by TheFirstNoob** [comment]
`set_cookies(".yoursite.com", {
    "__Secure-1PSID": str(os.getenv("GEMINI_COOKIE"))
    })`
    
    in .env create GEMIMI_COOKIE=
    And set __Secure-1PSID (Press F12 on site and copy PSID)
    
    Example code find here: https://github.com/Zero6992/chatGPT-discord-bot/blob/main/auto_login/AutoLogin.py
    Docs how to get cookie find here: https://github.com/xtekky/gpt4free?tab=readme-ov-file#cookies
