### ISSUE TITLE
You.com with my cookies

### ISSUE THREAD

**Issue by Allamaris0** [xtekky/gpt4free#2045]
Hello. Can I use gpt4free with my own you.com account?

In params there no support for cookies:

```
g4f.Provider.You supports: (
    model: str,
    messages: Messages,
    stream: bool = True,
    image: ImageType = None,
    image_name: str = None,
    proxy: str = None,
    timeout: int = 240,
    chat_mode: str = "default",
)
```

I create you.com.har but it shows `ERROR:root:No telemetry in .har files found` and it gets telemetry_id with nodriver.
When I create .har with my cookies then I got error:
```
Read .har file: C:\Users\Em\PycharmProjects\freegpt\har_and_cookies\you.har
Traceback (most recent call last):
  File "C:\Users\Em\PycharmProjects\freegpt\you-unlimited.py", line 10, in <module>
    read_cookie_files(cookies_dir)
  File "C:\Users\Em\PycharmProjects\freegpt\venv\lib\site-packages\g4f\cookies.py", line 134, in read_cookie_files
    for v in harFile['log']['entries']:
TypeError: list indices must be integers or slices, not str
```

**Comment by iwannet** [comment]
yeah good idea, maybe use some code from here https://github.com/Archeb/YOUChat_Proxy

**Comment by iwannet** [comment]
Bruh, closed ?

**Comment by AppSolves** [comment]
Same issue for me, are there any updates on this?
