### ISSUE TITLE
Response:500 error with the huggingface provider.

### ISSUE THREAD

**Issue by gamelist1990** [xtekky/gpt4free#2053]
![image](https://github.com/xtekky/gpt4free/assets/118247906/10fa6d5d-1966-4602-84fa-c74373d367b9)
   

Error message:INFO:werkzeug:127.0.0.1 - - [11/Jun/2024 00:28:28] "POST /backend-api/v2/conversation HTTP/1.1" 200 -
ERROR:root:Response 500: 
Traceback (most recent call last):
  File "C:\Users\PC\Music\api-1\g4f\gui\server\api.py", line 177, in _create_response_stream
    for chunk in ChatCompletion.create(**kwargs):
  File "C:\Users\PC\Music\api-1\g4f\providers\base_provider.py", line 223, in create_completion
    yield loop.run_until_complete(await_callback(gen.__anext__))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PC\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\PC\Music\api-1\g4f\providers\base_provider.py", line 52, in await_callback
    return await callback()
           ^^^^^^^^^^^^^^^^
  File "C:\Users\PC\Music\api-1\g4f\Provider\HuggingChat.py", line 99, in create_async_generator
    await raise_for_status(response)
  File "C:\Users\PC\Music\api-1\g4f\requests\raise_for_status.py", line 28, in raise_for_status_async
    raise ResponseStatusError(f"Response {response.status}: {message}")
g4f.errors.ResponseStatusError: Response 500:

「It was working fine until a few days ago, but about the day before yesterday it started returning Response 500.」

**Comment by gamelist1990** [comment]
INFO:root:Successfully sent a new message in the conversation. ID: 666729eb2f7e93042d9ad7ee
INFO:root:<ClientResponse(https://huggingface.co/chat/conversation/666729eb2f7e93042d9ad7ee) [500 Internal Server Error]>

When I access that URL, I get a blank NewChat, so I looked at the _data.json and saw {
                    “id”: 3, 
　　　　　　“title”: 4, 
　　　　　　“id”: 3,
　　　　　　 “title”: 4
                    “title”: 4,.
                    “model”: 5, “updatedAt”: 6, “id”: 3, “title”: 4, { “id”: 3
                    “updatedAt”: 6, “assistantId”: -1, -2, -3, -4, -5, -6
                    “assistantId”: -1,.
                    “avatarHash”: 7
                },.
                “66672bca5d051c97bdc7b18a”, “new Chat”.
                “New Chat”,.
                “CohereForAI/c4ai-command-r-plus”, “New Chat”.
                [
                    “Date”,.
                    “2024-06-10T16:37:30.118Z”
                ],.
                null, 

was of the form

**Comment by xtekky** [comment]
I will take a look soon.

**Comment by gamelist1990** [comment]
It's helpful.

**Comment by MRGRD56** [comment]
@xtekky

I'm having the same issue ;(  

![image](https://github.com/xtekky/gpt4free/assets/35491968/7afaf19b-4af2-4703-8bf3-c4c02eb511fc)

I've tried it with a cookies file and a .har file, the error is the same.  
The HuggingChat provider just refuses to work

When I go to HuggingChat itself, I can see a new chat created, with no messages there

I'm running in Docker on Ubuntu if it matters

```
Using HuggingChat provider and CohereForAI/c4ai-command-r-plus model
INFO:werkzeug:192.168.80.1 - - [22/Jun/2024 16:31:48] "POST /backend-api/v2/conversation HTTP/1.1" 200 -
ERROR:root:Response 500: 
Traceback (most recent call last):
  File "/app/g4f/gui/server/api.py", line 177, in _create_response_stream
    for chunk in ChatCompletion.create(**kwargs):
  File "/app/g4f/providers/base_provider.py", line 223, in create_completion
    yield loop.run_until_complete(await_callback(gen.__anext__))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/app/g4f/providers/base_provider.py", line 52, in await_callback
    return await callback()
           ^^^^^^^^^^^^^^^^
  File "/app/g4f/Provider/HuggingChat.py", line 99, in create_async_generator
    await raise_for_status(response)
  File "/app/g4f/requests/raise_for_status.py", line 28, in raise_for_status_async
    raise ResponseStatusError(f"Response {response.status}: {message}")
g4f.errors.ResponseStatusError: Response 500:
```

Maybe it'd be better to reopen the issue at least?
