### ISSUE TITLE
Error "KeyError: 'conversationId'" when using CohereForAI/c4ai-command-r-plus model in HuggingChat 

### ISSUE THREAD

**Issue by restartxx** [xtekky/gpt4free#2221]
### **Bug description**
I am using the latest version of **g4f** installed via **pip**. When I try to use the **Command r+** model provided by **HuggingChat** (CohereForAI/c4ai-command-r-plus), I get an error related to `conversationId`. This occurs both when using the API and the GUI interface.

Up until a week ago, the model was working normally. This error started appearing recently, and the template is still available and working directly in HuggingChat. .

Here are the steps I followed and the error that appears:

1. I installed the latest version of **g4f** via pip (`pip install g4f`).

2. I tried to use the **Command r+** model provided by **HuggingChat**.

3. I got the error below, indicating a problem with the `conversationId`.

 **Full log:**
 ``` CohereForAI/c4ai-command-r-plus ERROR:root:RetryProvider failed: HuggingChat: KeyError: 'conversationId' Traceback (most recent call last): File "/usr/lib/python3.11/site-packages/g4f/api/__init__.py", line 171, in streaming async for chunk in response: File "/usr/lib/py thon3.11/site-packages/g4f/client/async_client.py", line 71, in iter_append_model_and_provider async for chunk in response: File "/usr/lib/python3.11/site-packages/g4f/client/async_client.py", line 42, in iter_response async for chunk in response: File  "/usr/lib/python3.11/site-packages/g4f/providers/retry_provider.py", line 143, in create_async_generator
raise_exceptions(exceptions)
File "/usr/lib/python3.11/site-packages/g4f/providers/retry_provider.py", line 324, in raise_exceptions
raise RetryProviderError("RetryProvider failed:\n" + "\n".join([
g4f.errors.RetryProviderError: RetryProvider failed:
HuggingChat: KeyError: 'conversationId'
```

### **Environment**
- **Python version**: 3.11
- **Location**: I am not in a country blocked by Cloudflare, and the model works directly in HuggingChat without any problems.

**Comment by TheFirstNoob** [comment]
Hey! Thanks for report this!
I test this problem and can Confirmed!

**Comment by TheFirstNoob** [comment]
@restartxx quick fix if needed:

Open `g4f/Provider/HuggingChat.py`

Change line: ```response = session.get(f'https://huggingface.co/chat/conversation/{conversationId}/__data.json?x-sveltekit-invalidated=01',)```

Invalidated=01 to Invalidated=11

Works fine!

**Comment by restartxx** [comment]
> @restartxx quick fix if needed:
> 
> Open `g4f/Provider/HuggingChat.py`
> 
> Change line: `response = session.get(f'https://huggingface.co/chat/conversation/{conversationId}/__data.json?x-sveltekit-invalidated=01',)`
> 
> Invalidated=01 to Invalidated=11
> 
> Works fine!

Thank you very much! But... huh, it's still not working for me. Same error. 🥲🤡

**Comment by TheFirstNoob** [comment]
@restartxx `HuggingChat.py` with this fix

```
from __future__ import annotations

import json, requests, re

from curl_cffi import requests as cf_reqs
from ..typing import CreateResult, Messages
from .base_provider import ProviderModelMixin, AbstractProvider
from .helper import format_prompt

class HuggingChat(AbstractProvider, ProviderModelMixin):
    url = "https://huggingface.co/chat"
    working = True
    supports_stream = True
    default_model = "meta-llama/Meta-Llama-3.1-70B-Instruct"
    models = [
        'meta-llama/Meta-Llama-3.1-70B-Instruct',
        'CohereForAI/c4ai-command-r-plus-08-2024',
        '01-ai/Yi-1.5-34B-Chat',
        'mistralai/Mistral-7B-Instruct-v0.3',
    ]
    
    model_aliases = {
        "llama-3.1-70b": "meta-llama/Meta-Llama-3.1-70B-Instruct",
        "command-r-plus": "CohereForAI/c4ai-command-r-plus-08-2024",
        "yi-1.5-34b": "01-ai/Yi-1.5-34B-Chat",
        "mistral-7b": "mistralai/Mistral-7B-Instruct-v0.3",
    }

    @classmethod
    def get_model(cls, model: str) -> str:
        if model in cls.models:
            return model
        elif model in cls.model_aliases:
            return cls.model_aliases[model]
        else:
            return cls.default_model
            
    @classmethod
    def create_completion(
        cls,
        model: str,
        messages: Messages,
        stream: bool,
        **kwargs
    ) -> CreateResult:
        model = cls.get_model(model)
        
        if model in cls.models:
            session = cf_reqs.Session()
            session.headers = {
                'accept': '*/*',
                'accept-language': 'en',
                'cache-control': 'no-cache',
                'origin': 'https://huggingface.co',
                'pragma': 'no-cache',
                'priority': 'u=1, i',
                'referer': 'https://huggingface.co/chat/',
                'sec-ch-ua': '"Not)A;Brand";v="99", "Google Chrome";v="127", "Chromium";v="127"',
                'sec-ch-ua-mobile': '?0',
                'sec-ch-ua-platform': '"macOS"',
                'sec-fetch-dest': 'empty',
                'sec-fetch-mode': 'cors',
                'sec-fetch-site': 'same-origin',
                'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36',
            }

            print(model)
            json_data = {
                'model': model,
            }

            response = session.post('https://huggingface.co/chat/conversation', json=json_data)
            conversationId = response.json()['conversationId']
            print(response.json())

            response = session.get(f'https://huggingface.co/chat/conversation/{conversationId}/__data.json?x-sveltekit-invalidated=11',)

            data: list = (response.json())["nodes"][1]["data"]
            keys: list[int] = data[data[0]["messages"]]
            message_keys: dict = data[keys[0]]
            messageId: str = data[message_keys["id"]]

            settings = {
                "inputs": format_prompt(messages),
                "id": messageId,
                "is_retry": False,
                "is_continue": False,
                "web_search": False,
                "tools": []
            }

            headers = {
                'accept': '*/*',
                'accept-language': 'en',
                'cache-control': 'no-cache',
                'origin': 'https://huggingface.co',
                'pragma': 'no-cache',
                'priority': 'u=1, i',
                'referer': f'https://huggingface.co/chat/conversation/{conversationId}',
                'sec-ch-ua': '"Not)A;Brand";v="99", "Google Chrome";v="127", "Chromium";v="127"',
                'sec-ch-ua-mobile': '?0',
                'sec-ch-ua-platform': '"macOS"',
                'sec-fetch-dest': 'empty',
                'sec-fetch-mode': 'cors',
                'sec-fetch-site': 'same-origin',
                'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36',
            }

            files = {
                'data': (None, json.dumps(settings, separators=(',', ':'))),
            }

            response = requests.post(f'https://huggingface.co/chat/conversation/{conversationId}',
                cookies=session.cookies,
                headers=headers,
                files=files,
            )

            first_token = True
            for line in response.iter_lines():
                line = json.loads(line)
                
                if "type" not in line:
                    raise RuntimeError(f"Response: {line}")
                
                elif line["type"] == "stream":
                    token = line["token"]
                    if first_token:
                        token = token.lstrip().replace('\u0000', '')
                        first_token = False
                    else:
                        token = token.replace('\u0000', '')

                    yield token
                
                elif line["type"] == "finalAnswer":
                    break
```

Log working: 
```
INFO:src.log:thefirstnoob : /ask [888 * 888] в (Direct Message with thefirstnoob)
Using RetryProvider provider and command-r-plus model
Using HuggingChat provider
CohereForAI/c4ai-command-r-plus-08-2024
{'conversationId': '66e32ffdeb7441750d276d9e'}

answer: 888 * 888 equals 788544.
```

**Comment by restartxx** [comment]
Again, thank you very much! @TheFirstNoob 
Just tested it here using:
``` 
from g4f.client import Client

client = Client()

chat_completion = client.chat.completions.create(model="command-r+",
    messages=[{"role": "user", "content": "Hello"}], stream=True)

for completion in chat_completion:
    print(completion.choices[0].delta.content or "", end="", flush=True)
```
and it is indeed working. But in the gui and api it is not. That's why when I was testing it before I was still seeing the error. Did you test it using the api? # @

**Comment by TheFirstNoob** [comment]
Nope my mistake. I test your code and work fine:

tested code:
```
from g4f.client import Client

client = Client()
response = client.chat.completions.create(
    model="command-r+",
    messages=[{"role": "user", "content": "Hello"}],
)
print(response.choices[0].message.content)
```

`
![image](https://github.com/user-attachments/assets/ffff7341-565c-4685-abfe-ae1724e150ea)
`

**Comment by restartxx** [comment]
Nice!
Did you manage to the model work in the g4f API?

**Comment by TheFirstNoob** [comment]
I didnt use g4f api key directly. Only use provider calling. If i remember g4f api site doesn`t work now... maybe i mistake.

Thats now updated for latest (waiting merge) but its actual.
```
providers = {
            "gpt-3.5-turbo": RetryProvider([FreeChatgpt, FreeNetfly, Bixin123, Nexra, TwitterBio], shuffle=False),
            "gpt-4": RetryProvider([Chatgpt4Online, Nexra, Binjie, FreeNetfly, AiChats, You, Liaobots], shuffle=False),
            "gpt-4-turbo": RetryProvider([Nexra, Bixin123, You, Liaobots], shuffle=False),
            "gpt-4o-mini": RetryProvider([Pizzagpt, AiChatOnline, ChatgptFree, CodeNews, You, FreeNetfly, Koala, MagickPen, DDG, Liaobots], shuffle=False),
            "gpt-4o": RetryProvider([Chatgpt4o, LiteIcoding, AiChatOnline, You, Liaobots], shuffle=False),
            "claude-3-haiku": RetryProvider([DDG, Liaobots], shuffle=False),
            "blackbox": RetryProvider([Blackbox], shuffle=False),
            "gemini-pro": RetryProvider([ChatGot, Liaobots], shuffle=False),
            "gemini-flash": RetryProvider([Blackbox, Liaobots], shuffle=False),
            "gemma-2b": RetryProvider([ReplicateHome], shuffle=False),
            "command-r-plus": RetryProvider([HuggingChat, HuggingFace], shuffle=False),
            "llama-3.1-70b": RetryProvider([HuggingChat, HuggingFace, Blackbox, DeepInfra, FreeGpt, TeachAnything, Free2GPT, Snova, DDG], shuffle=False),
            "llama-3.1-405b": RetryProvider([Blackbox, Snova], shuffle=False),
            "llama-3.1-sonar-large-128k-online": RetryProvider([PerplexityLabs], shuffle=False),
            "llama-3.1-sonar-large-128k-chat": RetryProvider([PerplexityLabs], shuffle=False),
            "pi": RetryProvider([Pi], shuffle=False),
            "mixtral-8x7b": RetryProvider([HuggingChat, HuggingFace, ReplicateHome, TwitterBio, DeepInfra, DDG], shuffle=False),
            "mistral-7b": RetryProvider([HuggingChat, HuggingFace, DeepInfra], shuffle=False),
            "yi-1.5-34b": RetryProvider([HuggingChat, HuggingFace], shuffle=False),
            "SparkDesk-v1.1": RetryProvider([FreeChatgpt], shuffle=False),
        }
```

**Comment by restartxx** [comment]
Got it. I use the API through the docker I'm hosting (just using ```g4f api``` to open api on port 1337 ),  other models are working, only command-r is not. If you don't use this API, that's fine. But if you could take a look if you're free, I owe you one.

Thank you very much!

**Comment by restartxx** [comment]
Everything fixed in the last release. Thank you very much! ❤️
