### ISSUE TITLE
Forefront Error

### ISSUE THREAD

**Issue by liaosunny123** [xtekky/gpt4free#223]
Use Forefront to generate a completion, but I get error:  
```
Traceback (most recent call last):
  File "forefront.py", line 4, in <module>
    token = forefront.Account.create(logging=True)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "forefront\__init__.py", line 42, in create
    trace_token = response.json()['response']['id']
                  ~~~~~~~~~~~~~~~^^^^^^^^^^^^
KeyError: 'response'
```
I catch the error and find that the remote server send back:  
```
{'errors': [{'message': 'Too many requests from this machine. Please try again in a bit.', 'code': 'too_many_requests'}]}
```

**Comment by youyou-pm10** [comment]
That's right,I catch the same error.Except that Xtekky can make the api using a bigger company!

**Comment by xtekky** [comment]
got takedown request from them
