### ISSUE TITLE
Gemini model doesn't return an URI

### ISSUE THREAD

**Issue by Halo333X** [xtekky/gpt4free#2264]
It works fine, if i'm in gemini, it loads correctly the prompt, but when i'm waiting for a response, i'm always getting this

ERROR:root:Error in synchronous image generation: Invalid data URI image.
Traceback (most recent call last):
  File "C:\Users\sandr\Desktop\AI\AI\gemi.py", line 28, in <module>
    response = client.images.generate(
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sandr\AppData\Local\Programs\Python\Python312\Lib\site-packages\g4f\client\client.py", line 209, in generate
    result = loop.run_until_complete(self.async_generate(prompt, model, **kwargs))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sandr\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\sandr\AppData\Local\Programs\Python\Python312\Lib\site-packages\g4f\client\client.py", line 242, in async_generate
    return self._process_image_response(image_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sandr\AppData\Local\Programs\Python\Python312\Lib\site-packages\g4f\client\client.py", line 267, in _process_image_response
    image = to_image(image_data)
            ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sandr\AppData\Local\Programs\Python\Python312\Lib\site-packages\g4f\image.py", line 40, in to_image
    is_data_uri_an_image(image)
  File "C:\Users\sandr\AppData\Local\Programs\Python\Python312\Lib\site-packages\g4f\image.py", line 89, in is_data_uri_an_image
    raise ValueError("Invalid data URI image.")
ValueError: Invalid data URI image.

**Comment by BinhPQ2** [comment]
Can you post your code?
