### ISSUE TITLE
import error, looks like it can't resolve the path of a module in another folder

### ISSUE THREAD

**Issue by RosarioDiBartolo** [xtekky/gpt4free#2271]
Traceback (most recent call last):
  File "C:\Users\Rosario\Desktop\customgpt\main.py", line 1, in <module>
    from g4f.client import Client
  File "C:\Users\Rosario\Desktop\customgpt\.venv\Lib\site-packages\g4f\__init__.py", line 6, in <module>
    from .models import Model
  File "C:\Users\Rosario\Desktop\customgpt\.venv\Lib\site-packages\g4f\models.py", line 5, in <module>
    from .Provider import IterListProvider, ProviderType
  File "C:\Users\Rosario\Desktop\customgpt\.venv\Lib\site-packages\g4f\Provider\__init__.py", line 42, in <module>
    from .HuggingChat      import HuggingChat
  File "C:\Users\Rosario\Desktop\customgpt\.venv\Lib\site-packages\g4f\Provider\HuggingChat.py", line 5, in <module>
    from curl_cffi import requests as cf_reqs
ModuleNotFoundError: No module named 'curl_cffi'

**Code**
 from g4f.client import Client

client = Client()
response = client.chat.completions.create(
    model= "gpt-4",
    messages=[{"role": "user", "content": "Hello"}],
 )
print(response.choices[0].message.content)

 
**Environment**
- python version: 3.12.2

**Comment by TheFirstNoob** [comment]
Hey, you install not full libs g4f for correct working.
Use: ```pip install -U g4f``` command and test again.

**Comment by kqlio67** [comment]
Hi @RosarioDiBartolo,

It looks like you're encountering an import error because the 'curl_cffi' module is missing. This module is a dependency for the HuggingChat provider in the g4f library.

To resolve this, you need to install the 'curl_cffi' package. **You can do this by running the following command in your terminal or command prompt:**
```
pip install curl_cffi
```

After installing this package, try running your script again. It should resolve the ModuleNotFoundError you're experiencing.

If you're using a virtual environment (which seems to be the case based on your file path), make sure you activate it before installing the package or running your script.
