### ISSUE TITLE
Base64 Decoding Issue in Image Generation

### ISSUE THREAD

**Issue by Dynamicaaa** [xtekky/gpt4free#2288]
### Issue Summary

When attempting to generate an image using the `g4f` library in Python, I encountered an error related to base64 decoding.  

### Traceback

```python
Traceback (most recent call last):
  File "c:\Users\Anonymous\Documents\EdenX\imggen.py", line 8, in <module>
    response = client.images.generate(
  File "C:\Users\Anonymous\Documents\EdenX\venv\lib\site-packages\g4f\client\client.py", line 421, in generate
    return asyncio.run(self.async_generate(prompt, model, response_format=response_format, **kwargs))
  File "C:\Users\Anonymous\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\Anonymous\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 646, in run_until_complete    return future.result()
  File "C:\Users\Anonymous\Documents\EdenX\venv\lib\site-packages\g4f\client\client.py", line 438, in async_generate
    return await self._process_image_response(response, response_format)
  File "C:\Users\Anonymous\Documents\EdenX\venv\lib\site-packages\g4f\client\client.py", line 479, in _process_image_response  
    image_data_bytes = base64.b64decode(base64_data)
  File "C:\Users\Anonymous\AppData\Local\Programs\Python\Python310\lib\base64.py", line 87, in b64decode
    return binascii.a2b_base64(s)
binascii.Error: Incorrect padding
```

### Environment

- **OS**: Windows 10 Pro (Testing Environment) / Debian 12 (LTS Server)
- **Country**: United States Of America
- **Python Version**: 3.10.7
- **g4f Version**: 0.3.3.1
- **g4f Image Model**: flux-pro

### Steps to Reproduce

1. Install the `g4f` library using `python -m pip install -U g4f`.
2. Execute the script `python main.py`.
3. Observe the traceback error during image generation.

### Additional Information

- This issue occurs consistently when attempting to generate images using specific models.
- The error message suggests an issue with base64 decoding due to incorrect padding.

### Code Sample

```python
import requests
from g4f.client import Client

# Initialize the client
client = Client()

# Generate an image
response = client.images.generate(
    model="flux-pro",
    prompt="Angular face with a sharp jawline, medium brown skin with a few freckles, short curly hair in a high fade style."   
)

# Get the image URL from the response
image_url = response.data[0].url
print(f"Image URL: {image_url}")

# Download the image
image_response = requests.get(image_url)

# Save the image to a file
if image_response.status_code == 200:
    with open("siamese_cat_image.jpg", "wb") as file:
        file.write(image_response.content)
    print("Image downloaded successfully!")
else:
    print("Failed to download the image.")
```

Please advise on how to resolve this issue or if any additional information is required. Thank you!

**Comment by Intiiii** [comment]
same issue here, have you found a way to fix this yet?

**Comment by prp-e** [comment]
Also getting the same result while trying to use it.
