### ISSUE TITLE
The Nexra provider is down 

### ISSUE THREAD

**Issue by Vasabiko** [xtekky/gpt4free#2290]
If you select any image or chat generation model, an error occurs.
![Снимок экрана 2024-10-20 222703](https://github.com/user-attachments/assets/9a11b2ef-347a-40e5-9b7d-18addf7a0040)

```
INFO:werkzeug:192.168.1.2 - - [20/Oct/2024 22:21:33] "GET /backend-api/v2/models/NexraFluxPro HTTP/1.1" 200 -
Couldn't do web search: https://links.duckduckgo.com/d.js RuntimeError: error sending request for url (https://links.duckduckgo.com/d.js?q=Abstraction%2C+smooth+lines%2C+shine%2C+sparkles%2C+maybe+colors.&kl=wt-wt&l=wt-wt&p=&s=0&df=y&vqd=4-291809866526735444012416869664418383668&bing_market=wt-WT&ex=-1): operation timed out

Caused by:
    operation timed out
ERROR:root:403, message='Forbidden', url='https://nexra.aryahcr.cc/api/image/complements'
Traceback (most recent call last):
  File "d:\gpt4free\g4f\gui\server\api.py", line 178, in _create_response_stream
    for chunk in ChatCompletion.create(**kwargs):
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\gpt4free\g4f\providers\base_provider.py", line 223, in create_completion
    yield loop.run_until_complete(await_callback(gen.__anext__))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Serg\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "d:\gpt4free\g4f\providers\base_provider.py", line 52, in await_callback
    return await callback()
           ^^^^^^^^^^^^^^^^
  File "d:\gpt4free\g4f\Provider\nexra\NexraFluxPro.py", line 58, in create_async_generator
    response.raise_for_status()
  File "d:\gpt4free\venv\Lib\site-packages\aiohttp\client_reqrep.py", line 1157, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 403, message='Forbidden', url='https://nexra.aryahcr.cc/api/image/complements'
INFO:werkzeug:192.168.1.2 - - [20/Oct/2024 22:21:46] "POST /backend-api/v2/conversation HTTP/1.1" 200 -
INFO:werkzeug:192.168.1.2 - - [20/Oct/2024 22:21:54] "GET /backend-api/v2/models/NexraLLaMA31 HTTP/1.1" 200 -
Couldn't do web search: https://links.duckduckgo.com/d.js RuntimeError: error sending request for url (https://links.duckduckgo.com/d.js?q=Abstraction%2C+smooth+lines%2C+shine%2C+sparkles%2C+maybe+colors.&kl=wt-wt&l=wt-wt&p=&s=0&df=y&vqd=4-291809866526735444012416869664418383668&bing_market=wt-WT&ex=-1): operation timed out

Caused by:
    operation timed out
ERROR:root:403, message='Forbidden', url='https://nexra.aryahcr.cc/api/chat/complements'
Traceback (most recent call last):
  File "d:\gpt4free\g4f\gui\server\api.py", line 178, in _create_response_stream
    for chunk in ChatCompletion.create(**kwargs):
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\gpt4free\g4f\providers\base_provider.py", line 223, in create_completion
    yield loop.run_until_complete(await_callback(gen.__anext__))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Serg\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "d:\gpt4free\g4f\providers\base_provider.py", line 52, in await_callback
    return await callback()
           ^^^^^^^^^^^^^^^^
  File "d:\gpt4free\g4f\Provider\nexra\NexraLLaMA31.py", line 56, in create_async_generator
    response.raise_for_status()
  File "d:\gpt4free\venv\Lib\site-packages\aiohttp\client_reqrep.py", line 1157, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 403, message='Forbidden', url='https://nexra.aryahcr.cc/api/chat/complements'
INFO:werkzeug:192.168.1.2 - - [20/Oct/2024 22:22:06] "POST /backend-api/v2/conversation HTTP/1.1" 200 -
```

**Comment by TheFirstNoob** [comment]
Hi! 403 is not down. Your region is forbidden. Working correclty on me.
