### ISSUE TITLE
ValueError: Unknown model: dall-e-3

### ISSUE THREAD

**Issue by BaseMax** [xtekky/gpt4free#2305]
```
C:\Users\MAX\Desktop>pip install -U g4f[all]
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: g4f[all] in c:\users\max\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (0.3.3.2)
Requirement already satisfied: requests in c:\users\max\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from g4f[all]) (2.32.3)
Requirement already satisfied: aiohttp in c:\users\max\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from g4f[all]) (3.9.3)
Requirement already satisfied: brotli in c:\users\max\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from g4f[all]) (1.1.0)
Requirement already satisfied: pycryptodome in c:\users\max\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from g4f[all]) (3.20.0)
Requirement already satisfied: curl-cffi>=0.6.2 in c:\users\max\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from g4f[all]) (0.7.3)
Requirement already satisfied: cloudscraper in c:\users\max\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from g4f[all]) (1.2.71)
Requirement already satisfied: certifi in c:\users\max\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from g4f[all]) (2024.8.30)
Requirement already satisfied: browser-cookie3 in c:\users\max\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from g4f[all]) (0.19.1)
Requirement already satisfied: PyExecJS in c:\users\max\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from g4f[all]) (1.5.1)
Requirement already satisfied: duckduckgo-search>=5.0 in c:\users\max\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from g4f[all]) (6.3.2)
Requirement already satisfied: beautifulsoup4 in c:\users\max\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from g4f[all]) (4.12.3)
Requirement already satisfied: pywebview in c:\users\max\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from g4f[all]) (5.2)
Requirement already satisfied: platformdirs in c:\users\max\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from g4f[all]) (4.2.2)
Requirement already satisfied: plyer in c:\users\max\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from g4f[all]) (2.1.0)
Requirement already satisfied: cryptography in c:\users\max\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from g4f[all]) (43.0.0)
Requirement already satisfied: aiohttp-socks in c:\users\max\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from g4f[all]) (0.8.4)
Requirement already satisfied: pillow in c:\users\max\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from g4f[all]) (10.2.0)
Requirement already satisfied: cairosvg in c:\users\max\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from g4f[all]) (2.7.1)
Requirement already satisfied: werkzeug in c:\users\max\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from g4f[all]) (3.0.1)
Requirement already satisfied: flask in c:\users\max\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from g4f[all]) (3.0.2)
Requirement already satisfied: loguru in c:\users\max\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from g4f[all]) (0.7.2)
Requirement already satisfied: fastapi in c:\users\max\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from g4f[all]) (0.109.2)
Requirement already satisfied: uvicorn in c:\users\max\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from g4f[all]) (0.27.0.post1)
Requirement already satisfied: nest-asyncio in c:\users\max\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from g4f[all]) (1.6.0)
Requirement already satisfied: cffi>=1.12.0 in c:\users\max\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from curl-cffi>=0.6.2->g4f[all]) (1.17.0)
Requirement already satisfied: typing-extensions in c:\users\max\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from curl-cffi>=0.6.2->g4f[all]) (4.12.2)
Requirement already satisfied: click>=8.1.7 in c:\users\max\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from duckduckgo-search>=5.0->g4f[all]) (8.1.7)
Requirement already satisfied: primp>=0.6.4 in c:\users\max\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from duckduckgo-search>=5.0->g4f[all]) (0.6.4)
Requirement already satisfied: aiosignal>=1.1.2 in c:\users\max\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from aiohttp->g4f[all]) (1.3.1)
Requirement already satisfied: attrs>=17.3.0 in c:\users\max\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from aiohttp->g4f[all]) (23.2.0)
Requirement already satisfied: frozenlist>=1.1.1 in c:\users\max\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from aiohttp->g4f[all]) (1.4.1)
Requirement already satisfied: multidict<7.0,>=4.5 in c:\users\max\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from aiohttp->g4f[all]) (6.0.5)
Requirement already satisfied: yarl<2.0,>=1.0 in c:\users\max\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from aiohttp->g4f[all]) (1.9.4)
Requirement already satisfied: python-socks<3.0.0,>=2.4.3 in c:\users\max\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from python-socks[asyncio]<3.0.0,>=2.4.3->aiohttp-socks->g4f[all]) (2.4.4)
Requirement already satisfied: soupsieve>1.2 in c:\users\max\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from beautifulsoup4->g4f[all]) (2.5)
Requirement already satisfied: lz4 in c:\users\max\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from browser-cookie3->g4f[all]) (4.3.3)
Requirement already satisfied: pycryptodomex in c:\users\max\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from browser-cookie3->g4f[all]) (3.20.0)
Requirement already satisfied: cairocffi in c:\users\max\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from cairosvg->g4f[all]) (1.6.1)
Requirement already satisfied: cssselect2 in c:\users\max\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from cairosvg->g4f[all]) (0.7.0)
Requirement already satisfied: defusedxml in c:\users\max\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from cairosvg->g4f[all]) (0.7.1)
Requirement already satisfied: tinycss2 in c:\users\max\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from cairosvg->g4f[all]) (1.2.1)
Requirement already satisfied: pyparsing>=2.4.7 in c:\users\max\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from cloudscraper->g4f[all]) (3.1.2)
Requirement already satisfied: requests-toolbelt>=0.9.1 in c:\users\max\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from cloudscraper->g4f[all]) (1.0.0)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\max\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from requests->g4f[all]) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\max\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from requests->g4f[all]) (3.6)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\max\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from requests->g4f[all]) (2.1.0)
Requirement already satisfied: pydantic!=1.8,!=1.8.1,!=2.0.0,!=2.0.1,!=2.1.0,<3.0.0,>=1.7.4 in c:\users\max\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from fastapi->g4f[all]) (2.6.1)
Requirement already satisfied: starlette<0.37.0,>=0.36.3 in c:\users\max\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from fastapi->g4f[all]) (0.36.3)
Requirement already satisfied: Jinja2>=3.1.2 in c:\users\max\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from flask->g4f[all]) (3.1.3)
Requirement already satisfied: itsdangerous>=2.1.2 in c:\users\max\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from flask->g4f[all]) (2.1.2)
Requirement already satisfied: blinker>=1.6.2 in c:\users\max\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from flask->g4f[all]) (1.7.0)
Requirement already satisfied: MarkupSafe>=2.1.1 in c:\users\max\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from werkzeug->g4f[all]) (2.1.5)
Requirement already satisfied: colorama>=0.3.4 in c:\users\max\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from loguru->g4f[all]) (0.4.6)
Requirement already satisfied: win32-setctime>=1.0.0 in c:\users\max\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from loguru->g4f[all]) (1.1.0)
Requirement already satisfied: six>=1.10.0 in c:\users\max\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from PyExecJS->g4f[all]) (1.16.0)
Requirement already satisfied: proxy-tools in c:\users\max\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from pywebview->g4f[all]) (0.1.0)
Requirement already satisfied: bottle in c:\users\max\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from pywebview->g4f[all]) (0.13.1)
Requirement already satisfied: pythonnet in c:\users\max\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from pywebview->g4f[all]) (3.0.3)
Requirement already satisfied: h11>=0.8 in c:\users\max\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from uvicorn->g4f[all]) (0.14.0)
Requirement already satisfied: pycparser in c:\users\max\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from cffi>=1.12.0->curl-cffi>=0.6.2->g4f[all]) (2.22)
Requirement already satisfied: annotated-types>=0.4.0 in c:\users\max\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from pydantic!=1.8,!=1.8.1,!=2.0.0,!=2.0.1,!=2.1.0,<3.0.0,>=1.7.4->fastapi->g4f[all]) (0.6.0)
Requirement already satisfied: pydantic-core==2.16.2 in c:\users\max\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from pydantic!=1.8,!=1.8.1,!=2.0.0,!=2.0.1,!=2.1.0,<3.0.0,>=1.7.4->fastapi->g4f[all]) (2.16.2)
Requirement already satisfied: async-timeout>=3.0.1 in c:\users\max\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from python-socks[asyncio]<3.0.0,>=2.4.3->aiohttp-socks->g4f[all]) (4.0.3)
Requirement already satisfied: anyio<5,>=3.4.0 in c:\users\max\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from starlette<0.37.0,>=0.36.3->fastapi->g4f[all]) (4.2.0)
Requirement already satisfied: webencodings in c:\users\max\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from cssselect2->cairosvg->g4f[all]) (0.5.1)
Requirement already satisfied: clr-loader<0.3.0,>=0.2.6 in c:\users\max\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from pythonnet->pywebview->g4f[all]) (0.2.6)
Requirement already satisfied: sniffio>=1.1 in c:\users\max\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from anyio<5,>=3.4.0->starlette<0.37.0,>=0.36.3->fastapi->g4f[all]) (1.3.0)

C:\Users\MAX\Desktop>
Traceback (most recent call last):.py
  File "C:\Users\MAX\Desktop\gptimg.py", line 4, in <module>
    response = client.images.generate(
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MAX\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\g4f\client\client.py", line 421, in generate
    return asyncio.run(self.async_generate(prompt, model, response_format=response_format, **kwargs))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2032.0_x64__qbz5n2kfra8p0\Lib\asyncio\runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2032.0_x64__qbz5n2kfra8p0\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2032.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\MAX\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\g4f\client\client.py", line 426, in async_generate
    raise ValueError(f"Unknown model: {model}")
ValueError: Unknown model: dall-e-3
```

**Comment by TheFirstNoob** [comment]
Hi, We dont have Dalle-3 after update at the moment.

**Comment by SutirthaChakraborty** [comment]
What are the models we have now?
