### ISSUE TITLE
Providing a docker/image for "linux/arm/v7" (raspberry pi) ... could be marvelous !

### ISSUE THREAD

**Issue by manatlan** [xtekky/gpt4free#2349]
**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
Providing a docker/image for "linux/arm/v7" (raspberry pi) ... could be marvelous !

**Describe alternatives you've considered**
I tried a docker-compose of the github repo, with no luck (compilation trouble)
But I'm really not an expert ... perhaps an expert could help ?

**Additional context**
it could be marvelous to have a docker running on a simple raspberry pi !

**Comment by manatlan** [comment]
Do you known what components is problematic for armv7 ?
Perhaps I could help to fix them.

**Comment by foxfire52** [comment]
@manatlan The project uses **seleniarm/node-chromium** as base image. I think the selenium mainteners don't provide an **armv7** image. You could ask here https://github.com/SeleniumHQ/docker-selenium

**Comment by foxfire52** [comment]
@manatlan Try replacing the first line in **Dockerfile**   https://github.com/xtekky/gpt4free/blob/0d8e4ffa2c0706b0381f53c3985d04255b7170f5/docker/Dockerfile#L1-L5 
with
`FROM seleniarm/node-chromium:4.18.1-20240326`
Then run `docker compose up --build` on your **arm** device.

It's an older selenium docker image with **armv7** support.

**Comment by manatlan** [comment]
I tried ... but got this problem 
```
80.45             building '_cffi_backend' extension
80.45             creating build/temp.linux-armv7l-cpython-311/src/c
80.45             arm-linux-gnueabihf-gcc -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -fPIC -DFFI_BUILDING=1 -DUSE__THREAD -DHAVE_SYNC_SYNCHRONIZE -I/usr/include/ffi -I/usr/include/libffi -I/usr/include/python3.11 -c src/c/_cffi_backend.c -o build/temp.linux-armv7l-cpython-311/src/c/_cffi_backend.o
80.45             src/c/_cffi_backend.c:15:10: fatal error: ffi.h: No such file or directory
80.45                15 | #include <ffi.h>
80.45                   |          ^~~~~~~
80.45             compilation terminated.
80.45             error: command '/usr/bin/arm-linux-gnueabihf-gcc' failed with exit code 1
80.45             [end of output]
80.45       
80.45         note: This error originates from a subprocess, and is likely not a problem with pip.
80.45         ERROR: Failed building wheel for cffi
80.45       Failed to build cffi
80.45       ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (cffi)
80.45       [end of output]
80.45   
80.45   note: This error originates from a subprocess, and is likely not a problem with pip.
81.81 error: subprocess-exited-with-error
81.81 
81.81 × pip subprocess to install build dependencies did not run successfully.
81.81 │ exit code: 1
81.81 ╰─> See above for output.
81.81 
81.81 note: This error originates from a subprocess, and is likely not a problem with pip.
```
it can't build cffi ;-(
any ideas ?

**Comment by foxfire52** [comment]
Try adding this
```

RUN apt-get -qqy update \
&& apt-get -qqy install libffi-dev

```
At line 40 of *Dockerfile*
https://github.com/xtekky/gpt4free/blob/0d8e4ffa2c0706b0381f53c3985d04255b7170f5/docker/Dockerfile#L36-L43
This should fix the missing **ffi.h** file dependency

**Comment by foxfire52** [comment]
There's a new update, **hlohaus** added a slim *Dockerfile* without selenium dependency.

You should try that docker image too, I think it should work.
Download repository latest version and run 
```
docker-compose -f docker-compose-slim.yml up -d --build
```

**Comment by manatlan** [comment]
not better
```
pi@raspberrypi:~/gpt4free$ docker-compose -f docker-compose-slim.yml up -d --build
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.10/site-packages/requests/adapters.py", line 633, in send
    conn = self.get_connection_with_tls_context(
  File "/home/pi/.local/lib/python3.10/site-packages/requests/adapters.py", line 489, in get_connection_with_tls_context
    conn = self.poolmanager.connection_from_host(
  File "/home/pi/.local/lib/python3.10/site-packages/urllib3/poolmanager.py", line 303, in connection_from_host
    return self.connection_from_context(request_context)
  File "/home/pi/.local/lib/python3.10/site-packages/urllib3/poolmanager.py", line 325, in connection_from_context
    raise URLSchemeUnknown(scheme)
urllib3.exceptions.URLSchemeUnknown: Not supported URL scheme http+docker

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/docker/api/client.py", line 214, in _retrieve_server_version
    return self.version(api_version=False)["ApiVersion"]
  File "/usr/lib/python3/dist-packages/docker/api/daemon.py", line 181, in version
    return self._result(self._get(url), json=True)
  File "/usr/lib/python3/dist-packages/docker/utils/decorators.py", line 46, in inner
    return f(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/docker/api/client.py", line 237, in _get
    return self.get(url, **self._set_request_timeout(kwargs))
  File "/home/pi/.local/lib/python3.10/site-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
  File "/home/pi/.local/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/pi/.local/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/home/pi/.local/lib/python3.10/site-packages/requests/adapters.py", line 637, in send
    raise InvalidURL(e, request=request)
requests.exceptions.InvalidURL: Not supported URL scheme http+docker

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/docker-compose", line 33, in <module>
    sys.exit(load_entry_point('docker-compose==1.29.2', 'console_scripts', 'docker-compose')())
  File "/usr/lib/python3/dist-packages/compose/cli/main.py", line 81, in main
    command_func()
  File "/usr/lib/python3/dist-packages/compose/cli/main.py", line 200, in perform_command
    project = project_from_options('.', options)
  File "/usr/lib/python3/dist-packages/compose/cli/command.py", line 60, in project_from_options
    return get_project(
  File "/usr/lib/python3/dist-packages/compose/cli/command.py", line 152, in get_project
    client = get_client(
  File "/usr/lib/python3/dist-packages/compose/cli/docker_client.py", line 41, in get_client
    client = docker_client(
  File "/usr/lib/python3/dist-packages/compose/cli/docker_client.py", line 170, in docker_client
    client = APIClient(use_ssh_client=not use_paramiko_ssh, **kwargs)
  File "/usr/lib/python3/dist-packages/docker/api/client.py", line 197, in __init__
    self._version = self._retrieve_server_version()
  File "/usr/lib/python3/dist-packages/docker/api/client.py", line 221, in _retrieve_server_version
    raise DockerException(
docker.errors.DockerException: Error while fetching server API version: Not supported URL scheme http+docker
pi@raspberrypi:~/gpt4free$ 
```

**Comment by manatlan** [comment]
@foxfire52  ... I'm trying .... with "docker compose" (and not "docker-compose") ...
it's always building (for more than 3 hours) ... but it will do it ;-)
...
I will not update often (it's very very long)

**Comment by manatlan** [comment]
perhaps it's possible to build it via a github action
seems possible
https://earthly.dev/blog/arm-containers-github-actions/

**Comment by manatlan** [comment]
It takes more than 5h... And crash my RPI 3b+, without results ;-(

**Comment by foxfire52** [comment]
@manatlan It is possible but current github action arm build failed

@hlohaus 
Github doesn't provide native arm runners yet ([GitHub-hosted arm64 runners](https://github.com/orgs/community/discussions/19197)), so it cross-compiles.
I think the problem happens when the docker image is cross-compiled on x64 platform with **buildx qemu x64**. Cargo dependency (`duckduckgo-search`->`primp`) can trigger build failure (qemu kernel bug [link1](https://www.github.com/rust-lang/cargo/issues/8719) [link2](https://github.com/pyca/cryptography/issues/6347)). Sometimes it affects cryptography module.
This bug doesn't affect x86 build environments.


As fix we can remove `duckduckgo-search` requirement  and `RUN rustup self uninstall -y` line from _docker-slim_ image.
It _should_ work.

**Comment by foxfire52** [comment]
@manatlan Thanks to hlohaus the **armv7** image is now available on docker.

You can test it with:
```bash
docker run \
  -p 1337:1337 \
  -v ${PWD}/har_and_cookies:/app/har_and_cookies \
  -v ${PWD}/generated_images:/app/generated_images \
  hlohaus789/g4f:latest-slim \
  rm -r -f /app/g4f/ \
  && pip install -U g4f[slim] \
  && python -m g4f.cli api --gui --debug
```

**Comment by tomhan87** [comment]
There are still some errors at build time. My PR should fix them.

**Comment by manatlan** [comment]
still trouble
```
Collecting primp>=0.8.0
  Downloading primp-0.8.0.tar.gz (80 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 80.5/80.5 KB 1.5 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [20 lines of output]
      Checking for Rust toolchain....
      Running `maturin pep517 write-dist-info --metadata-directory /tmp/pip-modern-metadata-6njso_zl --interpreter /usr/bin/python3`
      Traceback (most recent call last):
        File "/usr/lib/python3/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
          main()
        File "/usr/lib/python3/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/usr/lib/python3/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 164, in prepare_metadata_for_build_wheel
          return hook(metadata_directory, config_settings)
        File "/tmp/pip-build-env-j0dfi4pm/overlay/local/lib/python3.10/dist-packages/maturin/__init__.py", line 203, in prepare_metadata_for_build_wheel
          _output = subprocess.check_output(command)
        File "/usr/lib/python3.10/subprocess.py", line 421, in check_output
          return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
        File "/usr/lib/python3.10/subprocess.py", line 503, in run
          with Popen(*popenargs, **kwargs) as process:
        File "/usr/lib/python3.10/subprocess.py", line 971, in __init__
          self._execute_child(args, executable, preexec_fn, close_fds,
        File "/usr/lib/python3.10/subprocess.py", line 1863, in _execute_child
          raise child_exception_type(errno_num, err_msg, err_filename)
      FileNotFoundError: [Errno 2] No such file or directory: 'maturin'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

```

**Comment by manatlan** [comment]
but got better results with : 

```
docker run \
  -p 1337:1337 \
  -v ${PWD}/har_and_cookies:/app/har_and_cookies \
  -v ${PWD}/generated_images:/app/generated_images \
  hlohaus789/g4f:latest-slim \
  rm -r -f /app/g4f/ \
  && pip install -U pip \
  && pip install -U g4f[slim] \
  && python -m g4f.cli api --debug
```

**Comment by foxfire52** [comment]
**cffi** and **pillow** python modules are still missing, I've opened a Pull request to address it.

**Comment by hlohaus** [comment]
@manatlan Hey man, your messages are actually from Bing. Bing Chat is no more. It's now Copilot. And guess what, you don't even need an account to use Copilot! But here's the catch, you can't upload or generate images without one.

> tested with older version (0.3.6.3 & 0.3.7.1) ... but got a lot of : 
> 
> g4f.errors.RateLimitError: CaptchaChallenge: Use other cookies or/and ip address
> g4f.errors.RateLimitError: Response 402: Rate limit reached
> ...
> for a lot of models ("gpt-4o", "gpt-4o-mini", "gemini-pro", "llama*" etc ...)
> 
> seems too lite ;-)
> 
>

**Comment by foxfire52** [comment]
Last error found is **cryptography** module build. I opened a PR.

**Comment by manatlan** [comment]
Thanks a lot !!
I've reached to setup it (with 0.3.8.1)
```
FROM hlohaus789/g4f:latest-armv7
RUN rm -r -f /app/g4f/
RUN pip install -U g4f
CMD ["python3", "-m", "g4f.cli", "api", "--debug"]
```
it works greatly
