### ISSUE TITLE
GF4 Error

### ISSUE THREAD

**Issue by Matuco19** [xtekky/gpt4free#2447]
**Bug description**
I used the g4f usage example, and instead of generating the text I get the error: 
```
Traceback (most recent call last):
  File "c:\Users\silfa\Documents\VSCodeProjects\g4ftest\test.py", line 4, in <module>
    response = client.chat.completions.create(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\silfa\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\g4f\client\__init__.py", line 240, in create
    return next(response)
           ^^^^^^^^^^^^^^
  File "C:\Users\silfa\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\g4f\client\__init__.py", line 98, in iter_append_model_and_provider
    for chunk in response:
  File "C:\Users\silfa\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\g4f\client\__init__.py", line 92, in iter_response      
    yield ChatCompletion.model_construct(content, finish_reason, completion_id, int(time.time()))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\silfa\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\g4f\client\stubs.py", line 88, in model_construct       
    return super().model_construct(
           ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'super' object has no attribute 'model_construct'
```

The code i used:
```py
from g4f.client import Client

client = Client()
response = client.chat.completions.create(
    model="gpt-4o-mini",
    messages=[{"role": "user", "content": "Hello"}],
    # Add any other necessary parameters
)
print(response.choices[0].message.content)
```

**Environment**
- python version: 3.11
- g4f version: 0.3.8.1
- OS: Windows11

**Comment by hlohaus** [comment]
Try updating Pydantic:
- pip install -U pydantic
You need at least version 2.

**Comment by Matuco19** [comment]
> Try updating Pydantic: `pip install -U pydantic` You need at least version 2.

it works, thanks!
