### ISSUE TITLE
Airforce utf-8 decode error

### ISSUE THREAD

**Issue by HongyiHank** [xtekky/gpt4free#2480]
**Bug description**
While I using this code
```
import g4f

provider = g4f.Provider.Airforce

messages = [
    {"role": "system", "content": "Your name is Hank"},
    {"role": "user", "content": "hellow"}
]

response = g4f.ChatCompletion.create(
    model="gpt-4o",
    messages=messages,
    provider=provider
)

print(response)
```
I'll get an error `UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb5 in position 1: invalid start byte`

**Environment**
- python version 3.12.5

**Additional context**
complete error message:
```
C:\Users\hongyihank\OneDrive\doc>py test.py
Traceback (most recent call last):
  File "C:\Users\hongyihank\OneDrive\doc\test.py", line 10, in <module>
    response = g4f.ChatCompletion.create(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hongyihank\AppData\Local\Programs\Python\Python312\Lib\site-packages\g4f\__init__.py", line 55, in create
    return result if stream else ''.join([str(chunk) for chunk in result])
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hongyihank\AppData\Local\Programs\Python\Python312\Lib\site-packages\g4f\providers\asyncio.py", line 53, in to_sync_generator
    yield loop.run_until_complete(await_callback(gen.__anext__))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hongyihank\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\hongyihank\AppData\Local\Programs\Python\Python312\Lib\site-packages\g4f\providers\asyncio.py", line 38, in await_callback
    return await callback()
           ^^^^^^^^^^^^^^^^
  File "C:\Users\hongyihank\AppData\Local\Programs\Python\Python312\Lib\site-packages\g4f\Provider\Airforce.py", line 271, in create_async_generator
    async for result in cls.generate_text(model, messages, max_tokens, temperature, top_p, stream, api_key, proxy):
  File "C:\Users\hongyihank\AppData\Local\Programs\Python\Python312\Lib\site-packages\g4f\Provider\Airforce.py", line 236, in generate_text
    result = await response.json()
             ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hongyihank\AppData\Local\Programs\Python\Python312\Lib\site-packages\aiohttp\client_reqrep.py", line 1260, in json
    return loads(stripped.decode(encoding))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb5 in position 1: invalid start byte
```

**Comment by Arken1xs** [comment]
I have the same issue with Airforce provider. Similar issue will arise if you will try to use GizAI provider:
```File "providertest.py", line 15, in main
    response = await client.chat.completions.create(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
               
  File "\g4f\client\__init__.py", line 163, in async_iter_append_model_and_provider
  
    async for chunk in response:
    
  File "\g4f\client\__init__.py", line 118, in async_iter_response
     
    async for chunk in response:
    
  File "\g4f\Provider\GizAI.py", line 73, in create_async_generator  
  
    result = await response.json()
             ^^^^^^^^^^^^^^^^^^^^^
             
  File "\aiohttp\client_reqrep.py", line 1199, in json
  
    raise ContentTypeError(
    
aiohttp.client_exceptions.ContentTypeError: 0, message="Attempt to decode JSON with unexpected mimetype: ', url='https://app.giz.ai/api/data/users/inferenceServer.infer"```

**Comment by Arken1xs** [comment]
For some reason, response.headers from Airforce always contains this:
`'Content-Encoding': 'zstd'`
ImHex detects the binary content of response as "Zstandard compressed data format" as well.

**Comment by Arken1xs** [comment]
This issue is related only to non-streaming response, so I guess that Airforce is just returning stream by default.

**Comment by HongyiHank** [comment]
I'm not sure if I misunderstood your meaning, but when I used your method and added ```stream=True```, I got ```Airforce does not support "stream" argument```. Here's the complete code and error message:

code:
```
import g4f
provider = g4f.Provider.Airforce
messages = [
    {"role": "system", "content": "Your name is Hank"},
    {"role": "user", "content": "hellow"}
]
async def main():
    response = await g4f.ChatCompletion.create(
        model="gpt-4o",
        messages=messages,
        provider=provider,
        stream=True
    )
    
    answer = ""
    async for chunk in response:
        if chunk.choices and chunk.choices[0].delta.content:
            answer += chunk.choices[0].delta.content
    print(answer)
import asyncio
asyncio.run(main())
```
Error message:
```
C:\Users\hongyihang\OneDrive\doc>py test.py
Traceback (most recent call last):
  File "C:\Users\hongyihang\OneDrive\doc\test.py", line 26, in <module>
    asyncio.run(main())
  File C:\Users\hongyihang\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File C:\Users\hongyihang\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File C:\Users\hongyihang\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\hongyihang\OneDrive\doc\test.py", line 11, in main
    response = await g4f.ChatCompletion.create(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File C:\Users\hongyihang\AppData\Local\Programs\Python\Python312\Lib\site-packages\g4f\__init__.py", line 37, in create
    model, provider = get_model_and_provider(
                      ^^^^^^^^^^^^^^^^^^^^^^^
  File C:\Users\hongyihang\AppData\Local\Programs\Python\Python312\Lib\site-packages\g4f\client\service.py", line 93, in get_model_and_provider
    raise StreamNotSupportedError(f'{provider_name} does not support "stream" argument')
g4f.errors.StreamNotSupportedError: Airforce does not support "stream" argument
```

**Comment by HongyiHank** [comment]
@Arken1xs In `v0.3.9.4`, streaming and system message support was added in Airforce. Therefore, after updating to `v0.3.9.4`, I finally solved the problem by using this code.
```
import g4f

provider = g4f.Provider.Airforce

messages = [
    {"role": "system", "content": "Your name is Hank"},
    {"role": "user", "content": "What is your name?"}
]

def main():
    response = g4f.ChatCompletion.create(
        model="gpt-4o",
        messages=messages,
        provider=provider,
        stream=True
    )
    
    answer = ""
    for chunk in response:
        answer += chunk
    print(answer)

if __name__ == "__main__":
    main()
```
