### ISSUE TITLE
OpenaiAccount/OpenaiChat - ResponseStatusError: Response 403: OpenAI Bot detected

### ISSUE THREAD

**Issue by The2Alert** [xtekky/gpt4free#2493]
**Error**

```json
{
    "error": {
        "message": "ResponseStatusError: Response 403: OpenAI Bot detected"
    },
    "model": "gpt-4o",
    "provider": "OpenaiAccount"
}
```

**Auth**
https://github.com/xtekky/gpt4free?tab=readme-ov-file#har-file-for-openaichat-provider

**Comment by The2Alert** [comment]
@xtekky @hlohaus

**Comment by hlohaus** [comment]
Hey @The2Alert, tell me more about your system? Does it always not work, or just sometimes?  Have you tried it with a proxy?

**Comment by The2Alert** [comment]
@hlohaus It's always the same error. The proxy used is from froxy.com . The account for which the HAR file was created has a Plus subscription and is created via Google Chrome according to the instructions in the README. It would be great to make it possible to log in via localhost:7900 .

**Comment by hlohaus** [comment]
@The2Alert 
I have this issue, if i use nodriver on docker with chatgpt.com:
```
future: <Task finished name='Task-11' coro=<Listener.listener_loop() done, defined at /home/g4f/.local/lib/python3.12/site-packages/nodriver/core/connection.py:591> exception=TypeError("string indices must be integers, not 'str'")>
Traceback (most recent call last):
  File "/home/g4f/.local/lib/python3.12/site-packages/nodriver/core/connection.py", line 634, in listener_loop
    tx(**message)
  File "/home/g4f/.local/lib/python3.12/site-packages/nodriver/core/connection.py", line 116, in __call__
    self.__cdp_obj__.send(response["result"])
  File "/home/g4f/.local/lib/python3.12/site-packages/nodriver/cdp/network.py", line 2726, in get_cookies
    return [Cookie.from_json(i) for i in json['cookies']]
            ^^^^^^^^^^^^^^^^^^^
  File "/home/g4f/.local/lib/python3.12/site-packages/nodriver/cdp/network.py", line 1376, in from_json
    partition_key=CookiePartitionKey.from_json(json['partitionKey']) if json.get('partitionKey', None) is not None else None,
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/g4f/.local/lib/python3.12/site-packages/nodriver/cdp/network.py", line 1275, in from_json
    top_level_site=str(json['topLevelSite']),
                       ^^^^^^^^^^^^^^^^^^^^
TypeError: string indices must be integers, not 'str'
```

There is a issue with the nodriver version.
I have created a working fix.

**Comment by The2Alert** [comment]
@hlohaus thanks you, unittest failed :) 
When is the Docker build release?)

**Comment by woniuzfb** [comment]
> It would be great to make it possible to log in via localhost:7900

`sed -i '/supports_gpt_4 = True/i \\    needs_auth = True' /app/g4f/Provider/needs_auth/OpenaiChat.py`

**Comment by hlohaus** [comment]
@woniuzfb Try OpenaiAccount. It is OpenaiChat with Auth.

**Comment by The2Alert** [comment]
@hlohaus o1 not found

**Endpoint:** /v1/models

**Comment by noVibe** [comment]
Hi! Got same error. Running docker

**Comment by hlohaus** [comment]
using it with authentication first, and then, if needed, you can also run it without authentication.

@noVibe
