### ISSUE TITLE
[ERROR] AttributeError: 'IterListProvider' object has no attribute 'get_parameters'

### ISSUE THREAD

**Issue by blacsheep** [xtekky/gpt4free#2520]
**Bug description**
go to the web page, toggle web search button, request "who are you?".

![image](https://github.com/user-attachments/assets/39e54af1-6452-4e1c-b358-d9c57633841a)

**Environment**
deployed by "docker-compose up -d"

The debugging info:

```
Web search: 'who are you?...' 5 Results 2057 Words
Debugging middleware caught exception in streamed response at a point where response headers were already sent.
Traceback (most recent call last):
  File "/home/g4f/.local/lib/python3.12/site-packages/werkzeug/wsgi.py", line 256, in __next__
    return self._next()
           ^^^^^^^^^^^^
  File "/home/g4f/.local/lib/python3.12/site-packages/werkzeug/wrappers/response.py", line 32, in _iter_encoded
    for item in iterable:
                ^^^^^^^^^
  File "/app/g4f/gui/server/api.py", line 142, in _create_response_stream
    **provider_handler.get_parameters(as_json=True),
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'IterListProvider' object has no attribute 'get_parameters'. Did you mean: 'get_providers'?
```

**Comment by Taurinz359** [comment]
same

**Comment by Kodiman1402** [comment]
same

**Comment by hmenke** [comment]
Possible patch:
```diff
diff --git a/g4f/gui/server/api.py b/g4f/gui/server/api.py
index ca80f7f3..8b929ce4 100644
--- a/g4f/gui/server/api.py
+++ b/g4f/gui/server/api.py
@@ -138,8 +138,12 @@ class Api:
             ignore_stream=True,
             logging=False
         )
+        provider = provider_handler.get_providers(
+            stream=kwargs.get("stream", True),
+            ignored=kwargs.get("ignored", []),
+        )[0]
         params = {
-            **provider_handler.get_parameters(as_json=True),
+            **provider.get_parameters(as_json=True),
             "model": model,
             "messages": kwargs.get("messages"),
             "web_search": kwargs.get("web_search")
```

**Comment by jaypyles** [comment]
> Possible patch:
> 
> ```diff
> diff --git a/g4f/gui/server/api.py b/g4f/gui/server/api.py
> index ca80f7f3..8b929ce4 100644
> --- a/g4f/gui/server/api.py
> +++ b/g4f/gui/server/api.py
> @@ -138,8 +138,12 @@ class Api:
>              ignore_stream=True,
>              logging=False
>          )
> +        provider = provider_handler.get_providers(
> +            stream=kwargs.get("stream", True),
> +            ignored=kwargs.get("ignored", []),
> +        )[0]
>          params = {
> -            **provider_handler.get_parameters(as_json=True),
> +            **provider.get_parameters(as_json=True),
>              "model": model,
>              "messages": kwargs.get("messages"),
>              "web_search": kwargs.get("web_search")
> ```

Worked for me 👍

**Comment by p1aintiff** [comment]
> Possible patch:
> 
> ```diff
> diff --git a/g4f/gui/server/api.py b/g4f/gui/server/api.py
> index ca80f7f3..8b929ce4 100644
> --- a/g4f/gui/server/api.py
> +++ b/g4f/gui/server/api.py
> @@ -138,8 +138,12 @@ class Api:
>              ignore_stream=True,
>              logging=False
>          )
> +        provider = provider_handler.get_providers(
> +            stream=kwargs.get("stream", True),
> +            ignored=kwargs.get("ignored", []),
> +        )[0]
>          params = {
> -            **provider_handler.get_parameters(as_json=True),
> +            **provider.get_parameters(as_json=True),
>              "model": model,
>              "messages": kwargs.get("messages"),
>              "web_search": kwargs.get("web_search")
> ```

make it

**Comment by hlohaus** [comment]
It's fixed or?
