### ISSUE TITLE
ModuleNotFoundError: No module named 'openai_rev'

### ISSUE THREAD

**Issue by SJ50** [xtekky/gpt4free#268]
with latest docker file change.
```
2023-04-28 23:22:50.464 Uncaught app exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 565, in _run_script
    exec(code, module.__dict__)
  File "/usr/src/gpt4free/streamlit_app.py", line 7, in <module>
    from openai_rev import you
ModuleNotFoundError: No module named 'openai_rev'
```

**Comment by pvrego** [comment]
Same

**Comment by sunddytwo** [comment]
how to solve this issue
