### ISSUE TITLE
Bug: Missing module fake_useragent

### ISSUE THREAD

**Issue by simwai** [xtekky/gpt4free#322]
Hello,

I tried to run the project's GUI on repl.it, by copying the gui file to the bsse folder and run the streamlit command and this ended in a missing module fake_useragent error.

Best regards,
simwai

**Comment by valerii-chirkov** [comment]
There are many possible reasons for this type of error:
1. You don't have fake_useragent module installed -> install it manualy via pip.
2. You have several modules called fake_useragent -> use a container or venv.
3. You have your own package named fake_useragent in a directory -> rename it or move away.

And many many more, provide a traceback and your userflow to get this kind of error.

**Comment by simwai** [comment]
Replit didn't handle the package installing itself. Now, I can compile it. Ty.

**Comment by chalukah** [comment]
Traceback (most recent call last):
  File "C:\Python311\Lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 565, in _run_script
    exec(code, module.__dict__)
  File "C:\Users\Chaluka\Documents\GitHub\gpt4free\streamlit_app.py", line 7, in <module>
    from gpt4free import you
  File "C:\Users\Chaluka\Documents\GitHub\gpt4free\gpt4free\__init__.py", line 3, in <module>
    from gpt4free import cocalc
  File "C:\Users\Chaluka\Documents\GitHub\gpt4free\gpt4free\cocalc\__init__.py", line 2, in <module>
    from fake_useragent import UserAgent
ModuleNotFoundError: No module named 'fake_useragent'

**Comment by chalukah** [comment]
can u help me to fix this?

**Comment by chalukah** [comment]
`Traceback (most recent call last):
  File "C:\Python311\Lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 565, in _run_script
    exec(code, module.__dict__)
  File "C:\Users\Chaluka\Documents\GitHub\gpt4free\streamlit_app.py", line 7, in <module>
    from gpt4free import you
  File "C:\Users\Chaluka\Documents\GitHub\gpt4free\gpt4free\__init__.py", line 3, in <module>
    from gpt4free import cocalc
  File "C:\Users\Chaluka\Documents\GitHub\gpt4free\gpt4free\cocalc\__init__.py", line 2, in <module>
    from fake_useragent import UserAgent
ModuleNotFoundError: No module named 'fake_useragent'`

**Comment by chalukah** [comment]
this shows up when i try to deploy

**Comment by valerii-chirkov** [comment]
Try to install it manually:
pip3 install fake_useragent

**Comment by chalukah** [comment]
ModuleNotFoundError: No module named 'pydantic'

**Comment by chalukah** [comment]
now this comes

**Comment by chalukah** [comment]
`Traceback (most recent call last):
  File "C:\Python311\Lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 565, in _run_script
    exec(code, module.__dict__)
  File "C:\Users\Chaluka\Documents\GitHub\gpt4free\streamlit_app.py", line 7, in <module>
    from gpt4free import you
  File "C:\Users\Chaluka\Documents\GitHub\gpt4free\gpt4free\__init__.py", line 3, in <module>
    from gpt4free import cocalc
  File "C:\Users\Chaluka\Documents\GitHub\gpt4free\gpt4free\cocalc\__init__.py", line 3, in <module>
    from pydantic import BaseModel
ModuleNotFoundError: No module named 'pydantic'`

**Comment by valerii-chirkov** [comment]
pip3 install pydantic

It seems like you didn't install required modules at all.
Try pip3 install -r requirements.txt
