### ISSUE TITLE
streamlit_chat_app.py error

### ISSUE THREAD

**Issue by superhero75** [xtekky/gpt4free#358]
After running  streamlit_chat_app, I got the following error message. The latest file doesn't work at all.

2023-05-02 03:12:24.574 Uncaught app exception
Traceback (most recent call last):
  File "/home/.local/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 565, in _run_script
    exec(code, module.__dict__)
  File "/home/gptown/gpt4free/gui/streamlit_chat_app.py", line 86, in <module>
    st.session_state['current_conversation']['user_inputs'].append(user_input)
  File "/home/.local/lib/python3.10/site-packages/streamlit/runtime/state/session_state_proxy.py", line 90, in __getitem__
    return get_session_state()[key]
  File "/home/.local/lib/python3.10/site-packages/streamlit/runtime/state/safe_session_state.py", line 111, in __getitem__
    raise KeyError(key)
KeyError: 'current_conversation'

**Comment by Zybrick** [comment]
The same problem.

 You can now view your Streamlit app in your browser.

  Local URL: http://localhost:8501
  Network URL: ****************

2023-05-04 03:57:01.668 Uncaught app exception
Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 565, in _run_script
    exec(code, module.__dict__)
  File "C:\gpt4free-main\gui\streamlit_chat_app.py", line 10, in <module>
    from query_methods import query, avail_query_methods
  File "C:\gpt4free-main\gui\query_methods.py", line 7, in <module>
    from gpt4free import quora, forefront, theb, you
ImportError: cannot import name 'quora' from 'gpt4free' (C:\Program Files\Python310\lib\site-packages\gpt4free\__init__.py)

![2023-05-04 (2)](https://user-images.githubusercontent.com/104236650/236084314-b5874046-3505-4ddc-915f-e62aa592e665.png)

**Comment by Lanthanum1** [comment]
Same

**Comment by Lanthanum1** [comment]
> The same problem.
> 
> You can now view your Streamlit app in your browser.
> 
> Local URL: http://localhost:8501 Network URL: ****************
> 
> 2023-05-04 03:57:01.668 Uncaught app exception Traceback (most recent call last): File "C:\Program Files\Python310\lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 565, in _run_script exec(code, module.**dict**) File "C:\gpt4free-main\gui\streamlit_chat_app.py", line 10, in from query_methods import query, avail_query_methods File "C:\gpt4free-main\gui\query_methods.py", line 7, in from gpt4free import quora, forefront, theb, you ImportError: cannot import name 'quora' from 'gpt4free' (C:\Program Files\Python310\lib\site-packages\gpt4free__init__.py)
> 
> ![2023-05-04 (2)](https://user-images.githubusercontent.com/104236650/236084314-b5874046-3505-4ddc-915f-e62aa592e665.png)

You can move query_methods.py and streamlit_chat_app.py to base folder and run streamlit_chat_app.py in base folder. Maybe need pip install faker and xtempmail.
