### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by budaniao88** [xtekky/gpt4free#405]
Traceback (most recent call last):
  File "/root/miniconda3/bin/streamlit", line 8, in <module>
    sys.exit(main())
  File "/root/miniconda3/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/root/miniconda3/lib/python3.9/site-packages/click/core.py", line 1055, in main 
    rv = self.invoke(ctx)
  File "/root/miniconda3/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/root/miniconda3/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/root/miniconda3/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/root/miniconda3/lib/python3.9/site-packages/streamlit/web/cli.py", line 233, in main_run
    _main_run(target, args, flag_options=kwargs)
  File "/root/miniconda3/lib/python3.9/site-packages/streamlit/web/cli.py", line 269, in _main_run
    bootstrap.run(file, command_line, args, flag_options)
  File "/root/miniconda3/lib/python3.9/site-packages/streamlit/web/bootstrap.py", line 385, in run
    _install_pages_watcher(main_script_path)
  File "/root/miniconda3/lib/python3.9/site-packages/streamlit/web/bootstrap.py", line 361, in _install_pages_watcher
    watch_dir(
  File "/root/miniconda3/lib/python3.9/site-packages/streamlit/watcher/path_watcher.py", line 153, in watch_dir
    return _watch_path(
  File "/root/miniconda3/lib/python3.9/site-packages/streamlit/watcher/path_watcher.py", line 128, in _watch_path
    watcher_class(
  File "/root/miniconda3/lib/python3.9/site-packages/streamlit/watcher/event_based_path_watcher.py", line 92, in __init__
    path_watcher.watch_path(
  File "/root/miniconda3/lib/python3.9/site-packages/streamlit/watcher/event_based_path_watcher.py", line 170, in watch_path
    folder_handler.watch = self._observer.schedule(
  File "/root/miniconda3/lib/python3.9/site-packages/watchdog/observers/api.py", line 301, in schedule
    emitter.start()
  File "/root/miniconda3/lib/python3.9/site-packages/watchdog/utils/__init__.py", line 92, in start
    self.on_thread_start()
  File "/root/miniconda3/lib/python3.9/site-packages/watchdog/observers/inotify.py", line 119, in on_thread_start
    self._inotify = InotifyBuffer(path, self.watch.is_recursive)
  File "/root/miniconda3/lib/python3.9/site-packages/watchdog/observers/inotify_buffer.py", line 37, in __init__
    self._inotify = Inotify(path, recursive)
  File "/root/miniconda3/lib/python3.9/site-packages/watchdog/observers/inotify_c.py", line 179, in __init__
    self._add_dir_watch(path, recursive, event_mask)
  File "/root/miniconda3/lib/python3.9/site-packages/watchdog/observers/inotify_c.py", line 402, in _add_dir_watch
    self._add_watch(full_path, mask)
  File "/root/miniconda3/lib/python3.9/site-packages/watchdog/observers/inotify_c.py", line 416, in _add_watch
    Inotify._raise_error()
  File "/root/miniconda3/lib/python3.9/site-packages/watchdog/observers/inotify_c.py", line 432, in _raise_error
    raise OSError(err, os.strerror(err))

**Comment by Belissimo-T** [comment]
@budaniao88 I assume you were trying to run a terminal command. What was it?
