### ISSUE TITLE
error

### ISSUE THREAD

**Issue by mht2953658596** [xtekky/gpt4free#412]
An error occurred: failed to do request: Get "https://you.com/api/streamingSearch?q=%E5%86%99%E4%B8%AA%E4%BA%8C%E5%88%86%E6%9F%A5%E6%89%BE&page=1&count=10&safeSearch=Moderate&onShoppingPage=False&mkt=&responseFilter=WebPages%2CTranslations%2CTimeZone%2CComputation%2CRelatedSearches&domain=youchat&queryTraceId=f2a115d4-8304-4cc0-a86e-e38422213473&chat=%5B%5D": dial tcp [2a03:2880:f131:83:face:b00c:0:25de]:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.. Please make sure you are using a valid cloudflare clearance token and user agent.

**Comment by mht2953658596** [comment]
![image](https://user-images.githubusercontent.com/59814105/235976492-7a4805cb-3521-494e-adc5-d179ff6aa5b7.png)

**Comment by mht2953658596** [comment]
it will be ok，gpt4free\you\__init__.py

**Comment by Py1024plus** [comment]
NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
NotFoundError：无法在“节点”上执行“removeChild”：要删除的节点不是该节点的子节点。
at Eu (http://localhost:8501/static/js/main.b4c46d75.js:2:2472324)
at Ts (http://localhost:8501/static/js/main.b4c46d75.js:2:2484114)
at t.unstable_runWithPriority (http://localhost:8501/static/js/main.b4c46d75.js:2:3378608)
at Zo (http://localhost:8501/static/js/main.b4c46d75.js:2:2427204)
at Rs (http://localhost:8501/static/js/main.b4c46d75.js:2:2482072)
at Os (http://localhost:8501/static/js/main.b4c46d75.js:2:2478158)
at http://localhost:8501/static/js/main.b4c46d75.js:2:2427427
at t.unstable_runWithPriority (http://localhost:8501/static/js/main.b4c46d75.js:2:3378608)
at Zo (http://localhost:8501/static/js/main.b4c46d75.js:2:2427204)
at Ko (http://localhost:8501/static/js/main.b4c46d75.js:2:2427372)
