### ISSUE TITLE
Once I have docker running

### ISSUE THREAD

**Issue by dorcu** [xtekky/gpt4free#436]
Once I have docker running, if I access the IP and port 8501 the web stays loading. It is normal? Do you have a graphical environment?

**Comment by dorcu** [comment]
If I run "streamlit run gui/streamlit_app.py" y have this error:

Traceback (most recent call last):
  File "/usr/local/bin/streamlit", line 5, in <module>
    from streamlit.web.cli import main
  File "/usr/local/lib/python3.9/dist-packages/streamlit/__init__.py", line 55, in <module>
    from streamlit.delta_generator import DeltaGenerator as _DeltaGenerator
  File "/usr/local/lib/python3.9/dist-packages/streamlit/delta_generator.py", line 42, in <module>
    from streamlit.elements.arrow import ArrowMixin
  File "/usr/local/lib/python3.9/dist-packages/streamlit/elements/arrow.py", line 31, in <module>
    from pandas.io.formats.style import Styler
  File "/usr/local/lib/python3.9/dist-packages/pandas/io/formats/style.py", line 56, in <module>
    jinja2 = import_optional_dependency("jinja2", extra="DataFrame.style requires jinja2.")
  File "/usr/local/lib/python3.9/dist-packages/pandas/compat/_optional.py", line 171, in import_optional_dependency
    raise ImportError(msg)
ImportError: Pandas requires version '3.0.0' or newer of 'jinja2' (version '2.11.3' currently installed).

**Comment by dorcu** [comment]
Now I ran this command:

pip install --upgrade jinja2

And then:

streamlit run gui/streamlit_app.py

And  I get this message:

streamlit run gui/streamlit_app.py

Collecting usage statistics. To deactivate, set browser.gatherUsageStats to False.


  You can now view your Streamlit app in your browser.

  Network URL: http://xxx:8501
  External URL: http://xxx:8501

But if I access the URL, the web keeps loading

**Comment by lawrence7777777** [comment]
> 

+1

**Comment by paradoxgoo** [comment]
+1

**Comment by ali-farhad** [comment]
same error. my docker instance is running but i can't see anything in the browser. forever loading and then it times out. any solutions?
