### ISSUE TITLE
ModuleNotFoundError: No module named 'mailgw_temporary_email'

### ISSUE THREAD

**Issue by shaonaoteam** [xtekky/gpt4free#496]
I deployed and initated the project through Docker，error reported after entering the homepage：

Traceback (most recent call last):
2023-05-07 10:49:09   File "/usr/app/venv/lib/python3.11/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 565, in _run_script
2023-05-07 10:49:09     exec(code, module.__dict__)
2023-05-07 10:49:09   File "/usr/app/streamlit_app.py", line 7, in <module>
2023-05-07 10:49:09     from gpt4free import you
2023-05-07 10:49:09   File "/usr/app/gpt4free/__init__.py", line 4, in <module>
2023-05-07 10:49:09     from gpt4free import forefront
2023-05-07 10:49:09   File "/usr/app/gpt4free/forefront/__init__.py", line 7, in <module>
2023-05-07 10:49:09     from mailgw_temporary_email import Email
2023-05-07 10:49:09 ModuleNotFoundError: No module named 'mailgw_temporary_email'
2023-05-07 10:49:23 2023-05-07 02:49:23.998 Uncaught app exception
2023-05-07 10:49:23 Traceback (most recent call last):
2023-05-07 10:49:23   File "/usr/app/venv/lib/python3.11/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 565, in _run_script
2023-05-07 10:49:23     exec(code, module.__dict__)
2023-05-07 10:49:23   File "/usr/app/streamlit_app.py", line 7, in <module>
2023-05-07 10:49:23     from gpt4free import you
2023-05-07 10:49:23   File "/usr/app/gpt4free/__init__.py", line 4, in <module>
2023-05-07 10:49:23     from gpt4free import forefront
2023-05-07 10:49:23   File "/usr/app/gpt4free/forefront/__init__.py", line 7, in <module>
2023-05-07 10:49:23     from mailgw_temporary_email import Email
2023-05-07 10:49:23 ModuleNotFoundError: No module named 'mailgw_temporary_email'

![image](https://user-images.githubusercontent.com/43848538/236655171-3d50ff65-50ba-4ca4-960d-38c70b3e13dd.png)

**Comment by cuihp** [comment]
pip install mailgw_temporary_email

**Comment by Jeevaraz** [comment]
run this command : 
`pip3 install mailgw_temporary_email`

**Comment by shaonaoteam** [comment]
[https://github.com/cf-pages/gpt4free/commit/9be1a8953aefaa5d046b692533bd10a0c275d829](url)
