### ISSUE TITLE
pywebio-usesless.py模块，错误返回Program Error

### ISSUE THREAD

**Issue by timing2022** [xtekky/gpt4free#582]
Traceback (most recent call last):
  File "C:\Users\ca'd\AppData\Roaming\Python\Python39\site-packages\pywebio\session\threadbased.py", line 86, in main_task
    target()
  File "D:\python-code\gpt4free\gpt4free\pywebio-usesless.py", line 56, in main
    msg()
  File "D:\python-code\gpt4free\gpt4free\pywebio-usesless.py", line 40, in msg
    rp= ask(text["text"])
  File "D:\python-code\gpt4free\gpt4free\pywebio-usesless.py", line 17, in ask
    req = usesless.Completion.create(prompt=prompt, parentMessageId=local.message_id)
  File "D:\python-code\gpt4free\gpt4free\gpt4free\usesless\__init__.py", line 47, in create
    response = Completion.__response_to_json(content)
  File "D:\python-code\gpt4free\gpt4free\gpt4free\usesless\__init__.py", line 54, in __response_to_json
    split_text = text.rsplit("\n", 1)[1]
IndexError: list index out of range

然后继续刷新回答也没用
![image](https://github.com/xtekky/gpt4free/assets/111714707/5dbe3ad2-632c-415d-8873-e88088a1b18a)

**Comment by timing2022** [comment]
有无解决之法？

**Comment by timing2022** [comment]
后台返回错误
![image](https://github.com/xtekky/gpt4free/assets/111714707/c19f0644-3fdb-4567-8d06-35d1d14fc52f)

**Comment by taiyi747** [comment]
usesless似乎改变了网站内容爬虫失效，pywebio版本缺少维护，过两天更新

**Comment by timing2022** [comment]
谢谢解答
