### ISSUE TITLE
    raise SSLError(e, request=request)

### ISSUE THREAD

**Issue by Ioloper** [xtekky/gpt4free#655]
**Bug description**
I used the example given in the README file and only changed the proxy parameter
Running gpt4free using a network agent in China produces the following error message:
  File "E:\CodeBase\Python\gpt4free_test\venv\lib\site-packages\requests\adapters.py", line 517, in send
    raise SSLError(e, request=request)
All error messages are as follows:
Traceback (most recent call last):
  File "E:\CodeBase\Python\gpt4free_test\venv\lib\site-packages\urllib3\connectionpool.py", line 467, in _make_request
    self._validate_conn(conn)
  File "E:\CodeBase\Python\gpt4free_test\venv\lib\site-packages\urllib3\connectionpool.py", line 1092, in _validate_conn
    conn.connect()
  File "E:\CodeBase\Python\gpt4free_test\venv\lib\site-packages\urllib3\connection.py", line 635, in connect
    sock_and_verified = _ssl_wrap_socket_and_match_hostname(
  File "E:\CodeBase\Python\gpt4free_test\venv\lib\site-packages\urllib3\connection.py", line 776, in _ssl_wrap_socket_and_match_hostname
    ssl_sock = ssl_wrap_socket(
  File "E:\CodeBase\Python\gpt4free_test\venv\lib\site-packages\urllib3\util\ssl_.py", line 466, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls, server_hostname)
  File "E:\CodeBase\Python\gpt4free_test\venv\lib\site-packages\urllib3\util\ssl_.py", line 510, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "D:\Tools\DE\Python\python 3.10.0\lib\ssl.py", line 512, in wrap_socket
    return self.sslsocket_class._create(
  File "D:\Tools\DE\Python\python 3.10.0\lib\ssl.py", line 1070, in _create
    self.do_handshake()
  File "D:\Tools\DE\Python\python 3.10.0\lib\ssl.py", line 1341, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:997)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\CodeBase\Python\gpt4free_test\venv\lib\site-packages\urllib3\connectionpool.py", line 790, in urlopen
    response = self._make_request(
  File "E:\CodeBase\Python\gpt4free_test\venv\lib\site-packages\urllib3\connectionpool.py", line 491, in _make_request
    raise new_e
urllib3.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:997)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\CodeBase\Python\gpt4free_test\venv\lib\site-packages\requests\adapters.py", line 486, in send
    resp = conn.urlopen(
  File "E:\CodeBase\Python\gpt4free_test\venv\lib\site-packages\urllib3\connectionpool.py", line 844, in urlopen
    retries = retries.increment(
  File "E:\CodeBase\Python\gpt4free_test\venv\lib\site-packages\urllib3\util\retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='chat-server.tenant-forefront-default.knative.chi.coreweave.com', port=443): Max retries exceeded with url: /chat (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:997)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\CodeBase\Python\gpt4free_test\main.py", line 7, in <module>
    response = gpt4free.Completion.create(
  File "E:\CodeBase\Python\gpt4free_test\venv\lib\site-packages\gpt4free\__init__.py", line 41, in create
    return Completion.__fore_front_service(prompt, **kwargs)
  File "E:\CodeBase\Python\gpt4free_test\venv\lib\site-packages\gpt4free\__init__.py", line 59, in __fore_front_service
    return forefront.Completion.create(prompt=prompt, **kwargs).text
  File "E:\CodeBase\Python\gpt4free_test\venv\lib\site-packages\gpt4free\forefront\__init__.py", line 175, in create
    for response in StreamingCompletion.create(
  File "E:\CodeBase\Python\gpt4free_test\venv\lib\site-packages\gpt4free\forefront\__init__.py", line 133, in create
    for chunk in post(
  File "E:\CodeBase\Python\gpt4free_test\venv\lib\site-packages\requests\api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
  File "E:\CodeBase\Python\gpt4free_test\venv\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "E:\CodeBase\Python\gpt4free_test\venv\lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "E:\CodeBase\Python\gpt4free_test\venv\lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "E:\CodeBase\Python\gpt4free_test\venv\lib\site-packages\requests\adapters.py", line 517, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='chat-server.tenant-forefront-default.knative.chi.coreweave.com', port=443): Max retries exceeded with url: /chat (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:997)')))

Process finished with exit code 1

**Screenshots**
![image](https://github.com/xtekky/gpt4free/assets/84219482/f4361efa-4fc9-40c1-9de2-2c4dc1e3d484)

**Environement**
- python version: python 3.10
- IDE: Pycharm

**Comment by xtekky** [comment]
try new version
