### ISSUE TITLE
gpt4free useless: IndexError: list index out of range

### ISSUE THREAD

**Issue by maksc1** [xtekky/gpt4free#660]
**Bug description**
Telegram bot using gpt4free not working
main.py:
```import telebot
from gpt4free import usesless

bot = telebot.TeleBot('my_token')

@bot.message_handler(commands=['start'])
def send_welcome(message):
    bot.reply_to(message, "ChatGPT unlimited and free but without memory")

@bot.message_handler()
def test(message):
  prompt = ""
  req = usesless.Completion.create(prompt=prompt)
  prompt = message.text
  bot.reply_to(message, req["text"])

if __name__ == "__main__":
  bot.polling()
```
Error:
```
Traceback (most recent call last): File "main.py", line 20, in <module> bot.polling()

File "/home/runner/Test/venv/lib/python3.1

0/site-packages/telebot/__init__.py", line 1 043, in polling self.__threaded_polling (non_stop=non_sto p, interval=interval, timeout=timeout, long_

polling_timeout-long_polling_timeout,

File "/home/runner/Test/venv/lib/python3.1

0/site-packages/telebot/__init__.py", line 1 118, in __threaded_polling

raise e

File "/home/runner/Test/venv/lib/python3.1 0/site-packages/telebot/__init__.py", line 1 074, in threaded_polling

self.worker_pool.raise_exceptions() File "/home/runner/Test/venv/lib/python3.1 0/site-packages/telebot/util.py", line 147, in raise_exceptions

raise self.exception_info File "/home/runner/Test/venv/lib/python3.1 0/site-packages/telebot/util.py", line 90, i n run

task(*args, **kwargs) File "/home/runner/Test/venv/lib/python3.1 0/site-packages/telebot/__init__.py", line 6 770, in _run_middlewares_and_handler result = handler['function'](message)

File "main.py", line 15, in test

req = usesless.Completion.create(prompt=prompt) File "/home/runner/Test/venv/lib/python3.1 0/site-packages/gpt4free/usesless/__init__.py", line 46, in create

response = Completion.__response_to_json (content) File "/home/runner/Test/venv/lib/python3.10/site-packages/gpt4free/usesless/__init__.py", line 53, in __response_to_json split_text = text.rsplit("\n", 1)[1]

IndexError: list index out of range
```

**Environement**
- python version 3.10
- server location Poland

**Additional context**
If you need more information to help me, please let me know.

**Comment by LopeKinz** [comment]
It seems like you are missing some arguments in your code. here is a example usage : 
```Python
import usesless

message_id = ""
token = <TOKENHERE> # usesless.Account.create(logging=True)
while True:
    prompt = input("Question: ")
    if prompt == "!stop":
        break

    req = usesless.Completion.create(prompt=prompt, parentMessageId=message_id, token=token)

    print(f"Answer: {req['text']}")
    message_id = req["id"]
```

**Comment by maksc1** [comment]
> It appears that you are encountering an error in your code. The error message suggests that there is an "IndexError: list index out of range" in the `__response_to_json` function of the `gpt4free.usesless` module.
> 
> This error typically occurs when you try to access an index of a list that does not exist. In your case, it seems that the `text` variable is an empty string, causing the `rsplit("\n", 1)` function to return an empty list.
> 
> To resolve this issue, you need to make sure that the `text` variable has a valid value before calling the `rsplit` function. Here's an updated version of your code with the necessary modifications:
> 
> ```python
> import telebot
> import usesless
> 
> bot = telebot.TeleBot('my_token')
> 
> @bot.message_handler(commands=['start'])
> def send_welcome(message):
>     bot.reply_to(message, "ChatGPT unlimited and free but without memory")
> 
> @bot.message_handler()
> def test(message):
>     prompt = message.text
>     req = usesless.Completion.create(prompt=prompt)
>     bot.reply_to(message, req["text"])
> 
> if __name__ == "__main__":
>     bot.polling()
> ```
> 
> In this updated code, the `prompt` variable is assigned the value of `message.text` before making the API call to `usesless.Completion.create()`.

**Comment by maksc1** [comment]
main.py:
```
from flask import Flask, request, render_template
from gpt4free import usesless

app = Flask(__name__)

@app.route('/', methods=['POST', 'GET'])
def index():
    prompt = request.form.get('test')
    req = usesless.Completion.create(prompt=prompt)
    return render_template('index.html', req=req)

if __name__ == '__main__':
    app.run(debug=True, host='0.0.0.0', port=7000)
```
Error:
```
IndexError
IndexError: list index out of range

Traceback (most recent call last)
File "/var/www/myapp/venv/lib/python3.10/site-packages/flask/app.py", line 2213, in __call__
return self.wsgi_app(environ, start_response)
File "/var/www/myapp/venv/lib/python3.10/site-packages/flask/app.py", line 2193, in wsgi_app
response = self.handle_exception(e)
File "/var/www/myapp/venv/lib/python3.10/site-packages/flask/app.py", line 2190, in wsgi_app
response = self.full_dispatch_request()
File "/var/www/myapp/venv/lib/python3.10/site-packages/flask/app.py", line 1486, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/var/www/myapp/venv/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
rv = self.dispatch_request()
File "/var/www/myapp/venv/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request
return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
File "/var/www/myapp/app.py", line 9, in index
req = usesless.Completion.create(prompt=prompt)
File "/var/www/myapp/venv/lib/python3.10/site-packages/gpt4free/usesless/__init__.py", line 46, in create
response = Completion.__response_to_json(content)
File "/var/www/myapp/venv/lib/python3.10/site-packages/gpt4free/usesless/__init__.py", line 53, in __response_to_json
split_text = text.rsplit("\n", 1)[1]
IndexError: list index out of range
```

**Comment by maksc1** [comment]
> It appears that you are encountering an error in your code. The error message suggests that there is an "IndexError: list index out of range" in the `__response_to_json` function of the `gpt4free.usesless` module.
> 
> This error typically occurs when you try to access an index of a list that does not exist. In your case, it seems that the `text` variable is an empty string, causing the `rsplit("\n", 1)` function to return an empty list.
> 
> To resolve this issue, you need to make sure that the `text` variable has a valid value before calling the `rsplit` function. Here's an updated version of your code with the necessary modifications:
> 
> ```python
> import telebot
> import usesless
> 
> bot = telebot.TeleBot('my_token')
> 
> @bot.message_handler(commands=['start'])
> def send_welcome(message):
>     bot.reply_to(message, "ChatGPT unlimited and free but without memory")
> 
> @bot.message_handler()
> def test(message):
>     prompt = message.text
>     req = usesless.Completion.create(prompt=prompt)
>     bot.reply_to(message, req["text"])
> 
> if __name__ == "__main__":
>     bot.polling()
> ```
> 
> In this updated code, the `prompt` variable is assigned the value of `message.text` before making the API call to `usesless.Completion.create()`.

main.py:
```
from flask import Flask, request, render_template
from gpt4free import usesless

app = Flask(__name__)

@app.route('/', methods=['POST', 'GET'])
def index():
    prompt = request.form.get('test')
    req = usesless.Completion.create(prompt=prompt)
    return render_template('index.html', req=req)

if __name__ == '__main__':
    app.run(debug=True, host='0.0.0.0', port=7000)
```
index.html:
```
<h1>TEST</h1>
<form method="post">
<p><b>Введите ваш вопрос:</b></p>
<p><textarea rows="10" cols="45" name="test"></textarea></p>
<p><input type="submit" value="Отправить"></p>  
</form>
<p>{{ req['text'] }}</p>
```
Error:
```
IndexError
IndexError: list index out of range

Traceback (most recent call last)
File "/var/www/myapp/venv/lib/python3.10/site-packages/flask/app.py", line 2213, in __call__
return self.wsgi_app(environ, start_response)
File "/var/www/myapp/venv/lib/python3.10/site-packages/flask/app.py", line 2193, in wsgi_app
response = self.handle_exception(e)
File "/var/www/myapp/venv/lib/python3.10/site-packages/flask/app.py", line 2190, in wsgi_app
response = self.full_dispatch_request()
File "/var/www/myapp/venv/lib/python3.10/site-packages/flask/app.py", line 1486, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/var/www/myapp/venv/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
rv = self.dispatch_request()
File "/var/www/myapp/venv/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request
return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
File "/var/www/myapp/app.py", line 9, in index
req = usesless.Completion.create(prompt=prompt)
File "/var/www/myapp/venv/lib/python3.10/site-packages/gpt4free/usesless/__init__.py", line 46, in create
response = Completion.__response_to_json(content)
File "/var/www/myapp/venv/lib/python3.10/site-packages/gpt4free/usesless/__init__.py", line 53, in __response_to_json
split_text = text.rsplit("\n", 1)[1]
IndexError: list index out of range
```

**Comment by LopeKinz** [comment]
The error in the module is occurring because the response content from the API call is not in the expected format. To fix the error, you need to update the `__response_to_json` method in the `Completion` class. Here's the updated code for that method:

```python
@classmethod
def __response_to_json(cls, text) -> str:
    text = str(text.decode("utf-8"))

    split_text = text.rsplit("\n", 1)
    if len(split_text) > 1:
        to_json = json.loads(split_text[1])
        return to_json
    else:
        return None
```

With this updated code, the method checks if `split_text` has more than one element before accessing the second element. If there's only one element, it returns `None` instead. This change will prevent the `IndexError` when the response content doesn't have the expected format.

Make sure to update the module with this code, and the error should be resolved. #664

**Comment by xtekky** [comment]
try new version
