### ISSUE TITLE
Another backend for GPT-4

### ISSUE THREAD

**Issue by cabfile** [xtekky/gpt4free#694]
None of the current ones work for me (even Bing). One of them even returns 502 Bad Gateway.

**Comment by xtekky** [comment]
what about Bing ?

**Comment by killporter** [comment]
> what about Bing ?

Using g4f.Provider.Providers.Bing provider
[2023-06-28 13:44:56,700] ERROR in app: Exception on /chat [POST]
Traceback (most recent call last):
  File "C:\Users\39340\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\39340\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\39340\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\39340\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Chrome Extention\freegpt ui\gpt4free\serverextra.py", line 12, in chat
    response = g4f.ChatCompletion.create(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Chrome Extention\freegpt ui\gpt4free\g4f\__init__.py", line 33, in create
    if stream else ''.join(engine._create_completion(model.name, messages, stream, **kwargs)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Chrome Extention\freegpt ui\gpt4free\g4f\Provider\Providers\Bing.py", line 342, in _create_completion
    for token in response:
  File "F:\Chrome Extention\freegpt ui\gpt4free\g4f\Provider\Providers\Bing.py", line 308, in run
    loop = asyncio.get_event_loop()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\39340\AppData\Local\Programs\Python\Python311\Lib\asyncio\events.py", line 677, in get_event_loop
    raise RuntimeError('There is no current event loop in thread %r.'
RuntimeError: There is no current event loop in thread 'Thread-1 (process_request_thread)'.

**Comment by cabfile** [comment]
> what about Bing ?

i literally stated that even bing doesnt work
