### ISSUE TITLE
client_exceptions.WSServerHandshakeError:200

### ISSUE THREAD

**Issue by OHNope** [xtekky/gpt4free#708]
$ vim test.py

  1 import g4f
  2 from g4f.Provider import (
  3     Ails,
  4     You,
  5     Bing,
  6     Yqcloud,
  7     Theb,
  8     Aichat,
  9     Bard,
 10     Vercel,
 11     Forefront,
 12     Lockchat,
 13     Liaobots,
 14     H2o,
 15     ChatgptLogin,
 16     DeepAi,
 17     GetGpt
 18 )
 19 
 20 # usage:
 21 response = g4f.ChatCompletion.create(model=g4f.Model.gpt_4, messages=[
 22          
$ python test.py
Using g4f.Provider.Providers.Bing provider
Traceback (most recent call last):
  File "test.py", line 21, in <module>
    response = g4f.ChatCompletion.create(model=g4f.Model.gpt_4, messages=[
  File "/Users/xby/gpt4free/g4f/__init__.py", line 33, in create
    if stream else ''.join(engine._create_completion(model.name, messages, stream, **kwargs)))
  File "/Users/xby/gpt4free/g4f/Provider/Providers/Bing.py", line 342, in _create_completion
    for token in response:
  File "/Users/xby/gpt4free/g4f/Provider/Providers/Bing.py", line 313, in run
    next_val = loop.run_until_complete(gen.__anext__())
  File "/usr/local/anaconda3/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/Users/xby/gpt4free/g4f/Provider/Providers/Bing.py", line 164, in stream_generate
    wss = await session.ws_connect('wss://sydney.bing.com/sydney/ChatHub', ssl=ssl_context, autoping=False,
  File "/Users/xby/gpt4free/venv/lib/python3.8/site-packages/aiohttp/client.py", line 795, in _ws_connect
    raise WSServerHandshakeError(
aiohttp.client_exceptions.WSServerHandshakeError: 200, message='Invalid response status', url=URL('wss://sydney.bing.com/sydney/ChatHub')
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f9edeb33d30>
(venv)

**Comment by a603558762** [comment]
same problem
