### ISSUE TITLE
No module named 'Crypto'

### ISSUE THREAD

**Issue by win4r** [xtekky/gpt4free#715]
Traceback (most recent call last):
  File "./star.py", line 1, in <module>
    import g4f
  File "/workspace/poeapi/gpt4free/g4f/__init__.py", line 2, in <module>
    from . import Provider
  File "/workspace/poeapi/gpt4free/g4f/Provider/__init__.py", line 2, in <module>
    from .Providers import (
  File "/workspace/poeapi/gpt4free/g4f/Provider/Providers/GetGpt.py", line 5, in <module>
    from Crypto.Cipher import AES
ModuleNotFoundError: No module named 'Crypto'

**Comment by smpurkis** [comment]
I believe `pip install pycryptodome` should solve this
