### ISSUE TITLE
ModuleNotFoundError: No module named 'execjs'

### ISSUE THREAD

**Issue by DoubleJuly** [xtekky/gpt4free#722]
After installing the requirement.txt, there are still many modules not found, such as this one.
Traceback (most recent call last):
  File "D:/gpt4free-2/test.py", line 1, in <module>
    import g4f
  File "D:\gpt4free-2\g4f\__init__.py", line 2, in <module>
    from . import Provider
  File "D:\gpt4free-2\g4f\Provider\__init__.py", line 2, in <module>
    from .Providers import (
  File "D:\gpt4free-2\g4f\Provider\Providers\Vercel.py", line 4, in <module>
    import execjs
ModuleNotFoundError: No module named 'execjs'

**Comment by ayonovdenizs** [comment]
in folder gpt4free:
`pip install -r requirements.txt`

**Comment by ayonovdenizs** [comment]
pip install pyexecjs
