### ISSUE TITLE
JSON error only if deployed to Oracle cloud

### ISSUE THREAD

**Issue by iu2frl** [xtekky/gpt4free#731]
**Bug description**
I create a gpt4free script in Python, when the code is executed on my local machine, it works just fine, as soon as i copy the exact same code to a Docker container running the same Python 3.10.11 version with the same packages on the Oracle cloud i get a JSON error

Code snippet:
```python 
    ...
    # Generate temporary reply
    newReply = bot.reply_to(inputMessage, "Please wait...")
    # Process the input query
    inputQuery = inputMessage.text.capitalize().replace("/ai", "").strip()
    # Create the GPT4FREE instance
    try:
        gptResponse: str = g4f.ChatCompletion.create(model=g4f.Model.gpt_4, messages=[{"role": "user", "content": inputQuery}])
    except Exception as retExc:
        # Plot errors if needed
        bot.edit_message_text(retExc, inputMessage.chat.id, newReply.id)
        return
    # Cleanup response from GPT if needed
    gptResponse = re.sub(r"(\[\^\d\^\])", "", gptResponse)
    # Try to process the input text as markdown
    ...
```
Error on the Docker container:

```bash
Starting bot
Using g4f.Provider.Providers.Bing provider
Exception in thread Thread-1 (ReplyAi):
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/tmp/TelegramGPT/./main.py", line 37, in ReplyAi
    gptResponse: str = g4f.ChatCompletion.create(model=g4f.Model.gpt_4, messages=[{"role": "user", "content": inputQuery}])
  File "/tmp/TelegramGPT/g4f/__init__.py", line 33, in create
    if stream else ''.join(engine._create_completion(model.name, messages, stream, **kwargs)))
  File "/tmp/TelegramGPT/g4f/Provider/Providers/Bing.py", line 342, in _create_completion
    for token in response:
  File "/tmp/TelegramGPT/g4f/Provider/Providers/Bing.py", line 313, in run
    next_val = loop.run_until_complete(gen.__anext__())
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/tmp/TelegramGPT/g4f/Provider/Providers/Bing.py", line 162, in stream_generate
    conversationId, clientId, conversationSignature = await create_conversation()
  File "/tmp/TelegramGPT/g4f/Provider/Providers/Bing.py", line 148, in create_conversation
    conversationId = create.json().get('conversationId')
  File "/usr/local/lib/python3.10/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Environement**
- Docker image: Python 3.10.11
- Location: Oracle instance is in Frankfurt

**Additional context**
Please note, the same exact script runs fine if launched on my personal PC

**Comment by iu2frl** [comment]
Up

**Comment by bagusindrayana** [comment]
> Up

Still error even in new version gpt4free?

Try debug with print response from bing as text probably invalid json response or something that response cant convert or parse to json.

Also did another provider or model (gpt3.5) work for you?
