### ISSUE TITLE
File "/Users/xxxli/freegpt-webui/run.py", line 1, in <module>

### ISSUE THREAD

**Issue by jesustoachild** [xtekky/gpt4free#738]
myMac % python3 run.py
Traceback (most recent call last):
  File "/Users/xxxli/freegpt-webui/run.py", line 1, in <module>
    from server.app import app
  File "/Users/xxxli/freegpt-webui/server/app.py", line 1, in <module>
    from flask import Flask
ModuleNotFoundError: No module named 'flask'

**Comment by asemlucben** [comment]
https://pypi.org/project/Flask/
