### ISSUE TITLE
requests.exceptions.TooManyRedirects: Exceeded 30 redirects. Unclosed client session client_session: <aiohttp.client.ClientSession object at 0x00000233B16F7F10>

### ISSUE THREAD

**Issue by NightZZD** [xtekky/gpt4free#759]
**Bug description**
I have cloned the project and set enviroment.I run testing/test.py and the Code error reported.

report:
Traceback (most recent call last):
  File "D:\PycharmProjects\gpt4free-main-718\testing\test.py", line 5, in <module>
    response = g4f.ChatCompletion.create(model='gpt-3.5-turbo', provider=g4f.Provider.Bing, messages=[
  File "D:\PycharmProjects\gpt4free-main-718\g4f\__init__.py", line 36, in create
    if stream else ''.join(engine._create_completion(model.name, messages, stream, **kwargs)))
  File "D:\PycharmProjects\gpt4free-main-718\g4f\Provider\Providers\Bing.py", line 343, in _create_completion
    for token in response:
  File "D:\PycharmProjects\gpt4free-main-718\g4f\Provider\Providers\Bing.py", line 314, in run
    next_val = loop.run_until_complete(gen.__anext__())
  File "D:\anaconda3\envs\gpt4free-main-718\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File "D:\PycharmProjects\gpt4free-main-718\g4f\Provider\Providers\Bing.py", line 163, in stream_generate
    conversationId, clientId, conversationSignature = await create_conversation()
  File "D:\PycharmProjects\gpt4free-main-718\g4f\Provider\Providers\Bing.py", line 124, in create_conversation
    create = requests.get('https://www.bing.com/turing/conversation/create',
  File "D:\anaconda3\envs\gpt4free-main-718\lib\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "D:\anaconda3\envs\gpt4free-main-718\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "D:\anaconda3\envs\gpt4free-main-718\lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "D:\anaconda3\envs\gpt4free-main-718\lib\site-packages\requests\sessions.py", line 725, in send
    history = [resp for resp in gen]
  File "D:\anaconda3\envs\gpt4free-main-718\lib\site-packages\requests\sessions.py", line 725, in <listcomp>
    history = [resp for resp in gen]
  File "D:\anaconda3\envs\gpt4free-main-718\lib\site-packages\requests\sessions.py", line 191, in resolve_redirects
    raise TooManyRedirects(
requests.exceptions.TooManyRedirects: Exceeded 30 redirects.
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x00000233B16F7F10>

**Environement**
- python version 3.8

**Comment by Pandas886** [comment]
same problem i meet
