### ISSUE TITLE
Interference api keeps erroring out

### ISSUE THREAD

**Issue by leulmteka** [xtekky/gpt4free#765]
**Bug description**
everything works fine besides the interference api. I'm just using the template provided in the readme: 

```
import openai

openai.api_key = my-api-key
openai.api_base = http://127.0.0.1:1337

chat_completion = openai.ChatCompletion.create(stream=False,
    model='gpt-3.5-turbo', messages=[{'role': 'user', 'content': 'write a poem about a tree'}])

#print(chat_completion.choices[0].message.content)

for token in chat_completion:
    
    content = token[choices][0][delta].get(content)
    if content != None:
        print(content)

```
I've started the server in the terminal and everything seems to be working good on that side.
I've tried port forwarding, disabling firewalls, etc.
This is what happens when i use openai.api_base = 'http://127.0.0.1:1337':
![image](https://github.com/xtekky/gpt4free/assets/72883746/3a72aa5f-7a2f-4adb-84ca-59d2f5921a33)

This is what happens when i use openai.api_base = 'http://192.168.1.207:1337':
![image](https://github.com/xtekky/gpt4free/assets/72883746/e8d02404-6f6a-42b0-ad8e-e8b944487afd)

This is what my terminal shows: 
![image](https://github.com/xtekky/gpt4free/assets/72883746/a415c9d8-a0d7-463e-beb9-be7cca7da7de)

It even crashed my internet at one point lol. anyone know any fixes?

**Environement**
python 3.11.4
- U.S.

**Comment by leulmteka** [comment]
> try http://127.0.0.1:1337/v1

same thing. for 127.0.0.1.

in the original post, i've already put v1. my app.py  has this line 
`@app.route("/v1/chat/completions", methods=['POST'])`

for 192.168.1.207, when i don't have a "v1" it gives me a HTTP 500 error. when I do it's the 404.

**Comment by leeeawa** [comment]
![image](https://github.com/xtekky/gpt4free/assets/114284437/580cf4fd-acad-49d4-b903-3abe805d14d7)
I can use it normally.

**Comment by GoAwayNow** [comment]
It looks like the endpoint isn't under /v1/. That said, I also get a 500 error. Here's the full output.

```
127.0.0.1 - - [04/Aug/2023 17:50:31] "POST //chat/completions HTTP/1.1" 500 -
Traceback (most recent call last):
  File "G:\gpt4free\venv\lib\site-packages\urllib3\connectionpool.py", line 790, in urlopen
    response = self._make_request(
  File "G:\gpt4free\venv\lib\site-packages\urllib3\connectionpool.py", line 491, in _make_request
    raise new_e
  File "G:\gpt4free\venv\lib\site-packages\urllib3\connectionpool.py", line 467, in _make_request
    self._validate_conn(conn)
  File "G:\gpt4free\venv\lib\site-packages\urllib3\connectionpool.py", line 1092, in _validate_conn
    conn.connect()
  File "G:\gpt4free\venv\lib\site-packages\urllib3\connection.py", line 642, in connect
    sock_and_verified = _ssl_wrap_socket_and_match_hostname(
  File "G:\gpt4free\venv\lib\site-packages\urllib3\connection.py", line 783, in _ssl_wrap_socket_and_match_hostname
    ssl_sock = ssl_wrap_socket(
  File "G:\gpt4free\venv\lib\site-packages\urllib3\util\ssl_.py", line 469, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls, server_hostname)
  File "G:\gpt4free\venv\lib\site-packages\urllib3\util\ssl_.py", line 513, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "C:\Python39\lib\ssl.py", line 501, in wrap_socket
    return self.sslsocket_class._create(
  File "C:\Python39\lib\ssl.py", line 1041, in _create
    self.do_handshake()
  File "C:\Python39\lib\ssl.py", line 1310, in do_handshake
    self._sslobj.do_handshake()
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "G:\gpt4free\venv\lib\site-packages\requests\adapters.py", line 486, in send
    resp = conn.urlopen(
  File "G:\gpt4free\venv\lib\site-packages\urllib3\connectionpool.py", line 844, in urlopen
    retries = retries.increment(
  File "G:\gpt4free\venv\lib\site-packages\urllib3\util\retry.py", line 470, in increment
    raise reraise(type(error), error, _stacktrace)
  File "G:\gpt4free\venv\lib\site-packages\urllib3\util\util.py", line 38, in reraise
    raise value.with_traceback(tb)
  File "G:\gpt4free\venv\lib\site-packages\urllib3\connectionpool.py", line 790, in urlopen
    response = self._make_request(
  File "G:\gpt4free\venv\lib\site-packages\urllib3\connectionpool.py", line 491, in _make_request
    raise new_e
  File "G:\gpt4free\venv\lib\site-packages\urllib3\connectionpool.py", line 467, in _make_request
    self._validate_conn(conn)
  File "G:\gpt4free\venv\lib\site-packages\urllib3\connectionpool.py", line 1092, in _validate_conn
    conn.connect()
  File "G:\gpt4free\venv\lib\site-packages\urllib3\connection.py", line 642, in connect
    sock_and_verified = _ssl_wrap_socket_and_match_hostname(
  File "G:\gpt4free\venv\lib\site-packages\urllib3\connection.py", line 783, in _ssl_wrap_socket_and_match_hostname
    ssl_sock = ssl_wrap_socket(
  File "G:\gpt4free\venv\lib\site-packages\urllib3\util\ssl_.py", line 469, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls, server_hostname)
  File "G:\gpt4free\venv\lib\site-packages\urllib3\util\ssl_.py", line 513, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "C:\Python39\lib\ssl.py", line 501, in wrap_socket
    return self.sslsocket_class._create(
  File "C:\Python39\lib\ssl.py", line 1041, in _create
    self.do_handshake()
  File "C:\Python39\lib\ssl.py", line 1310, in do_handshake
    self._sslobj.do_handshake()
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "G:\gpt4free\venv\lib\site-packages\flask\app.py", line 2213, in __call__
    return self.wsgi_app(environ, start_response)
  File "G:\gpt4free\venv\lib\site-packages\flask\app.py", line 2193, in wsgi_app
    response = self.handle_exception(e)
  File "G:\gpt4free\venv\lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "G:\gpt4free\venv\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "G:\gpt4free\venv\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "G:\gpt4free\venv\lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "G:\gpt4free\venv\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "G:\gpt4free\venv\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "G:\gpt4free\interference\app.py", line 19, in chat_completions
    response = ChatCompletion.create(model=model, stream=streaming,
  File "G:\gpt4free\g4f\__init__.py", line 36, in create
    if stream else ''.join(engine._create_completion(model.name, messages, stream, **kwargs)))
  File "G:\gpt4free\g4f\Provider\Providers\Forefront.py", line 25, in _create_completion
    response = requests.post( 'https://streaming.tenant-forefront-default.knative.chi.coreweave.com/free-chat',
  File "G:\gpt4free\venv\lib\site-packages\requests\api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
  File "G:\gpt4free\venv\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "G:\gpt4free\venv\lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "G:\gpt4free\venv\lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "G:\gpt4free\venv\lib\site-packages\requests\adapters.py", line 501, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
```
