### ISSUE TITLE
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'

### ISSUE THREAD

**Issue by SamokhinSergey** [xtekky/gpt4free#791]
Hi! Its clear install with pip. 
I try run example code from readme and have this:
Traceback (most recent call last):
  File "h:\FuzoBot\test.py", line 1, in <module>
    from g4f.Provider import (
  File "C:\Users\***\AppData\Roaming\Python\Python39\site-packages\g4f\__init__.py", line 3, in <module>
    from g4f import models
  File "C:\Users\***\AppData\Roaming\Python\Python39\site-packages\g4f\models.py", line 7, in <module>
    class Model:
  File "C:\Users\***\AppData\Roaming\Python\Python39\site-packages\g4f\models.py", line 10, in Model
    best_provider: ModuleType | None
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'

**Comment by MIDORIBIN** [comment]
@SamokhinSergey 
In g4f, Python 3.10 or above is required.

**Comment by xtekky** [comment]
should be fixed now
