### ISSUE TITLE
500 and error reported when using gpt-4

### ISSUE THREAD

**Issue by Joackk** [xtekky/gpt4free#852]
gpt3.5 can be used normally, but as soon as you use 4, the following error occurs, this is the server side of the error report
`192.168.31.109 - - [28/Aug/2023 08:54:49] "POST /chat/completions HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/home/joack/Desktop/gpt4free-main/venv/lib/python3.9/site-packages/flask/app.py", line 2213, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/joack/Desktop/gpt4free-main/venv/lib/python3.9/site-packages/flask/app.py", line 2193, in wsgi_app
    response = self.handle_exception(e)
  File "/home/joack/Desktop/gpt4free-main/venv/lib/python3.9/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/joack/Desktop/gpt4free-main/venv/lib/python3.9/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/joack/Desktop/gpt4free-main/venv/lib/python3.9/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/joack/Desktop/gpt4free-main/venv/lib/python3.9/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/joack/Desktop/gpt4free-main/venv/lib/python3.9/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/joack/Desktop/gpt4free-main/venv/lib/python3.9/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/joack/Desktop/gpt4free-main/interference/app.py", line 21, in chat_completions
    response = ChatCompletion.create(model=model, stream=stream, messages=messages)
  File "/home/joack/Desktop/gpt4free-main/g4f/__init__.py", line 27, in create
    raise Exception(f"{provider.__name__} is not working")
Exception: Liaobots is not working`

**Comment by w3bdesign** [comment]
You are trying to use Liaobots, see the error: "Exception: Liaobots is not working"

Try using a different provider

**Comment by Joackk** [comment]
> You are trying to use Liaobots, see the error: "Exception: Liaobots is not working"
> 
> Try using a different provider

hi，我使用的"python3 -m interference.app"来在第三方使用api，更改服务商是要修改服务器吗？

**Comment by xzripper** [comment]
Same bug
