### ISSUE TITLE
when i import g4f , TypeError: 'type' object is not subscriptable

### ISSUE THREAD

**Issue by fxyfw2** [xtekky/gpt4free#874]
C:\Users\fxy>python
**Python 3.8.17 (default, Jul  5 2023, 20:35:33) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32**
Type "help", "copyright", "credits" or "license" for more information.
**>>> import g4f**
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\develop\anaconda3\lib\site-packages\g4f\__init__.py", line 1, in <module>
    from .          import models
  File "D:\develop\anaconda3\lib\site-packages\g4f\models.py", line 2, in <module>
    from .Provider import Bard, BaseProvider, GetGpt, H2o, Liaobots, Vercel, Equing
  File "D:\develop\anaconda3\lib\site-packages\g4f\Provider\__init__.py", line 1, in <module>
    from .Acytoo        import Acytoo
  File "D:\develop\anaconda3\lib\site-packages\g4f\Provider\Acytoo.py", line 6, in <module>
    from .base_provider import BaseProvider
  File "D:\develop\anaconda3\lib\site-packages\g4f\Provider\base_provider.py", line 9, in <module>
    class BaseProvider(ABC):
  File "D:\develop\anaconda3\lib\site-packages\g4f\Provider\base_provider.py", line 21, in BaseProvider
    messages: list[dict[str, str]],
**TypeError: 'type' object is not subscriptable**

**Comment by MIDORIBIN** [comment]
@fxyfw2 
The current main branch does not support python 3.8 or lower.
Use python 3.9 or above, or wait until #875 is merged.

**Comment by fxyfw2** [comment]
> @fxyfw2 The current main branch does not support python 3.8 or lower. Use python 3.9 or above, or wait until #875 is merged.

thank you~
