### ISSUE TITLE
Liaobots is not working

### ISSUE THREAD

**Issue by Gegerout** [xtekky/gpt4free#879]
When using gpt4 model using this code:
response = g4f.ChatCompletion.create(
    model=g4f.models.gpt_4,
    messages=[{"role": "user", "content": "hi"}],
)  # alterative model setting

print(response)
Appears error: Liaobots is not working
Also it appears when using Liabots provider.
In the list of providers Liabots marked as actvie, but they aren't

**Comment by johnd0e** [comment]
With latest master I get another error:
```
Traceback (most recent call last):
  File "D:\AI\gpt4free\ttt.py", line 3, in <module>
    response = g4f.ChatCompletion.create(
  File "D:\AI\gpt4free\g4f\__init__.py", line 43, in create
    return result if stream else ''.join(result)
  File "D:\AI\gpt4free\g4f\Provider\base_provider.py", line 93, in create_completion
    yield from run_generator(cls.create_async_generator(model, messages, stream=stream, **kwargs))
  File "D:\AI\gpt4free\g4f\Provider\base_provider.py", line 122, in run_generator
    yield loop.run_until_complete(gen.__anext__())
  File "C:\Users\a\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "D:\AI\gpt4free\g4f\Provider\Liaobots.py", line 64, in create_async_generator
    response.raise_for_status()
  File "D:\AI\gpt4free\venv\lib\site-packages\aiohttp\client_reqrep.py", line 1005, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 403, message='Forbidden', url=URL('https://liaobots.com/api/user')
```

**Comment by hlohaus** [comment]
Last Week it worked.
Today the website doesn't Work too.
When the website not work,
we can't do somethings.
