### ISSUE TITLE
RunTime error: Event loop is closed.

### ISSUE THREAD

**Issue by VGChosen** [xtekky/gpt4free#892]
```

import speech_recognition as sr
import g4f
import pyttsx3

def recognize_speech_from_mic(recognizer, microphone):    
    if not isinstance(recognizer, sr.Recognizer):
        raise TypeError("`recognizer` must be a `Recognizer` instance")

    if not isinstance(microphone, sr.Microphone):
        raise TypeError("`microphone` must be a `Microphone` instance")

    with microphone as source:
        recognizer.adjust_for_ambient_noise(source, duration=1)  # Adjust for ambient noise for 1 second
        try:
            audio = recognizer.listen(source, timeout=5)  # Set a 5-second timeout for audio input
        except sr.WaitTimeoutError:
            return {"success": False, "error": "Audio input timed out", "transcription": None}

    ques_trans = {
        "success": True,
        "error": None,
        "transcription": None
    }

    try:
        ques_trans["transcription"] = recognizer.recognize_google(audio)
    except sr.RequestError:
        ques_trans["success"] = False
        ques_trans["error"] = "API unavailable"
    except sr.UnknownValueError:
        ques_trans["error"] = "Unable to recognize speech"

    return ques_trans

recognizer = sr.Recognizer()
microphone = sr.Microphone()
microphone.energy_threshold = 4000
engine = pyttsx3.init()

def say_res_after_gen(ask):
    response_collection = g4f.ChatCompletion.create(
        model="gpt-3.5-turbo",
        provider=g4f.Provider.DeepAi,
        messages=[{"role": "user", "content": ask}],
        stream=True,
    )

    for message in response_collection:
        engine.say(message)
        engine.runAndWait()

while True:
    question = recognize_speech_from_mic(recognizer, microphone)
    if question["success"]:
        say_res_after_gen(question["transcription"])
    else:
        engine.say("I was not able to catch you. Can you repeat?")
        engine.runAndWait()

```

My code works fine for sometime until it eventually gives this error log:
```

Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x000002DF6280BA30>   
Traceback (most recent call last):
  File "C:\Users\vivek\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 116, in __del__y", line 116, in __del__                                                                    y", line 108, in close
  File "C:\Users\vivek\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.pline 745, in call_soony", line 108, in close                                                                      line 510, in _check_closed
  File "C:\Users\vivek\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", 
line 745, in call_soon
  File "C:\Users\vivek\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", 
line 510, in _check_closed
RuntimeError: Event loop is closed

```
Extreamely sorry for the way of questioning. Relatively new

**Comment by hlohaus** [comment]
Try to add this lines before you use g4f:

import asyncio asyncio.set_event_loop_policy(asyncio.WindowsSelectorEventLoopPolicy())

**Comment by VGChosen** [comment]
@hlohaus  Thanks! It worked!
If it is possible for you can you explain it?

**Comment by alexferra** [comment]
RuntimeError: No snlm0e value.
