### ISSUE TITLE
WindowsProactorEventLoopPolicy is not supported + NotImplementedError

### ISSUE THREAD

**Issue by johnd0e** [xtekky/gpt4free#898]
Recent changes introduced by @hlohaus have broke a couple the providers, in same manner.

Environment: Windows 10, Python 3.10.11

Sample code:
```py
import g4f
response = g4f.ChatCompletion.create(model='gpt-3.5-turbo', provider=g4f.Provider.OpenaiChat, messages=[
#response = g4f.ChatCompletion.create(model=g4f.models.default, provider=g4f.Provider.Vercel, messages=[
#response = g4f.ChatCompletion.create(model='gpt-3.5-turbo', provider=g4f.Provider.You, messages=[
                                     {"role": "user", "content": "Hello"}])

print(response)
```

Result:
```
D:\AI\gpt4free\venv\lib\site-packages\curl_cffi\requests\session.py:471: UserWarning:
WindowsProactorEventLoopPolicy is not supported, you can use the selector loop by:
    asyncio.set_event_loop_policy(asyncio.WindowsSelectorEventLoopPolicy())

  warnings.warn(WINDOWS_WARN)
Exception ignored from cffi callback <function socket_function at 0x000002A4FC871A20>:
Traceback (most recent call last):
  File "D:\AI\gpt4free\venv\lib\site-packages\curl_cffi\aio.py", line 62, in socket_function
    loop.add_reader(sockfd, async_curl.process_data, sockfd, CURL_CSELECT_IN)
  File "C:\Users\a\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 518, in add_reader
    raise NotImplementedError
NotImplementedError:
Exception ignored from cffi callback <function socket_function at 0x000002A4FC871A20>:
Traceback (most recent call last):
  File "D:\AI\gpt4free\venv\lib\site-packages\curl_cffi\aio.py", line 68, in socket_function
    async_curl._sockfds.remove(sockfd)
KeyError: 760
Exception ignored from cffi callback <function socket_function at 0x000002A4FC871A20>:
Traceback (most recent call last):
  File "D:\AI\gpt4free\venv\lib\site-packages\curl_cffi\aio.py", line 65, in socket_function
    loop.add_writer(sockfd, async_curl.process_data, sockfd, CURL_CSELECT_OUT)
  File "C:\Users\a\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 524, in add_writer
    raise NotImplementedError
NotImplementedError:
Exception ignored from cffi callback <function socket_function at 0x000002A4FC871A20>:
Traceback (most recent call last):
  File "D:\AI\gpt4free\venv\lib\site-packages\curl_cffi\aio.py", line 62, in socket_function
    loop.add_reader(sockfd, async_curl.process_data, sockfd, CURL_CSELECT_IN)
  File "C:\Users\a\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 518, in add_reader
    raise NotImplementedError
NotImplementedError:
```

**Comment by hlohaus** [comment]
Python before 3.11 have a Bug under Windows. Try to add this Line in your Code to fix it:

asyncio.set_event_loop_policy(asyncio.WindowsSelectorEventLoopPolicy())

**Comment by johnd0e** [comment]
Thank you, this helped.
May be put this info to README?
