### ISSUE TITLE
You not working

### ISSUE THREAD

**Issue by johnd0e** [xtekky/gpt4free#902]
```
Traceback (most recent call last):
  File "D:\AI\gpt4free\nostream.py", line 11, in <module>
    response = g4f.ChatCompletion.create(model='gpt-3.5-turbo', provider=g4f.Provider.You, messages=[
  File "D:\AI\gpt4free\g4f\__init__.py", line 52, in create
    return result if stream else ''.join(result)
  File "D:\AI\gpt4free\g4f\Provider\base_provider.py", line 93, in create_completion
    yield from run_generator(cls.create_async_generator(model, messages, stream=stream, **kwargs))
  File "D:\AI\gpt4free\g4f\Provider\base_provider.py", line 122, in run_generator
    yield loop.run_until_complete(gen.__anext__())
  File "C:\Users\a\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "D:\AI\gpt4free\g4f\Provider\You.py", line 36, in create_async_generator
    response.raise_for_status()
  File "D:\AI\gpt4free\venv\lib\site-packages\curl_cffi\requests\cookies.py", line 51, in raise_for_status
    raise RequestsError(f"HTTP Error {self.status_code}: {self.reason}")
curl_cffi.requests.errors.RequestsError: HTTP Error 403:
```

**Comment by zing75blog** [comment]
same issues
