### ISSUE TITLE
Python Package Doesn't Work Since 0.0.2.9

### ISSUE THREAD

**Issue by thealphard** [xtekky/gpt4free#906]
**Bug description**
I use g4f version 0.0.2.9 and Python version 3.9. Here's the code bit that causes problem:
import g4f
```
--- some other code ---
                        response = g4f.ChatCompletion.create(
			model='gpt-3.5-turbo',
			messages=[
				{'role': 'user', 
	 			'content': # [some private context with correct syntax]
				},
				{'role': 'user', 
	 			'content': inp
				}
			],
			stream=True,
			provider= g4f.Provider.Acytoo # Does not matter which provider I use, I get the error anyway
		)
		cvp = ''
		for message in response:
			rp = message.replace('\n', '')
			cvp += rp
		return cvp
```
This code results in exception:
```
Traceback (most recent call last):
  File "[path]/code.py", line 53, in <module>
    print(Cevap(input(">>> ")))
  File "[path]/code.py", line 46, in Cevap
    for message in response:
  File "[path]\AppData\Local\Programs\Python\Python39\lib\site-packages\g4f\Provider\base_provider.py", line 93, in create_completion
    yield from run_generator(cls.create_async_generator(model, messages, stream=stream, **kwargs))
  File "[path]\AppData\Local\Programs\Python\Python39\lib\site-packages\g4f\Provider\base_provider.py", line 122, in run_generator
    yield loop.run_until_complete(gen.__anext__())
  File "[path]\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "[path]AppData\Local\Programs\Python\Python39\lib\site-packages\g4f\Provider\ChatgptAi.py", line 50, in create_async_generator
    raise RuntimeError("No system data")
RuntimeError: No system data
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x00000292460C2790>
Traceback (most recent call last):
  File "[path]\AppData\Local\Programs\Python\Python39\lib\asyncio\proactor_events.py", line 116, in __del__
  File "[path]\AppData\Local\Programs\Python\Python39\lib\asyncio\proactor_events.py", line 108, in close
  File "[path]\gsutk\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 751, in call_soon
  File "[path]\gsutk\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 515, in _check_closed
RuntimeError: Event loop is closed
```
(The code is inside the function Cevap, which takes a string input as variable "inp")

**Environement**
- I use Python 3.9.13 with g4f 0.0.2.9 and latest asyncio version.
- My location is Ankara, Türkiye

**Comment by Tsunami014** [comment]
Thanks lots to @hlohaus for [this reply](https://github.com/xtekky/gpt4free/issues/892#issuecomment-1717917518):
> Try to add this lines before you use g4f:
> 
> ```
> import asyncio
> asyncio.set_event_loop_policy(asyncio.WindowsSelectorEventLoopPolicy())
> ```
