### ISSUE TITLE
asyncio Loop

### ISSUE THREAD

**Issue by jackfood** [xtekky/gpt4free#908]
i encountered this error.

Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x000001EA4EE555A0>
Traceback (most recent call last):
  File "D:\Python\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "D:\Python\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "D:\Python\lib\asyncio\base_events.py", line 745, in call_soon
    self._check_closed()
  File "D:\Python\lib\asyncio\base_events.py", line 510, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed

**Comment by LinJia21** [comment]
i encountered this error,too.when I use provider=g4f.Provider.DeepAi

**Comment by hlohaus** [comment]
I changed the used event loop on windows.
Please update your g4f:

pip install g4f --upgrade
