### ISSUE TITLE
error while using bard

### ISSUE THREAD

**Issue by IYSTREEM** [xtekky/gpt4free#932]
when i try to use bard with this code 
```import g4f
from g4f.Provider import (
    Bard,
    Bing,
    HuggingChat,
    OpenAssistant,
    OpenaiChat,
)
response = g4f.ChatCompletion.create(
    model=g4f.models.default,
    messages=[{"role": "user", "content": "Hello"}],
    provider=Bard,
    #cookies=g4f.get_cookies(".google.com"),
    cookies={"cookie_name": "value", "cookie_name2": "value2"},
    auth=True
)```


 im getting this error someone please help me


`Traceback (most recent call last):
  File "C:\Users\DFIT\Desktop\'\AL\al_test.py", line 23, in <module>
    response = g4f.ChatCompletion.create(
  File "C:\Users\DFIT\AppData\Local\Programs\Python\Python39\lib\site-packages\g4f\__init__.py", line 51, in create
    return result if stream else ''.join(result)
  File "C:\Users\DFIT\AppData\Local\Programs\Python\Python39\lib\site-packages\g4f\Provider\base_provider.py", line 72, in create_completion
    yield asyncio.run(cls.create_async(model, messages, **kwargs))
  File "C:\Users\DFIT\AppData\Local\Programs\Python\Python39\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\DFIT\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "C:\Users\DFIT\AppData\Local\Programs\Python\Python39\lib\site-packages\g4f\Provider\Bard.py", line 50, in create_async
    raise RuntimeError("No snlm0e value.")
RuntimeError: No snlm0e value.
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x000001D4A3474E50>
Traceback (most recent call last):
  File "C:\Users\DFIT\AppData\Local\Programs\Python\Python39\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "C:\Users\DFIT\AppData\Local\Programs\Python\Python39\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "C:\Users\DFIT\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 746, in call_soon
    self._check_closed()
  File "C:\Users\DFIT\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 510, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed`

**Comment by IYSTREEM** [comment]
nvm i found what i was doing wrong
