### ISSUE TITLE
Maybe HuggingChat Provider  is not working

### ISSUE THREAD

**Issue by embarce** [xtekky/gpt4free#945]
**Bug description**
In Docker server

I used the HuggingChat Provider for chat services and provided cookie parameters, but the service did not return as expected.

Provider  is HuggingChat   model is OpenAssistant/oasst-sft-6-llama-30b-xor

My Exception:

Debugging middleware caught exception in streamed response at a point where response headers were already sent.
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/werkzeug/wsgi.py", line 289, in __next__
    return self._next()
  File "/usr/local/lib/python3.9/site-packages/werkzeug/wrappers/response.py", line 32, in _iter_encoded
    for item in iterable:
  File "/app/interference/app.py", line 44, in streaming
    for chunk in response:
  File "/app/g4f/Provider/base_provider.py", line 117, in create_completion
    yield loop.run_until_complete(gen.__anext__())
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/app/g4f/Provider/HuggingChat.py", line 76, in create_async_generator
    async for line in response.content:
  File "/usr/local/lib/python3.9/site-packages/aiohttp/streams.py", line 35, in __anext__
    rv = await self.read_func()
  File "/usr/local/lib/python3.9/site-packages/aiohttp/streams.py", line 311, in readline
    return await self.readuntil()
  File "/usr/local/lib/python3.9/site-packages/aiohttp/streams.py", line 343, in readuntil
    await self._wait("readuntil")
  File "/usr/local/lib/python3.9/site-packages/aiohttp/streams.py", line 304, in _wait
    await waiter
aiohttp.client_exceptions.ClientPayloadError: Response payload is not completed

**Environement**
- python version 3.9
- location Japan

**Additional context**
And I try to meta-llama/Llama-2-70b-chat-hf or codellama/CodeLlama-34b-Instruct-hf this retrun same error code

**Comment by hlohaus** [comment]
I created a PR for HuggingChat
