### ISSUE TITLE
Error in Windows

### ISSUE THREAD

**Issue by sancho1952007** [xtekky/gpt4free#956]
COMMAND: waitress-serve --listen=127.0.0.1:4200 main:app

LOGS:  
INFO:waitress:Serving on http://127.0.0.1:4200
ERROR:main:Exception on /generate [GET]
Traceback (most recent call last):
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USERNAME\Music\Projects\Spacy Voice Assistant\main.py", line 17, in generate
    response = g4f.ChatCompletion.create(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python311\Lib\site-packages\g4f\__init__.py", line 69, in create
    return result if stream else ''.join(result)
                                 ^^^^^^^^^^^^^^^
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python311\Lib\site-packages\g4f\Provider\retry_provider.py", line 54, in create_completion
    self.raise_exceptions()
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python311\Lib\site-packages\g4f\Provider\retry_provider.py", line 77, in raise_exceptions
    raise RuntimeError("\n".join(["All providers failed:"] + [
RuntimeError: All providers failed:
AItianhuSpace: RuntimeError: There is no current event loop in thread 'waitress-0'.
ChatgptLogin: RuntimeError: There is no current event loop in thread 'waitress-0'.
AItianhu: RuntimeError: There is no current event loop in thread 'waitress-0'.
Aivvm: HTTPError: 403 Client Error: Forbidden for url: https://chat.aivvm.com/api/chat
Aichat: RuntimeError: There is no current event loop in thread 'waitress-0'.
DeepAi: RuntimeError: There is no current event loop in thread 'waitress-0'.
ChatgptAi: RuntimeError: There is no current event loop in thread 'waitress-0'.
Myshell: RuntimeError: There is no current event loop in thread 'waitress-0'.
Aibn: RuntimeError: There is no current event loop in thread 'waitress-0'.
GptGo: RuntimeError: There is no current event loop in thread 'waitress-0'.

**Comment by VadimBoev** [comment]
The fact is that "g4f.ChatCompletion.create" creates a separate thread and is executed by a separate thread. And your error says that it is not possible to start a thread in a thread.

**Comment by hlohaus** [comment]
You can try use create_async.
It is a Windows + Asyncio issue in core.

**Comment by sancho1952007** [comment]
How do I do that?

**Comment by hlohaus** [comment]
The issue is solved in the new version.

**Comment by sancho1952007** [comment]
Great, thanks will check it!
