### ISSUE TITLE
There is no current event loop in thread 'Thread-6 (process_request_thread)'.

### ISSUE THREAD

**Issue by ahmedosman2001** [xtekky/gpt4free#967]
When i run 
`g4f.ChatCompletion.create(g4f.ChatCompletion.create(
    model=g4f.models.default,
    provider=g4f.Provider.Bing,
    messages=msg,
    stream=False,
    auth="random_cookie",
))` inside flask server. i get this error: `There is no current event loop in thread 'Thread-6 (process_request_thread)'.` it works fine without flask server but when i use it as Flask server API, i get this error.

**Comment by technicca** [comment]
Same error when using API, with or without docker:

```
gpt4free-gpt4free-1  | Traceback (most recent call last):
gpt4free-gpt4free-1  |   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1478, in __call__
gpt4free-gpt4free-1  |     return self.wsgi_app(environ, start_response)
gpt4free-gpt4free-1  |   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1458, in wsgi_app
gpt4free-gpt4free-1  |     response = self.handle_exception(e)
gpt4free-gpt4free-1  |   File "/usr/local/lib/python3.9/site-packages/flask_cors/extension.py", line 176, in wrapped_function
gpt4free-gpt4free-1  |     return cors_after_request(app.make_response(f(*args, **kwargs)))
gpt4free-gpt4free-1  |   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1455, in wsgi_app
gpt4free-gpt4free-1  |     response = self.full_dispatch_request()
gpt4free-gpt4free-1  |   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 869, in full_dispatch_request
gpt4free-gpt4free-1  |     rv = self.handle_user_exception(e)
gpt4free-gpt4free-1  |   File "/usr/local/lib/python3.9/site-packages/flask_cors/extension.py", line 176, in wrapped_function
gpt4free-gpt4free-1  |     return cors_after_request(app.make_response(f(*args, **kwargs)))
gpt4free-gpt4free-1  |   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 867, in full_dispatch_request
gpt4free-gpt4free-1  |     rv = self.dispatch_request()
gpt4free-gpt4free-1  |   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 852, in dispatch_request
gpt4free-gpt4free-1  |     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
gpt4free-gpt4free-1  |   File "/app/interference/app.py", line 22, in chat_completions
gpt4free-gpt4free-1  |     response = ChatCompletion.create(model=model, stream=stream, messages=messages)
gpt4free-gpt4free-1  |   File "/app/g4f/__init__.py", line 69, in create
gpt4free-gpt4free-1  |     return result if stream else ''.join(result)
gpt4free-gpt4free-1  |   File "/app/g4f/Provider/retry_provider.py", line 54, in create_completion
gpt4free-gpt4free-1  |     self.raise_exceptions()
gpt4free-gpt4free-1  |   File "/app/g4f/Provider/retry_provider.py", line 77, in raise_exceptions
gpt4free-gpt4free-1  |     raise RuntimeError("\n".join(["All providers failed:"] + [
gpt4free-gpt4free-1  | RuntimeError: All providers failed:
gpt4free-gpt4free-1  | ChatgptLogin: RuntimeError: There is no current event loop in thread 'Thread-16'.
gpt4free-gpt4free-1  | Aibn: RuntimeError: There is no current event loop in thread 'Thread-16'.
gpt4free-gpt4free-1  | GptGo: RuntimeError: There is no current event loop in thread 'Thread-16'.
gpt4free-gpt4free-1  | DeepAi: RuntimeError: There is no current event loop in thread 'Thread-16'.
gpt4free-gpt4free-1  | Aivvm: HTTPError: 403 Client Error: Forbidden for url: https://chat.aivvm.com/api/chat
gpt4free-gpt4free-1  | ChatgptAi: RuntimeError: There is no current event loop in thread 'Thread-16'.
gpt4free-gpt4free-1  | Aichat: RuntimeError: There is no current event loop in thread 'Thread-16'.
gpt4free-gpt4free-1  | Myshell: RuntimeError: There is no current event loop in thread 'Thread-16'.
gpt4free-gpt4free-1  | AItianhu: RuntimeError: There is no current event loop in thread 'Thread-16'.
gpt4free-gpt4free-1  | AItianhuSpace: RuntimeError: There is no current event loop in thread 'Thread-16'.
```

**Comment by FireStreaker2** [comment]
also getting this issue in a flask app, trying to create a streamed response with g4f
```py
def _streaming(self, model, messages):
        return Response(
            g4f.ChatCompletion.create(
                model=model,
                messages=[{"role": "user", "content": f"{messages}"}],
                stream=True,
            ),
            mimetype="application/json",
        )
 ```

**Comment by axxag** [comment]
Temporary workaround:

```diff
diff --git a/interference/app.py b/interference/app.py
 from g4f import ChatCompletion
+import asyncio

def chat_completions():
     stream = request.get_json().get("stream", False)
     messages = request.get_json().get("messages")

+    asyncio.set_event_loop(asyncio.new_event_loop())
     response = ChatCompletion.create(model=model, stream=stream, messages=messages)
```

**Comment by hlohaus** [comment]
i added:
    asyncio.set_event_loop(asyncio.new_event_loop())
to the g4f package
