### ISSUE TITLE
I think g4f.Provider.ChatgptAi have some problem today.

### ISSUE THREAD

**Issue by tianlichunhong** [xtekky/gpt4free#977]
Before g4f.Provider.ChatgptAi work fine. But today it can't work. Error as below.  v-0.1.4.0 and v-0.1.4.5 both not work. I think something changed at https://chatgpt.ai/ 

Traceback (most recent call last):
  File "/test.py", line 41, in <module>
    for message in response:
  File "/usr/local/lib/python3.11/dist-packages/g4f/Provider/base_provider.py",                                                                                                                                                                              line 109, in create_completion
    yield loop.run_until_complete(gen.__anext__())
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/base_events.py", line 653, in run_until_comp                                                                                                                                                                             lete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/g4f/Provider/ChatgptAi.py", line                                                                                                                                                                              50, in create_async_generator
    raise RuntimeError("No system data")
RuntimeError: No system data

**Comment by tianlichunhong** [comment]
Also g4f.Provider.Ails not work. Please help to check. Thank you!
