### ISSUE TITLE
Having problem with creating ChatComplement in Streaming mode

### ISSUE THREAD

**Issue by ZYpS-leader** [xtekky/gpt4free#986]
**Environment**
What I use is `Python 3.7.4` with `GCC 7.5.0` on Ubuntu, Linux.

**My code and bugs**
I tried to use the following statements to use CHATGPT:
- Acytoo
- Aivvm
- Ails
Without streaming, they worked really well. But while I was trying to use the following code to make it with streaming mode, it raised an Exception which looked like this:
```
Traceback (most recent call last):
  File "/root/programs/ps2/doai.py", line 26, in <module>
    test_get_with_stream()
  File "/root/programs/ps2/doai.py", line 13, in test_get_with_stream
    new_words, new_ans, response = get_with_stream(append(sends,get), ans, rolename=name)
  File "/root/programs/ps2/ais.py", line 50, in get_with_stream
    for r in response:
  File "/usr/local/lib/python3.7/site-packages/g4f/Provider/base_provider.py", line 90, in create_completion
    yield loop.run_until_complete(gen.__anext__())
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.7/site-packages/g4f/Provider/Acytoo.py", line 31, in create_async_generator
    response.raise_for_status()
  File "/usr/local/lib/python3.7/site-packages/aiohttp/client_reqrep.py", line 1005, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 422, message='Unprocessable Entity', url=URL('https://chat.acytoo.com/api/completions')
```
And my code is:
1.`doai.py`
```python
from ais import get_with_stream, append
def test_get_with_stream(name=""):
    """
    Test get_with_stream function
    """
    # Test with stream
    sends = ""
    ans = ""
    while True:
        get = input(" >: ")
        if get != "/clearall" and get != "/getall":
            print("Generating...")
            new_words, new_ans, response = get_with_stream(append(sends,get), ans, rolename=name)
            sends = new_words
            ans = new_ans
            print("Ans:",response)
            ans.append(answer)
        elif get == "/getall":
            print("All sent messages:",sends)
            print("All received messages:",ans)
        else:
            sends = []
            ans = []
        
        
test_get_with_stream("chatgpt")
```

2.`ais.py`
```python
import g4f

SPLIT="somethingsplit"
def append(old, new):
    return old + SPLIT + new

def split(old:str):
    return old.split(SPLIT)


def get_with_stream(words:str, ans:str, rolename:str):
    words = split(words)
    ans = split(ans)
    new = words[-1]
    already = []
    for i in range(len(words)-1):
        already.append({"role":"user", "content":words[i]})
        already.append({"role":rolename,"content":ans[-1]})
    already.append({"role":"user", "content":new})
    response = g4f.ChatCompletion.create(
        model="gpt-3.5-turbo",
        provider=g4f.Provider.Acytoo,
        messages=already,
        stream=True,
        )
    for r in response:
        an = r
    ans.append(an)
    w = ""
    a = ""
    for i in range(len(words)):
        w = append(w, words[i])
        a = append(a, ans[i])
    return w,a,an
```

Maybe they are not easy to understand...
the "rolename" is used to change the role name while sending message to the website offering gpt.
It supposed that the exception above was de to the wrong rolename. **I really hope you will tell me what the correct rolename of the website excatly woule be.**

Very thankful for your help.

**Comment by ZYpS-leader** [comment]
@xtekky

**Comment by xtekky** [comment]
Please try again, there was some updates.
try not setting the provider, it will then be set automatically with a retry system

**Comment by ZYpS-leader** [comment]
@xtekky I'm not sure with what you mean. I tried with `pip install --upgrade g4f` and  `pip install -U g4f` (of course, they keep the same meaning), but they all told me that I have got the latest version. However, the problem above eas still existing. 

I'm not sure why, but I sincerely thank for you help. I'm looking toward to your reply.
